### ISSUE TITLE
Lint for unspecified type arguments when a type parameter has an upper bound.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#10]
Or more assertively:

**DO: specify a type argument when a type parameter has an upper bound.**

As a motivational example take the `dart:math Point` class:

```
class Point<T extends num>
```

The trouble is that this is legal:

`Point p = new Point('hello', 'world');`

and only fails at runtime if `magnitude` is called:

```
Unhandled exception:
type 'String' is not a subtype of type 'int' of 'times'.
```

To be sure `Point` is a special case but a general rule might be useful since in general if an upper bound has been defined `dynamic` is almost certainly _not_ what's intended.

**Comment by srawlins** [comment]
Since Dart 2 enforces argument types, I think this request is stale.
