### ISSUE TITLE
omit_local_variable_types conflicts with --no-implicit-dynamic

### ISSUE THREAD

**Issue by natebosch** [dart-lang/linter#1006]
Specifically this conflicts with `strong_mode_implicit_dynamic_variable`.

**Comment by srawlins** [comment]
Linter rules and analyzer modes can conflict. What is the bug and what would you like the fix to be?

**Comment by natebosch** [comment]
At the time I wanted `dynamic` to be an allowed exception to `omit_local_variable_types`. I've hit other blockers to `--no-implicit-dynamic` so it hasn't been something I've pushed on.

**Comment by srawlins** [comment]
I see. So in this example:

```dart
dynamic x = 0;
dynamic y = x;
```

you'd like `omit_local_variable_types` to not  complain. Seems reasonable.

**Comment by pq** [comment]
Is the proposal to make this conditional on whether `no-implicit-dynamic` is enabled?

**Comment by natebosch** [comment]
In my opinion it doesn't need to be conditional. `dynamic` is dangerous - if you're using it and want to make it explicit I think the lint should allow that regardless of other configuration.

**Comment by pq** [comment]
@bwilkerson: any thoughts/reservations?

**Comment by bwilkerson** [comment]
The purpose of this rule is to enforce the style guide. I don't know whether the style guide has changed since I last looked at it, but it seems to me that making `dynamic` an exception is consistent with the guide.

**Comment by pq** [comment]
https://github.com/dart-lang/linter/pull/1594 👍
