### ISSUE TITLE
Consider migrating categories to tags

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1020]
In the current incarnation, lints can belong to a single category but moving forward it would be interesting to consider a tag approach.  A few ideas for tags that come to mind:

* FLUTTER
* PACKAGE: MOCKITO
* DEPRECATED
* EXPENSIVE

But I'm just spit-balling!

/cc @srawlins

**Comment by srawlins** [comment]
I like those. I also like, STYLE, PERFORMANCE, ERROR-PRONE, CODE BLOAT

**Comment by pq** [comment]
👍 

@srawlins qq:

ERROR-PRONE -- do you mean the lint is prone to error?  (e.g., false positives?)

**Comment by srawlins** [comment]
No, I mean like "Code that violates this lint is error-prone", like `control_flow_in_finally`, and `no_adjacent_strings_in_list` and `unrelated_type_equality_checks`.

**Comment by srawlins** [comment]
I see now that the "categories" are actually `Group`s defined in the analyzer, with a few built-in values. It's ok having non-built-in values. But I'll have to update `LintRule` in the SDK to specify `groups` now instead of `group`.

`LintGroup` also uses groups for its `compareTo`:

https://github.com/dart-lang/sdk/blob/77202bf2b03451a64ecd9fe9885f961a640b72e8/pkg/analyzer/lib/src/lint/linter.dart#L255-L261

Strange. Having multiple groups per rule will break this notion.

**Comment by pq** [comment]
Yeah.  This wasn't entirely by design.  The group stuff got pulled into analyzer in a bulk move to ease maintenance.  It's probably not the best place for it to be if we're going to be changing it.  As for `compareTo`, we can re-think it.  There are probably better ways to establish natural order.

**Comment by pq** [comment]
@jcollins-g just gave (well, **_is giving_** 😛) a demo of category support for `dartdoc` (https://github.com/dart-lang/dartdoc/issues/1681) which is making me think we should seriously consider using it rather than creating our own new thing.

**Comment by srawlins** [comment]
Hi @pq the category/tag concept doesn't seem very complex. Right now the Group class in analyzer is super small. What complexity would we avoid duplicating? In particular the Category and Categorization classes (from dartdoc's [model.dart](https://github.com/dart-lang/dartdoc/blob/master/lib/src/model.dart)) I think have a lot of complexity that would make this harder to integrate than to just adjust the Group class.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/6c6b1040b4ab26155be8c61d8c28a294a118606c
