### ISSUE TITLE
Thoughts on configs for linter

### ISSUE THREAD

**Issue by sethladd** [dart-lang/linter#103]
I wonder if users would appreciate more semantic configurations for various linting levels. Instead of giving our users hundreds of individual options, what if we grouped them with more meaning?
- "Tell me if my program fails to start"
- "Tell me if my program is likely not to function as written"
- "Tell me if my program has messy code"

Each of those is a collection of errors/warnings/hints/lints.

There may be other semantic groupings...

**Comment by zoechi** [comment]
also like "Dart style guide" rule or "Flutter style guide rule"

**Comment by pq** [comment]
Conversation picked up in #288.
