### ISSUE TITLE
Clean up all internal analyzer references.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1053]
Follow-up from https://github.com/dart-lang/sdk/issues/26728#issuecomment-401372269, we should clean up all of the places we're needlessly reaching into analyzer internals.

**Comment by pq** [comment]
@bwilkerson: are there plans for anything comparable to `ScopedVisitor` becoming API?

https://github.com/dart-lang/linter/blob/a9d0ce070ae618c8263d99deeefa7ae03d97a7ab/lib/src/rules/unnecessary_this.dart#L68

**Comment by pq** [comment]
A few more:

https://github.com/dart-lang/linter/blob/2ccfba5456d3da79346936d012c8486b39f4b399/lib/src/util/condition_scope_visitor.dart#L325

https://github.com/dart-lang/linter/blob/2ccfba5456d3da79346936d012c8486b39f4b399/lib/src/ast.dart#L302-L306

**Comment by bwilkerson** [comment]
I hope not! I don't want analyzer to have any knowledge of Dart's scoping rules (except indirectly through the front end).

That said, the use case here is valid and not one that we've yet figured out how to support in the API. What this and several other lints is trying to do is ask the question "what would the analysis have produced if ...". In this case, it's "if the `this.` had been omitted" and serves as a check that removing it is a valid thing to do.

@kmillikin Have you given any thought as to whether or how the front end might be able to answer such questions?

**Comment by pq** [comment]
Now that we're in the SDK, there's a lot less motivation for this. Closing.
