### ISSUE TITLE
consider enabling lint always_declare_return_types

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#1070]
(changes can be seen on #1064)

This lint enforce the rules [DO type annotate public APIs](https://github.com/dart-lang/site-www/blob/7e1e470dc838e0fdad4b2743a1aafc05674d8d65/src/_guides/language/effective-dart/design.md#do-type-annotate-public-apis) and [PREFER type annotating private declarations](https://github.com/dart-lang/site-www/blob/7e1e470dc838e0fdad4b2743a1aafc05674d8d65/src/_guides/language/effective-dart/design.md#prefer-type-annotating-private-declarations).

(@munificent  I can't find those two rules in the current Effective Dart version and I really don't understand why they disappeared as they allowed to catch a lot of issues)

**Comment by pq** [comment]
Thanks for opening the issue to discuss @a14n!  I've changed the name to reflect how this is a conversation (rather than a prescription) --- sorry if that feels weird; if so, just change it back!

As for the content, as I said in #1064, I'm not in favor of this lint for the linter code base but would be curious to hear other perspectives.

Repeat of what I wrote there:

> I think it just adds noise for visitor implementations and is really gratuitous in tests.

> So, to clarify a little, I'm very much in favor of this rule for any kind of public API where explicit types serve as valuable documentation. Having said that, the more folks contribute to the linter I realize there's a sense in which it's all a bit public and we should strive for clarity (maybe, at times, at the expense of brevity and shortcuts favored by, possibly, only me) in places I never anticipated it being valuable. Especially if this change might reduce the chance of bugs. In that case, best I just get over myself! 😄

**Comment by a14n** [comment]
[My previous comment](https://github.com/dart-lang/linter/pull/1064#issuecomment-402273883):

>I tends to always type methods so I don't see those changes as noise (moreover if this can catch bugs). In linter codebase the `Visitor<void>` pattern been almost everywhere I may understand that all those `void` could be seen as noise. However if someone creates a lint using a `Visitor<String>` this would **catch runtime errors** if a visit method return int because its signature was `visitXXX(node)` without return type.

This was following the rules :

- [DO type annotate public APIs](https://github.com/dart-lang/site-www/blob/7e1e470dc838e0fdad4b2743a1aafc05674d8d65/src/_guides/language/effective-dart/design.md#do-type-annotate-public-apis)
  >Type annotations are important documentation for how a library should be used. Annotating the parameter and return types of public methods and functions helps users understand what the API expects and what it provides.
  >
  >Note that if a public API accepts a range of values that Dart's type system cannot express, then it is acceptable to leave that untyped. In that case, the implicit dynamic is the correct type for the API.
  >
  >For code internal to a library (either private, or things like nested functions) annotate where you feel it helps, but don't feel that you must provide them.
- [PREFER type annotating private declarations](https://github.com/dart-lang/site-www/blob/7e1e470dc838e0fdad4b2743a1aafc05674d8d65/src/_guides/language/effective-dart/design.md#prefer-type-annotating-private-declarations).
  >Type annotations on your public API help users of your code. Nearly as important is guiding maintainers of your code. Adding type annotations to internal member and variable declarations can future readers of your code understand it, and help corral bugs.

Without return type the result will be seen as `dynamic` and everything can be called (even unexisting methods). Even private methods shouldn't be an exception imho.

**Comment by pq** [comment]
> DO type annotate public APIs

Aside: the linter is no longer meant to be consumed as a package, which is just to say that effectively there isn't really any public API...

> PREFER type annotating private declarations.

This is more compelling to me.  That said, I think it's a little prescriptive.  Does anyone puzzle about `main`?  Moreover, I don't see how the short versions of `visit__` methods could be confused as they're just callbacks.  But maybe this is confusing to others and to newcomers?

**Comment by a14n** [comment]
>Does anyone puzzle about `main`?

Perhaps we could special case this one in `always_declare_return_types` but in general it could catch code smell like :

```dart
bool something = true;

main() {
  if (something) {
    doSomething();
  } else {
    return computeResult(); // error if main has void return type
  }
}

int computeResult() {
  return 1;
}

void doSomething() {}
```

One can argument this code smell can be catch in code review but I really prefer the analyzer catch it automatically (even if the _small_ cost is to have an additional `void`). There are a lot of reason a review can fail to fix that (hard diff, asleep reviewer...)

>Moreover, I don't see how the short versions of `visit__` methods could be confused as they're just callbacks.

We (people used to the linter codebase) know that these `visit__` methods are callbacks BUT our best friend (the dart analyzer) don't and if we omit the return type we prevent it to catch errors. Enabling `always_declare_return_types` will add code but if it allows to catch bugs, improves code assist and lowers newcomers entrance's price I'm ready to pay.

**Comment by munificent** [comment]
>  I can't find those two rules in the current Effective Dart version and I really don't understand why they disappeared as they allowed to catch a lot of issues

Oops, that looks like an oversight on my part. I rewrote that entire section from scratch and it kind of got lost in the shuffle. *Technically* the new guidelines imply basically the same thing, but it's definitely not clear. Filed an issue: https://github.com/dart-lang/site-www/issues/996

**Comment by a14n** [comment]
What's the status here? Should we open a poll? ;)

**Comment by srawlins** [comment]
Close?

This has been enabled via [pedantic](https://github.com/dart-lang/pedantic/blob/master/lib/analysis_options.1.9.0.yaml).

**Comment by pq** [comment]
Thanks for following up!
