### ISSUE TITLE
provide a lint if a `@deprecated` annotation has no description of the deprecation

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#1073]
It's useful when deprecating functionality to indicate to the user what the recommended alternative is. So, instead of:

```dart
@deprecated
void foo() {
  ...
}
```

we should prefer:

```dart
@Deprecated('Prefer to use the bar() method')
void foo() {
  ...
}
```

/cc @kevmoo

**Comment by bwilkerson** [comment]
> It's useful when deprecating functionality to indicate to the user what the recommended alternative is. 

That's true, but that's not what the optional argument is used for:
```
  /**
   * Create a deprecation annotation which specifies the expiration of the
   * annotated feature.
   *
   * The [expires] argument should be readable by programmers, and should state
   * when an annotated feature is expected to be removed.
   * This can be specified, for example, as a date, as a release number, or
   * as relative to some other change (like "when bug 4418 is fixed").
   */
  const Deprecated(String expires) : this.expires = expires;
```

**Comment by devoncarew** [comment]
I've never seen in used for that purpose. We'd probably gather good info by surveying existing code, but generally, I don't think we should be limited by what that dartdoc says.

**Comment by pq** [comment]
It sounds like we should update the docs regardless?

**Comment by kevmoo** [comment]
We could always deprecate `@deprecate` 😄

**Comment by srawlins** [comment]
Okie doke, at some point, the description of the `Deprecated` constructor argument changed to [this](https://api.dartlang.org/stable/2.1.0/dart-core/Deprecated/Deprecated.html):

> Create a deprecation annotation which specifies the migration path and expiration of the annotated feature.
>
> The `message` argument should be readable by programmers, and should state an alternative feature (if available) as well as when an annotated feature is expected to be removed.

At this point, I think the original lint request is perfectly valid :)
