### ISSUE TITLE
Add prefer_double_quotes linter

### ISSUE THREAD

**Issue by kentcb** [dart-lang/linter#1096]
For those of us using languages with double-quotes (e.g. C#) on the back-end, and using Dart on the front-end, it's quite annoying to have to switch between two quote demarcations. There already exists a `prefer_single_quotes` linter, but there is no counterpart for double quotes. This is a request to add one, which should be fairly straightforward given the existence of the `prefer_single_quotes` linter.

**Comment by pq** [comment]
Thanks for chiming in @bgetsug!

If you're curious, there's a bit of a relevant conversation over on https://github.com/dart-lang/site-www/issues/859.

**Comment by janvladimirmostert** [comment]
Copy-paste prefer_single_quotes with some minor changes, unless someone's already busy with it, i'll give it a try?
https://github.com/dart-lang/linter/blob/master/lib/src/rules/prefer_single_quotes.dart

Using Kotlin and Java, so the single quotes are quite annoying, semantically they mean character on the JVM, so seeing strings in single quotes in Dart is weird.
