### ISSUE TITLE
avoid_types_on_closure_parameters should only apply for type repeating inferred type

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#1099]
```dart
dynamic x;
x = (String a) => a.length; // should be OK
```

**Comment by dotdoom** [comment]
One common use case is [`Stream#listen`](https://api.flutter.dev/flutter/dart-async/Stream/listen.html)'s `onError` callback with `StackTrace`:

```dart
  stream.listen(
      (event) => ...,
      onError: (dynamic e, StackTrace stackTrace) => ...
//                         ^^^^^^^^^^
//                         avoid_types_on_closure_parameters
```

**Comment by davidmorgan** [comment]
+1, along with https://github.com/dart-lang/linter/issues/2131 I think this would make it match `omit_local_variable_types`, which seems desirable.

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/f07e042eaf90c1f68e346068ba8e62f18946dc24
