### ISSUE TITLE
False positive for "Avoid using braces in interpolation when not needed" rules

### ISSUE THREAD

**Issue by donny-dont** [dart-lang/linter#112]
Linting fails for the following scenario when ${varname} is required.

    /var/cache/drone/src/github.com/dogma-dart/dogma-data/lib/build.dart 252:11 [lint] Avoid using  braces in interpolation when not needed.
      return '${basename}_convert.dart';
              ^^^^^^^^^^^
    /var/cache/drone/src/github.com/dogma-dart/dogma-data/lib/build.dart 258:24 [lint] Avoid using braces in interpolation when not needed.
      return 'unmodifiable_${basename}_view.dart';
                           ^^^^^^^^^^^

**Comment by pq** [comment]
Should be fixed in master.  Thanks for the catch!

**Comment by pq** [comment]
Fixed in [0.1.2](https://pub.dartlang.org/packages/linter).

**Comment by donny-dont** [comment]
:+1: thanks for getting this sorted!

**Comment by pq** [comment]
You're welcome! :)
