### ISSUE TITLE
Update appveyor to point to stable (post 1.12 release).

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#117]
As pointed out here: https://github.com/dart-lang/linter/pull/115 we should clean up our config once 1.12 is available via chocolatey.

**Comment by pq** [comment]
Chocolately is up to `1.16` at this point but I wonder if we shouldn't just stick to grabbing the latest release via `wget` and close this out.  @devoncarew ?  Curious what you think?

**Comment by devoncarew** [comment]
sgtm; that way we won't need to rev the CI script when there are new sdk versions
