### ISSUE TITLE
`prefer_mixin` should not warn about non-super-mixin classes

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/linter#1203]
Per https://github.com/dart-lang/language/issues/32 many non-super-mixins will have to remain as classes indefinitely. Because the warnings from `prefer_mixin` show up at mixin application sites, and not at mixin declaration sites, it is not practical for it to warn about them. Mixin declarations are rare. Flutter declares them and makes developers _apply_ them, but few other libraries and frameworks do. Therefore, the user who is applying the mixin rarely has the ability to change the mixin declaration.

Instead `prefer_mixin` should only warn about super-mixins, not regular mixins. Perhaps we should also use a different name for this lint. `prefer_mixin_supermixin`?

@leafpetersen @lrhn @eernstg @Hixie

**Comment by bwilkerson** [comment]
A separate lint might be a good choice. My concern is that it's a breaking change (in at least one sense) for a lint to start triggering for cases that it didn't used to trigger for. We could relax the lint now, but we're likely to want to restore it when we try to disallow mixing in classes.

**Comment by yjbanov** [comment]
@leafpetersen I was thinking it could be used as an option for our users (I already turned off `enableSuperMixins` for Flutter's own code), but if we want to switch everyone to the same option, I'd be OK with that too. We'd be making a decision on behalf of our users, but I don't imagine our users defining their own mixins much, let alone super-mixins. So I think the effect is quite small.

**Comment by leafpetersen** [comment]
> I was thinking it could be used as an option for our users (I already turned off `enableSuperMixins` for Flutter's own code)

It is definitely POR that enableSuperMixins will no longer be supported at all once Flutter has migrated.  Based on my scraping of pub packages, I don't expect much (or any) user breakage due to this.

**Comment by yjbanov** [comment]
SGTM!
