### ISSUE TITLE
Consider exempting a null literal from await_only_futures

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/linter#1211]
After the "sync async" change, several code bases started adopting `await null;` as a way to opt out of the new behavior (back to the original behavior). It would be nice if this rule recognized that convention by not generating a lint for that specific case. It's unlikely to be used for any other reason, so the change is unlikely to mask any real code issues.

**Comment by pq** [comment]
I think this is a great idea.

/cc @matanlurey @davidmorgan

**Comment by davidmorgan** [comment]
SGTM

**Comment by a14n** [comment]
In flutter there's some `await Future.delayed(Duration.zero)`. I guess this does the same thing as `await null`.

**Comment by bwilkerson** [comment]
As far as I know, yes. The only differences I can think of are that `await Future.delayed(Duration.zero)` allocates a short-lived object and that it has the type `Future` so the rule doesn't produce a lint.
