### ISSUE TITLE
ignoring prefer_is_not_empty doesn't work

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#1232]
I run into https://github.com/dart-lang/sdk/issues/34798 and tried to ignore it
but `// ignore: prefer_is_not_empty` didn't work

![image](https://user-images.githubusercontent.com/405837/47661995-68882700-db9a-11e8-84b8-b02264980c4f.png)

it turned out I could ignore it with `prefer_is_empty`, but that seems wrong to me.

![image](https://user-images.githubusercontent.com/405837/47661961-54dcc080-db9a-11e8-8a91-83d67a104ecd.png)

**Comment by pq** [comment]
Verified here too.

**Comment by srawlins** [comment]
Hmm, what to do about this one, the lint text seems pretty clear:

[prefer_is_empty](http://dart-lang.github.io/linter/lints/prefer_is_empty.html):

> DON'T use length to see if a collection is empty.
> ...
> Instead, there are faster and more readable getters: isEmpty and isNotEmpty. Use the one that doesn't require you to negate the result.

[prefer_is_not_empty](http://dart-lang.github.io/linter/lints/prefer_is_not_empty.html):

> PREFER x.isNotEmpty to !x.isEmpty for Iterable and Map instances.

I agree, it's not intuitive what each rule does. But the rule names are just short, unique identifiers. What to do.

**Comment by zoechi** [comment]
@srawlins 

> I agree, it's not intuitive what each rule does.

I don't see a problem here. 

The actual issue is that both `prefer_is_empty` and `prefer_is_not_empty` are silenced by the same ignore
```
// ignore: prefer_is_empty
```
while this should only apply to the former and the later should be silenced by
```
// ignore: prefer_is_not_empty 
```
but isn't.

To me this looks like a copy-paste error.

**Comment by pq** [comment]
> The actual issue is that both prefer_is_empty and prefer_is_not_empty are silenced by the same ignore

Looking again, I think they aren't actually but the messages **_are_** confusing.

In your case, you are seeing a flagging of `prefer_is_empty`, it's just that it covers both the `isEmpty` and `isNotEmpty` case for collections.

The `prefer_is_not_empty` lint flags things like `!sources.isEmpty`.

In the end, I think we could probably have picked better names?

Feel free to re-open if you think I missed something or you have ideas for how to make this actionable...
