### ISSUE TITLE
Add @listepo to AUTHORS

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1237]
Thanks for the contribution @listepo!

We'd like to add an attribution to our [AUTHORS](https://github.com/dart-lang/linter/blob/master/AUTHORS) file.  Could you give use your preferred name and mail?

Cheers!

**Comment by listepo** [comment]
@pq https://github.com/dart-lang/linter/pull/1239 done.

**Comment by pq** [comment]
Thank you!
