### ISSUE TITLE
flutter_test incompatible with linter

### ISSUE THREAD

**Issue by jelenacarnegie** [dart-lang/linter#1259]
Because every version of flutter_test from sdk depends on analyzer 0.33.0 and linter 0.1.72 depends on analyzer ^0.33.2, flutter_test from sdk is incompatible
with linter 0.1.72.
And because no versions of linter match >0.1.72 <0.2.0, flutter_test from sdk is incompatible with linter ^0.1.72.
So, because flutter_comment_wall depends on both linter ^0.1.72 and flutter_test any from sdk, version solving failed.                                          
pub get failed (1)

flutter doctor:
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel beta, v0.10.2, on Mac OS X 10.13.6 17G65, locale en-US)
[✓] Android toolchain - develop for Android devices (Android SDK 28.0.3)
[✓] iOS toolchain - develop for iOS devices (Xcode 10.0)
[✓] Android Studio (version 3.2)
[✓] Connected device (2 available)

pubspec.yaml
.....
environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  linter: ^0.1.72

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

**Comment by pq** [comment]
Hi!  Thanks for catching this.

It looks like https://github.com/flutter/flutter/pull/24146 (or thereabouts) bumped the linter version to `0.1.72` which is causing the problem.

@jonahwilliams: this is my mistake:  I published `0.1.72` not planning to integrate it into the Dart SDK until a new `analyzer` was available (and needless to say until cherry-pick season was over).  I didn't realize that "force upgrade" would pull it into flutter.

Is it easy to pin it back to `0.1.71`?  Alternatively, I can publish a new version that reverts the new dependency...

/cc @tvolkert

**Comment by jonahwilliams** [comment]
The latest master of flutter/flutter_test has no more dependency on analyzer, so upgrading in this case should fix the issue (See https://github.com/flutter/flutter/pull/24007/files)

**Comment by pq** [comment]
Fantastic.  I'll close this assuming @jelenacarnegie you can update to latest.

If not, please re-open!
