### ISSUE TITLE
[1.0.0] review experimental lints

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1277]
Pre-release (and really ASAP), we should review the lints currently tagged as experimental and assess:

- [x] `prefer_void_to_null` (#1287)
- [x] `avoid_positional_boolean_parameters` (#1288)
- [x] `prefer_foreach` (#1289)
- [x] `literal_only_boolean_expressions` (#1290)

What's keeping them experimental?

My sense is that where possible we should bump to stable or deprecate.

Thoughts?

/cc @alexeieleusis @MichaelRFairhurst @srawlins @a14n @bwilkerson

**Comment by bwilkerson** [comment]
I agree. I suspect that they simply fell off everyones plates. Perhaps in the future when we create an experimental rule we should open an issue to resolve the experiment so that we don't forget about them as easily.

**Comment by pq** [comment]
Sub-tasks opened for candidate lints.  On a quick scan `prefer_void_to_null` is the only one that may seem qualify as experimental but even that may just be marketing (assuming the underlying issues have been fixed).

**Comment by pq** [comment]
All promoted.  💎
