### ISSUE TITLE
unnecessary_parenthesis should allow wrapping a `!` argument

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1283]
E.g. the parens in `var z = !(const [7].contains(5));` are unnecessary, but I think they really enhance readability when the first two tokens to the right of `!` are separated by whitespace.

**Comment by srawlins** [comment]
CC @alexeieleusis and @a14n

**Comment by a14n** [comment]
:+1:

**Comment by srawlins** [comment]
I think the only other prefix operator is `-`, and I don't see why that should be different from `!`.

**Comment by srawlins** [comment]
(The fix for this, if we want to give all wrapped unary expressions a pass, would be a simple `if (parent is PrefixExpression) return;`)
