### ISSUE TITLE
Should mark invariant_booleans as experimental while bugs get fixed?

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1315]
There are [7 open bugs](https://github.com/dart-lang/linter/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+invariant_booleans+in%3Atitle) against invariant_booleans, including many false positive bugs. It is also the [slowest](https://github.com/dart-lang/linter/issues/674) in the benchmarks. Should we mark it experimental until these issues are resolved?

**Comment by bwilkerson** [comment]
That sounds reasonable to me.
