### ISSUE TITLE
// ignore: syntax violates Effective Dart guidelines.

### ISSUE THREAD

**Issue by ghost** [dart-lang/linter#1320]
Effective Dart states:

> DO format comments like sentences
>
> Capitalize the first word unless it’s a case-sensitive identifier. End it with a period (or “!” or “?”, I suppose). This is true for all comments: doc comments, inline stuff, even TODOs. Even if it’s a sentence fragment.

https://www.dartlang.org/guides/language/effective-dart/documentation#do-format-comments-like-sentences

This is in conflict with the linter's "ignore" comment syntax, which starts with a non-capitalized word and doesn't end in punctuation. It seems bad to encourage people to violate the style guide in order to ignore linter errors.

My suggestion would be to add an additional ignore syntax like `// Ignore: avoid_as.` or `// Ignore: avoid_as, with additional explanation here.`, and update documentation to reference this form. Alternatively, relax this Effective Dart guideline to "PREFER" or add a note to call out this exception.

**Comment by pq** [comment]
Interesting!  A counter argument might be that `ignore` is special, essentially acting like an annotation (and not really a comment) so, in a way, could be seen as an identifier in which case the rule isn't being violated.  But that's maybe a stretch?  In any event I don't feel super strongly.  (It occurs to me that if we wanted to call out the specialness of ignores, and we likely should, we could consider special highlighting in the IDE.) . Anyway...  I'm curious: @bwilkerson, @a14n: any opinions?

Thanks for kicking this off @patlillis!

**Comment by a14n** [comment]
I don't have a strong opinion on this. I tends to see `ignore` as a tag (and so not really a word) because you can also use `ignore_for_file`. `TODO` is a little similar but it already satisfies this uppercase rule :smile: .

**Comment by bwilkerson** [comment]
Actually, we would have made it an annotation if annotations could be associated with arbitrary pieces of code. Unfortunately, there are places where users need to be able to ignore a lint where an annotation can't be used. (We had a lengthy set of discussions when it was first introduced to try to find a better alternative than burying it in a comment, but failed to come up with anything.)

But I agree that it's essentially a compiler directive masquerading as a comment and hence shouldn't be thought of or treated like a comment.

**Comment by srawlins** [comment]
I think this is settled.
