### ISSUE TITLE
[docs] badge minimum supporting SDK

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1340]
Follow-up from https://github.com/dart-lang/linter/issues/1108#issuecomment-451235677, let's add an SDK badge w/ the number of the minimum supporting SDK.

**Comment by srawlins** [comment]
Oh man, +10, that's a great idea! This would be, like, a String on each lint rule? `introduced: "2.1.0"`?

**Comment by pq** [comment]
@srawlins: exactly.

Thinking a bit about how we'd do it, I suppose we could just grab `DEPS` and grep?

https://github.com/dart-lang/sdk/blob/2.1.0-dev.0.0/DEPS
https://github.com/dart-lang/sdk/blob/2.1.0-dev.1.0/DEPS

etc.

@kevmoo: is there an easy way to enumerate releases (besides querying github for tags...)

**Comment by pq** [comment]
FWIW, I'm working on this now.

Once we have this information, thoughts on where it can best be used?

For starters, I'll add a new field to generated linter docs w/ linter version and minimum SDK.  Anywhere else?

/cc @chalin @srawlins @kevmoo

**Comment by chalin** [comment]
> generated linter docs w/ linter version and minimum SDK

Sounds like a very good place to start.

(Is there still a wish to integrate the linter doc under dartlang.org? #949 cc @kwalrath)

**Comment by pq** [comment]
I'm not sure about dartlang.org integration but happy to discuss it.

In the meantime, I'm close to having things in place to add linter version and minimum SDK to the generated docs.  I'll let you know when there's something to look at.

**Comment by pq** [comment]
Related to Dart SDK, it would interesting to finish the thought by adding the including Flutter SDK as well. It'd be great to have a mapping of Flutter [release tags](https://github.com/flutter/flutter/tags) to version numbers for the Dart SDK they vend in.

Does anyone know if there's an easier way than starting w/ the revision in engine and following the thread from there?

https://github.com/flutter/engine/blob/714856123d5c0602dd798e13437f455074342a5c/DEPS#L34

Or have any other thoughts?

@Hixie @tvolkert @goderbauer : is this mapping maintained anywhere that I'm missing?
