### ISSUE TITLE
Lint rule request - deprecated_member_use_same_package

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1349]
As per https://github.com/dart-lang/sdk/issues/35556 and https://github.com/dart-lang/sdk/issues/30084, we are going to split the analyzer Hint, DEPRECATED_MEMBER_USE into a Hint and a Lint:

* Analyzer's DEPRECATED_MEMBER_USE will be altered to not report deprecated member use from within the package where the deprecated member is declared.
* Linter will get a new Lint, something like deprecated_member_use_same_package, which will report on deprecated member usage from the same package where the deprecated member was declared.

This maybe quite difficult to implement, it's a very meaty chunk of the BestPracticesVerifier in analyzer.

(The name could be `deprecated_member_use_same_package` or `same_package_deprecated_member_use`; the latter reads nicely, but I like that the former starts with the same string as the Hint, `deprecated_member_use`; I dunno what naming policies apply...)

**Comment by srawlins** [comment]
@bwilkerson after thinking about the implementation; I think that DEPRECATED_MEMBER_USE is complicated enough, and bug-prone enough (the implementation runs through so many visit methods in BestPracticesVisitor) that I think DEPRECATED_MEMBER_USE_FROM_SAME_PACKAGE should be a Hint now.

This would effectively not change the strictness of the analyzer; it would just break up the existing Hint into two, so that users can ignore the _FROM_SAME_PACKAGE variant via analysis options. WDYT?

**Comment by bwilkerson** [comment]
It would mean that I wouldn't have to add a lint to all of the packages I work on, so sgtm. :-)

More seriously, though, I think that's a reasonable approach to meeting the original request.
