### ISSUE TITLE
ReEnable 'unnessesary_getters' lint?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#1361]
https://github.com/dart-lang/linter/blob/9312fd198afb954e423d9792b67b2eb2447cfc3c/lib/src/rules.dart#L265-L266

https://github.com/dart-lang/linter/issues/35 has been fixed for a LONG time!

**Comment by pq** [comment]
Ah, sorry.  The bug reference is stale, you're right.  The actual blocker is: #23. I'll update the docs and we can track re-enabling the bug there.
