### ISSUE TITLE
Allow "Prefer using lowerCamelCase for constant names" to be excluded for certain constants

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#140]
For the "Prefer using lowerCamelCase for constant names" message, we actually do want the message, we just need to exclude it for a few constants where we've used the underlying platform's names unmodified (in our case, Android constants, but you can imagine this happening with Unix constants like EINVAL or whatever).

History: See https://github.com/dart-lang/sdk/issues/24452#issuecomment-148763475

**Comment by Hixie** [comment]
This is presumably resolved with `// ignore:`.

**Comment by Angeloem** [comment]
Ahaa, I successfully disabled them in the constant files. There is a way to do that I read
