### ISSUE TITLE
lints to promote spread collections

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1402]
Placeholder for conversations around lints to promote the use of **spread-collections** ([feature spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/feature-specification.md), [implementation plan](https://github.com/dart-lang/language/blob/master/accepted/future-releases/spread-collections/implementation-plan.md)).

@munificent: ideally I'd like to see lints discussed/tracked in the implementation plan.  Does that sound reasonable?  What's the process for updating it?  Should I add a discussion to the [tracking bug](https://github.com/dart-lang/language/issues/47)?

/cc @stereotype441 @bwilkerson

**Comment by munificent** [comment]
Feel free to just send a pull request with the changes to the implementation plan. I'd love to see the linter on there.

**Comment by bwilkerson** [comment]
FWIW, I have a couple of quick assists nearly ready. We should coordinate so that the lints flag the cases the assists can handle.

**Comment by pq** [comment]
Thanks @munificent.  https://github.com/dart-lang/language/pull/201 opened.

> FWIW, I have a couple of quick assists nearly ready. We should coordinate so that the lints flag the cases the assists can handle.

Fantastic!  Does analyzer `0.35.0` have enough support that we can start implementing or do we need to wait for another push?

**Comment by bwilkerson** [comment]
I'm not entirely certain. I know that it contains the AST changes to represent the new constructs (that's why it was a breaking change), but I think the parser was incomplete at that point. Resolution was, and still is, incomplete, but the assist is primarily syntactic in nature, and I'd guess that the lint would be too.

**Comment by pq** [comment]
After some conversations w/ @bwilkerson and @stereotype441, I'm leaning towards a process that mirrors how `analyzer` and other tools phase their implementations.  As a result, closing this in favor of: #1409  and #1410.
