### ISSUE TITLE
fix deprecated analyzer API references

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1405]
`lookupInheritance` and `lookupMember` are flagged as deprecated:

https://github.com/dart-lang/linter/blob/db09b38aa1bff0e9200bc0c77d8e785e6cf76122/lib/src/rules/annotate_overrides.dart#L83

https://github.com/dart-lang/linter/blob/db09b38aa1bff0e9200bc0c77d8e785e6cf76122/lib/src/rules/public_member_api_docs.dart#L169

The docs don't say what the preferred approach is.

Analysists: can you advise?

/cc @stereotype441 @bwilkerson @scheglov

**Comment by scheglov** [comment]
Use `InheritanceManager2.getInherited(InterfaceType type, Name name)` for `lookupInheritance `.

Use `InheritanceManager2.getMember(...)` for `lookupMember`.

**Comment by bwilkerson** [comment]
We should document that in analyzer.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/91840

**Comment by pq** [comment]
Thank you!
