### ISSUE TITLE
DO specify type annotations.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#144]
As per #142.

**Comment by pq** [comment]
From the [flutter style guide](https://github.com/flutter/engine/blob/master/sky/specs/style-guide.md):

**DO** avoid `var` when specifying that a type is unknown.

Use `dynamic` if you are being explicit that the type is unknown. Use `Object` if you are being explicit that you want an object that implements `==` and `hashCode`.

**Comment by pq** [comment]
A real world example would be better.

@Hixie?

Also: feel free to update the descriptive text as you see fit.

Thanks!

**Comment by Hixie** [comment]
Specifically this is for projects that want to use types everywhere, to aid in debugging. When you're writing a simple app or library, it's nowhere near as much of a big deal. It's a big deal when you're doing a multi-thousand-line framework that you're hoping millions will use.

**Comment by pq** [comment]
Cool.  Thanks.

I'm guessing that these are no-no's too?

```
final foo = '';
const foo = '';
```

Might make sense to break out to another rule either way.

**Comment by Hixie** [comment]
Yeah, anything where you're lacking the type. Those two are actually even more important than "var", because they're insidious -- you don't notice the problem:
```dart
   int foo = 10;
   final bar = new Bar();
   String baz = 'hello';
   const quux = 20;
```
They all seem to have types. Two of them don't.

**Comment by pq** [comment]
Ha!

Thinking about a rename to capture the full spirit.  How about something like:

**DO** specify type annotations.

Avoid `var` when specifying that a type is unknown and short-hands that elide type annotations.  Use `dynamic` if you are being explicit that the type is unknown. Use `Object` if you are being explicit that you want an object that implements `==` and `hashCode`.

**GOOD:**
```dart
   int foo = 10;
   final Bar bar = new Bar();
   String baz = 'hello';
   const int quux = 20;
```

**BAD:**
```dart
   var foo = 10;
   final bar = new Bar();
   const quux = 20;
```

**Comment by Hixie** [comment]
Sounds great.

**Comment by Hixie** [comment]
I may steal that wording for our style guide. :-)

**Comment by pq** [comment]
First cut implemented in https://github.com/dart-lang/linter/commit/12642e75c637dbedb73cb5c0e37f4a4b537166c7.

**Comment by pq** [comment]
Some refinements in flight: https://codereview.chromium.org/1427223002/.

@Hixie : what about specifying return types for methods and functions?  I'm inclined to break that into a separate lint either way I think but I'm curious if that's part of the Flutter style.

**Comment by Hixie** [comment]
Yup, we recommend typing everything. That includes arguments, return values, specialising generics like List (whether in constructors or literals), specialising generic typedefs when relevant, etc. (We catch an inordinate number of mistakes before checkin by encouraging this practice and then analysing all code.)

**Comment by pq** [comment]
Thanks.  I figured!  I added another lint for that: https://github.com/dart-lang/linter/issues/146.

How are you on declaring exception types in catch clauses?

```dart
try {

} catch (e) {
  ...
}
```

vs.

```dart
try {

} on Exception catch (e) {
  ...
} on String catch (s) {
  ...
}

```

**Comment by Hixie** [comment]
Depends. The vast majority of the time all we do with exceptions is print them, so we tend to do:
```dart
try {
   // ...
} catch (e, stack) {
   print("Caught exception while doing foobar: $e\n$stack");
}
```
We do occasionally have catches for specific types, in which case we do the `on Foo` style. Looks like we sometimes do `} on Foo catch (e) {` and sometimes do just `} on Foo {`.

HTH.

**Comment by pq** [comment]
It does.  Thanks!

**Comment by pq** [comment]
Implemented w/ c5be49983a56596f1a78bce8aac13c43b4f5a719.  Landed in [0.1.4](https://github.com/dart-lang/linter/releases/tag/0.1.4).

**Comment by sethladd** [comment]
Thanks!

**Comment by pq** [comment]
:+1:

**Comment by pq** [comment]
Actually, it occurs to me that as it's implemented, we don't special case `_`, `__`, `___` identifiers.

https://github.com/dart-lang/linter/issues/147 to track the refinement.

**Comment by enloc-port** [comment]
So what is the issue here then? Why is it giving me "Specify type annotations"?

```dart
class FooClass<T> {}

typedef FooType = FooClass<String>;

class Bar {
  FooType get foo => FooClass<String>();
}
```
