### ISSUE TITLE
the linter package should export a linter version

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#1440]
This would be incremented whenever a linter rule changes such that a line would generate different lints than before; or alternatively, incremented whenever a new version of the linter was ready to be rolled into the analyzer. The analysis driver would use this version in the summary cache signature.

cc @scheglov @pq

**Comment by scheglov** [comment]
Sounds good to me, let me know when linter will have this data, so that I could update the code that computes signatures.

**Comment by pq** [comment]
https://dart-review.googlesource.com/c/sdk/+/93882

Once this (or something similar) lands, we'll need to publish a new analyzer and set this value from the linter but you should be able to start on the signature logic now (just discarding null version info).

**Comment by pq** [comment]
> Once this (or something similar) lands, we'll need to publish a new analyzer

@stereotype441: any other need for an analyzer roll or is one planned any time soon?

**Comment by bwilkerson** [comment]
I have a CL nearly ready to send out that includes some changes that we want in a breaking change version. It's not terrible if we publish twice, but just FYI.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/93844

**Comment by pq** [comment]
Just getting back to closing the loop on this.  All done. 👍
