### ISSUE TITLE
Lint rule for unsafe API usage, such as ScriptElement.src=

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1495]
There is internal desire to report on usage of unsafe APIs. One example is setting the src on a ScriptElement ([ScriptElement.src=](https://api.dartlang.org/dev/2.2.1-dev.2.0/dart-html/ScriptElement/src.html)).

The lint rule would therefore report on the following setter calls: `ScriptElement.src=` and `dynamic.src=`.

There is of course a lot of room for false positives there, so this rule is only recommended for _web_ packages.

**Comment by srawlins** [comment]
CC @vsmenon @sigmundch @davidmorgan @matanlurey

**Comment by matanlurey** [comment]
As I mentioned internally, I'm worried `<dynamic>.src=` is potentially too invasive, so that might want to be a separate lint rule.

**Comment by bwilkerson** [comment]
I have similar concerns. It might be worthwhile to write a script that we can run to measure the number of false positives in internal code.

**Comment by vsmenon** [comment]
Do we have any data on how often it comes up in existing code?  It's really easy to fix on new code - add the type.

**Comment by matanlurey** [comment]
I mean, ideally we would ban all dynamic invocation, but that's another topic.

**Comment by srawlins** [comment]
I'll write the rule for `dynamic.src=` and check internally, and post back. But if I were the owner of a package, and someone wanted to enable the `ScriptElement.src=` check, but _not_ the `dynamic.src=` check, you'd have to work _really_ (_really_) hard to justify that. Why can you not just make those dynamic calls non-dynamic? Does the package have so many `dynamic.src=` calls which are truly dynamic that it is onerous to write `// ignore_for_file:` comments?

@matanlurey I'll ask the language team if we can ban dynamic invocation first. That'd save me like 30, 40 lines of code here. 😉

**Comment by srawlins** [comment]
Internally, there are literally 0 instances of `dynamic.src=`. You could argue that it is therefore not important to guard against `dynamic.src=`, but I stand by my reasoning above; it would be very strange to (a) opt-in to this lint rule as a web package, (b) have a `dynamic.src=`, and (c) not be able to properly type that `dynamic`, which is the only false-positive situation that would require  an `// ignore:`. I cannot think of any situations or examples of apps that would want to opt-in to `unsafe_script_src` but would _not_ opt-in to `unsafe_dynamic_src`.
