### ISSUE TITLE
type_annotate_public_apis also should ignore `_`, `__`, ...

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#153]
> [lint]
  pub global run linter --stats -ctool/lintcfg.yaml lib test tool
  /home/myuser/dart/bwu_bind_html/lib/bwu_bind_html.dart 28:19 [lint] Type annotate public APIs.
    void updateHtml(_, [__]) {

like for #147 (#144)

**Comment by pq** [comment]
https://codereview.chromium.org/1641803002/

**Comment by pq** [comment]
Fixed w/ 733c6db127bcc90e78964b4a6bc3b6819fe08f3a.
