### ISSUE TITLE
False positive for unnecessary_parenthesis

### ISSUE THREAD

**Issue by modulovalue** [dart-lang/linter#1533]
**Describe the issue**
A false positive for unnecessary_parenthesis

**To Reproduce**

`(String).toString();`
`(AnyType).toString();`

With parentheses the toString() converts the Type to a String and does not call toString() on the type which is the case if the parentheses were to be removed.

**Comment by srawlins** [comment]
Great catch! While [Type has a toString() method](https://api.dartlang.org/stable/2.2.0/dart-core/Type-class.html), syntactically, `String.toString()` tries to call a static method named `toString()`.
