### ISSUE TITLE
false positive in `unnecessary_this` when used to avoid shadowing

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1546]
![image](https://user-images.githubusercontent.com/67586/57092905-5d38c400-6cc1-11e9-84cd-06d182cd882c.png)

**Comment by bwilkerson** [comment]
I don't believe that that's a false positive. The specification states:

> An initializer of the form `v = e` is equivalent to an initializer of the form `this.v = e` ...

Which means that the identifier on the left is always resolved in a scope that does not include the parameters.

**Comment by pq** [comment]
Was just going to update this bug since I came to the same conclusion.

Thanks for confirming!
