### ISSUE TITLE
curly_braces_in_flow_control_structures isn't catching all cases

### ISSUE THREAD

**Issue by DanTup** [dart-lang/linter#1548]
In the following code, only the last block complains with `curly_braces_in_flow_control_structures`:

<img width="638" alt="Screenshot 2019-05-06 at 5 20 57 pm" src="https://user-images.githubusercontent.com/1078012/57239270-54c6ed00-7023-11e9-8ff6-9f07f8b647a2.png">

Code is here:

https://github.com/flutter/devtools/blob/9bcab46e323c867664e90ee4954ff57ae507a44b/packages/devtools/lib/src/ui/analytics.dart#L280

Even if I fix the last one, it doesn't warn on the other cases:

<img width="578" alt="Screenshot 2019-05-06 at 5 21 44 pm" src="https://user-images.githubusercontent.com/1078012/57239314-70ca8e80-7023-11e9-9def-81d0ce773358.png">

**Comment by DanTup** [comment]
Also doesn't seem to complain on this. Now I'm wondering if I'm misunderstanding it? @pq 

<img width="605" alt="Screenshot 2019-05-06 at 5 22 43 pm" src="https://user-images.githubusercontent.com/1078012/57239381-a4a5b400-7023-11e9-92cb-df61941faeb8.png">

**Comment by pq** [comment]
There appears to be an exception for short lines.  (I believe this was designed to promote Flutter style IIRC?)

@a14n: should have some insights?

**Comment by bwilkerson** [comment]
The documentation states:

> There is one exception to this: an `if` statement with no `else` clause where the entire `if` statement and the then body all fit in one line.

It fails to mention the other exception, which, based on looking at the code, appears to be very intentional.

**Comment by DanTup** [comment]
> There is one exception to this: an if statement with no else clause where the entire if statement and the then body all fit in one line.

Aha, I should've read the docs - that explains the last one I think!

> It fails to mention the other exception, which, based on looking at the code, appears to be very intentional.

I'm not sure I understand what it is (or why it's intentional)?

**Comment by bwilkerson** [comment]
Sorry, should have been more explicit. The code currently produces a diagnostic if

- there is no else clause, the statement doesn't all fit on a single line and the then statement is not a block, or

- there is an else clause whose statement is not an if statement and if either the then or else statements is not a block.

I don't know what the motivation is for not checking the then statement when the else statement is an if statement. It's possible that it was unintentional and a bug.

**Comment by a14n** [comment]
IMHO it's just a bug. Fix coming.
