### ISSUE TITLE
Can we have quick fixes for linter hints?

### ISSUE THREAD

**Issue by kasperpeulen** [dart-lang/linter#158]
It seems like almost any linter rule could provide a quick fix.

![image](https://cloud.githubusercontent.com/assets/1035299/11445870/930314b2-9530-11e5-8b9a-7bb79e3abc01.png)

Would be awesome if I could quickly fix linter issues in that way :)

**Comment by sethladd** [comment]
+10000 :)

**Comment by pq** [comment]
:+1: 

First one landed in server proper as of https://github.com/dart-lang/sdk/commit/549a7a4d00c73a918439cdcb3601001e1955a581.  More to come!

**Comment by pq** [comment]
Support is there, some are implemented and more on the way!
