### ISSUE TITLE
Lint request: avoid dynamic dispatch

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1591]
Dynamic dispatch has several costs: it can be expensive, and can prevent tree-shaking.

The lint rule would report any methods being called  on dynamic (other than methods on Object?).

Examples:

```dart
var a;
a.length;

getLength(a) {
   print(a.length);
}
```

**Comment by srawlins** [comment]
CC @vsmenon @matanlurey

**Comment by matanlurey** [comment]
10/10 would adopt.

**Comment by srawlins** [comment]
Oops originally requested by @matanlurey at https://github.com/dart-lang/sdk/issues/33121. Lots of nummy discussion there. But I think this issue does belong here.

**Comment by srawlins** [comment]
Replacing with https://github.com/dart-lang/linter/issues/1782
