### ISSUE TITLE
unsafe_html needs better documentation

### ISSUE THREAD

**Issue by mnordine** [dart-lang/linter#1604]
Check out the page for `unsafe_html`: 
https://dart-lang.github.io/linter/lints/unsafe_html.html

It tells me to avoid assigning directly to `src` field. Why? What is the fix? Is it unsafe on any element that has the `src` field? Or just some?

**Comment by srawlins** [comment]
Apologies for the short description. To answer your questions here, before they make it to documentation:

* It is unsafe if you may be setting `src=` to untrusted, unescaped user input.
* There is no fix yet. We're planning one, but wanted to start linting early.
* I think it is unsafe on any setter of any element that directs the browser to make a network request.

**Comment by mnordine** [comment]
Thx @srawlins, I assumed it was to mainly check for adding untrusted scripts.

**Comment by pq** [comment]
Duplicate of #2348
