### ISSUE TITLE
Can't use `prefer_double_quotes` with dartanalyzer 2.3.2

### ISSUE THREAD

**Issue by passsy** [dart-lang/linter#1607]
When I add `prefer_double_quotes` to my project (dart sdk 2.3.2) I get the warning `'prefer_double_quotes' is not a recognized lint rule`.
Running `dartanalyzer` (version 2.3.2) also doesn't seem to support the new rule.

What do I have to update, so that `dartanalyzer` is using the latest `linter` version?

[`analyzer`](https://pub.dev/packages/analyzer) hasn't been updated since the new [`prefer_double_quotes` was added](https://github.com/dart-lang/linter/pull/1547). Is that the missing part?

**Comment by bwilkerson** [comment]
That would certainly explain it, yes. The lint rules are not dynamically loaded, they are statically compiled into the analyzer and analysis server snapshots, so changes to the linter package do not reach users until (a) the latest linter package has been vended into the SDK and (b) a new version of the SDK has been released.

**Comment by Stargator** [comment]
@bwilkerson 2.3.3 looks to be released on [6/24/2019](https://github.com/dart-lang/sdk/pull/37239/files). But no mention of prefer_double_quotes, do you know if that is an oversight or if the lint will be released after 2.3.3?

**Comment by bwilkerson** [comment]
No, I don't know. But I just saw https://github.com/dart-lang/linter/issues/1609, which might suggest that there is an issue with the rule that is preventing it from being recognized.

**Comment by pq** [comment]
Sorry for the confusion.  That lint was introduced to the SDK in  `2.3.2-dev.0.0`.   It looks like the changelog for `2.3.3` wasn't correctly updated though it should be available there.

cc @aadilmaan (fyi and a placeholder for a conversation about managing the changelist)
