### ISSUE TITLE
awkward blank `>=` in unreleased Dart SDK field in website.

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1609]
The linter website has some blanks for SDK, e.g.  http://dart-lang.github.io/linter/lints/prefer_double_quotes.html

"Dart SDK: >= • (Linter v0.1.88)"

I think this should be updated to say something like "Dart  SDK: (unknown)".

**Comment by pq** [comment]
d'oh!

The text we're generating looks like this:

```html
 <p style="padding-bottom: 10px;">Dart SDK: >= <unreleased> • <small>(Linter v0.1.88)</small></p>
```

For it to be legitimate HTML as it stands, we'd to change format or do some escaping...

I'll have a fix shortly.

Thanks for the catch!
