### ISSUE TITLE
 unhandled exception in avoid_implementing_value_types

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1647]
When testing a new dartfix for null closures, I hit this:

```
[~/src/repos/dart/sdk/pkg/dartfix] (master) $ dart bin/dartfix.dart --include=null-closures ../../../../linter
Calculating fixes...           |Unhandled exception:
ERR: file:///Users/pquitslund/src/repos/dart/sdk/third_party/pkg/linter/lib/src/rules/avoid_implementing_value_types.dart:126:13: Error: The getter 'type' isn't defined for the class 'Element'.
```

This is the triggering code:

```dart
  static bool _overridesEquals(ClassElement element) =>
      // ignore: unnecessary_cast
      (element.lookUpConcreteMethod('==', element.library)?.enclosingElement
              as ClassElement)
          ?.type
          ?.isObject ==
      false;
```

EDIT: @bwilkerson initially I thought it was related to #1644, but not sure now.  (Sorry if you saw the early description!)

**Comment by bwilkerson** [comment]
That's a reasonable hypothesis, but probably true. In the changed code the getter `type` is being invoked on an expression of type `ClassElement`. However, the error indicates that it isn't defined for `Element`. That's the error that promoted the fix. My guess is that we are somehow compiling against an older version of 'linter'.

**Comment by pq** [comment]
Sorry, yes.  I was running a stale SDK.  After re-building all is good again.  Thanks!
