### ISSUE TITLE
Update lines_longer_than_80_chars to match new Effective Dart guidance

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/linter#1659]
Effective Dart just added:

```
**Exception:** Multi-line strings can contain lines longer than 80 characters
because newlines are significant inside the string and splitting the lines into
shorter ones can alter the program.
```

Most likely we want the lint to match this?

**Comment by a14n** [comment]
Actually this is already supported by the lint ;)

https://github.com/dart-lang/linter/blob/b98f6be8fe33bb0c8f0d822926a1768839c4ba43/test/rules/lines_longer_than_80_chars.dart#L24-L26

@munificent updated the style guide after a report I made in dart-lang/site-www#967

**Comment by pq** [comment]
Aha!  I totally forgot about that. 😊

Thanks again!

**Comment by davidmorgan** [comment]
Neat! Thanks for checking :)
