### ISSUE TITLE
flutter_style_todos should accept "TODO(url): message"

### ISSUE THREAD

**Issue by jamesderlin** [dart-lang/linter#1670]
Currently the `flutter_style_todos` lint requires a format of:

`TODO(username): message, url`

and attempting to use:

`TODO(url): message`

fails:

>   info • Use Flutter TODO format: // TODO(username): message,
>         https://URL-to-issue •
>         ... •
>         flutter_style_todos

IMO we should not require a username and allow `TODO(url)`:

* Usernames can become stale.
* Usernames can be ambiguous. (Username on what system?)
* Usernames can misleadingly imply that the specified user claims responsibility for fixing the issue.

**Comment by srawlins** [comment]
I believe this lint is written for the Flutter team. Based on their Style guide:

https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#avoid-checking-in-comments-that-ask-questions

The lint should not deviate from that guide. AFAICT, the only wiggle room is in the URL bit:

> Including an issue link in TODOs is highly encouraged.

I suspect we will keep the lint enforcing that which is "highly encouraged."

**Comment by jamesderlin** [comment]
Heh, that wiki page was *just* updated after I started a discussion about this in chat.

The current consensus now seems to be:

* Drop the username requirement.
* Require the GitHub issue link.

Formatted as:

`TODO: message, url`

@hixie thinks it should be done as a separate lint to make transitioning easier, though.

**Comment by jamesderlin** [comment]
Also see https://github.com/flutter/flutter/issues/37519.

**Comment by Hixie** [comment]
> @Hixie thinks it should be done as a separate lint to make transitioning easier, though.

Also so we don't break people who use the existing style and benefit from the current lint.

**Comment by srawlins** [comment]
It sounds like we need a new lint rule then. I will leave it to the flutter team to request a new rule and specify it.
