### ISSUE TITLE
avoid_slow_async_io not reported for Directory.exists

### ISSUE THREAD

**Issue by kinex** [dart-lang/linter#1671]
If `File.exists()` is slow, I would bet there is same problem with `Directory.exists()`. Same for `Directory.stat()` . Or is it really preferable to use async methods with `Directory` and sync methods with `File`?

**Comment by pq** [comment]
@danrubel: I believe you've spent some time on this one...  Thoughts?

**Comment by danrubel** [comment]
My current understanding is that the all of the dart.io sync methods are faster than the corresponding async methods... but my information may be out of date. It would be great to have someone closer to that code weigh in here.

**Comment by pq** [comment]
Maybe @sortie has thoughts?
