### ISSUE TITLE
New rule for using a leading underscore for identifiers that aren't private

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1676]
As per [Effective Dart](https://dart.dev/guides/language/effective-dart/style#dont-use-a-leading-underscore-for-identifiers-that-arent-private):

> There is no concept of “private” for local variables, parameters, or library prefixes. When one of those has a name that starts with an underscore, it sends a confusing signal to the reader. To avoid that, don’t use leading underscores in those names.

```dart
// BAD

void fn(String _s) {
  int _n = _s.length;
}
```

**Comment by matthewkooshad** [comment]
this is nice. and, is there a lint rule for privates to have underscore prefix? i didn't locate it after searching for a while.

**Comment by bwilkerson** [comment]
> is there a lint rule for privates to have underscore prefix?

I'm not sure what you mean by that. All identifier are public unless they start with an underscore, so I don't know how you'd have a private that didn't start with an underscore.

**Comment by matthewkooshad** [comment]
i've been trying to use private functions to have leading underscore. but, sometimes, i forget it.
is there a way for the linter to know whether a variable or function can be labeled as private, if it's currently not labeled as private?

**Comment by bwilkerson** [comment]
Unfortunately, no, the underscore is the only indication that a declaration is private.

**Comment by jamesderlin** [comment]
FWIW, I find it useful to name local variables with a leading underscore when I'm intentionally shadowing a private member variable with a local one:
```dart
class Foo {
  int? _x;

  Foo(this._x);

  void f() {
    final _x = this._x;
    if (_x != null) {
      print(_x + 1);
    }
  }
}
```
