### ISSUE TITLE
Linter Extension-Method Experiment Support

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1683]
Tracking issue for `extension-method` support.

**Lints to vet/update.**

- [x] `always_declare_return_types`
- [ ] `always_specify_types` (#1706)
- [x] ~`annotate_overrides`~
- [x] `avoid_positional_boolean_parameters`
- [x] `avoid_renaming_method_parameters`
- [x] `avoid_returning_this` (assumes method parents are classes or mixins)
- [x] ~`avoid_setters_without_getters`~
- [x] `public_member_api_docs`
- [x] `prefer_constructors_over_static_methods` (assumes method parents are classes or mixins)
- [x] `slash_for_doc_comments`
- [x] `type_annotate_public_apis`
- [x] `use_setters_to_change_properties`
- [x] ~`void_checks`~
...

**New lints.**

- [ ] `camel_case_extensions`
  - [ ] style guide update: https://github.com/dart-lang/site-www/pull/1846
  - [x] lint experiment: #1685

**Comment by pq** [comment]
After some more thinking, I'm less sure about whether `avoid_setters_without_getters` should lint extensions.

@bwilkerson: thoughts?

**Comment by bwilkerson** [comment]
I would recommend that it not lint extensions unless we get a request for it from users.

**Comment by pq** [comment]
Closing this in favor of targeted issues moving forward
