### ISSUE TITLE
Lint for UpperCamelCase classes intended as metadata annotations (Style Guide).

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#17]
**DO** use UpperCamelCase names for classes intended to be used in metadata annotations.

If the annotation takes no parameters, you might want to create a lowerCamelCase constant for it.

**GOOD:**

```
@Foo(anArg)
class A { ... }

@Foo()
class B { ... }

@foo
class C { ... }
```

**Comment by dikmax** [comment]
I think this issue is covered by 'constant_identifier_names' and 'camel_case_types' rules.

**Comment by pq** [comment]
@dikmax is spot on.
