### ISSUE TITLE
new lint: `avoid_overriding_widget_equals`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#1783]
Follow-up from https://github.com/flutter/flutter/pull/41220#discussion_r332737769 (and https://github.com/flutter/flutter/issues/1220).

Intent: disallow overriding `==` and `hashCode` in `Widget` subclasses.

Discussion: consider a general solution such as a `@final` annotation (or extending `@sealed` in `package:meta`).

/cc @bwilkerson @Hixie

**Comment by pq** [comment]
The more I think about this, the more inclined I am to tackle the case generally w/ an annotation in meta (https://github.com/dart-lang/sdk/issues/34378) and general purpose enforcement in `analyzer`.  Would love to hear other folk's thoughts...

**Comment by Hixie** [comment]
I definitely prefer general lints that are triggered by annotations (a la `@immutable`) than Flutter-specific things.

**Comment by pq** [comment]
We went ahead and took a general approach and implemented `@nonVirtual` in [package:meta](https://pub.dev/packages/meta):

![image](https://user-images.githubusercontent.com/67586/67877067-27508d00-faf6-11e9-98b9-15b5b19fc8e4.png)

To take advantage `Widget` should get annotated.  (And possibly elsewhere too.)
