### ISSUE TITLE
Flag assignments to itself

### ISSUE THREAD

**Issue by filiph** [dart-lang/linter#182]
Seems to be a frequent bug in larger (copy-paste) codebases.

``` dart
_someLongVariableName.x = otherLongVariableName.x;
_someLongVariableName.y = otherLongVariableName.y;
_someLongVariableName.z = _someLongVariableName.z;
```

**Comment by parlough** [comment]
Fixed with the [`no_self_assignments`](https://dart.dev/lints/no_self_assignments) lint in Dart 3.1.0.

If anyone would like to see further changes or enhancements to the lint, please open a new issue. Thanks! =D
