### ISSUE TITLE
unnecessary_parenthesis shouldn't apply on `(a - b) as A`

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#1843]
The following code triggers a lint `unnecessary_parenthesis`

```dart
final Offset delta = (b - a) as Offset;
```

without parenthesis it's not obvious the cast applies on `b - a` instead of `a`

**Comment by bwilkerson** [comment]
I agree.

The question, though, is whether the rule is suppose to catch
- places where the use of parentheses doesn't change the semantics of the code (and hence are unnecessary in a strict sense), or
- places where they are both unnecessary in a strict sense _and_ don't improve readability.

The first is uncontroversial; the grammar defines unnecessary. The second is subject to personal preference. I don't know whether the rule is already following the second option, but I am concerned about adding special cases. If we're considering adding a special case, then I think we should at least actively request community feedback.

@davidmorgan Interested in your thoughts.

**Comment by a14n** [comment]
AFAICT there are already several exceptions. See the [rule history](https://github.com/dart-lang/linter/commits/master/lib/src/rules/unnecessary_parenthesis.dart).

**Comment by srawlins** [comment]
> The question, though, is whether the rule is suppose to catch

> * places where the use of parentheses doesn't change the semantics of the code (and hence are unnecessary in a strict sense), or
> * places where they are both unnecessary in a strict sense and don't improve readability.

It's the latter.

**Comment by davidmorgan** [comment]
Armed with a (google internal only, sorry) list of pre-existing violations of the lint as it stands today

https://docs.google.com/spreadsheets/d/1hA38kTTAzHANsISIxjYO2fCsr6Sg6JXjSQb185u0-P8/view#gid=1710344775

I think we should probably strip this lint down to a small, easily explained list of common cases of unnecessary parentheses.

**Comment by sigurdm** [comment]
Here is a similar example we hit:
```
main() {
  ((b) => b.a) as dynamic Function(dynamic);
}
```
Without the parenthesis b.a would be casted, not the function expresssion.
