### ISSUE TITLE
Advertise integration w/ Coala.

### ISSUE THREAD

**Issue by Adrianzatreanu** [dart-lang/linter#190]
Hello, we're coala - http://coala-analyzer.org/ and your linter can now be used in all our supported editors and stuff, maybe working together could be fruitful! 

See https://github.com/coala-analyzer/coala-bears/issues/105 & https://github.com/coala-analyzer/coala-bears/commit/93b3d8f09594ee09c8c46381724a85f53fd53bdb for more info

CC @sils1297

**Comment by Adrianzatreanu** [comment]
If you are interested in working with us, you can always find us on https://gitter.im/coala-analyzer/coala or #coala on freenode or https://telegram.me/joinchat/AuL-lwKZ8JLFZiI6SbtQVw on telegram.

We are looking forward for your messages :)

**Comment by adtac** [comment]
Hey @pq 

`coala` is a tool that unifies all linters under one interface - this means that you can support multiple editors trivially, get various performance improvements done under-the-hood, various output formats (JSON, CLI, ...) and much much more.

We integrated this linter as [DartLintBear](https://github.com/coala/bear-docs/blob/master/docs/DartLintBear.rst). You can easily test it out by [installing coala](http://docs.coala.io/en/latest/Users/Install.html) (it's just a simple `pip3 install coala-bears`) and running `coala --bears=DartLintBear --files=src/\*.dart` - that's it!

**Comment by pq** [comment]
Hi @adtac .  Is coala hooked up to the Dart `analyzer` shipped w/ the SDK?  The linter front-end CLI in this package is likely to go away in favor of calling out to the analyzer proper.  (See: https://github.com/dart-lang/linter/issues/389).

Thanks for doing this!

**Comment by adtac** [comment]
@pq do you mean the `dartanalyzer` binary? If so, yes, it's the one that's shipped with the binary (see [here](https://github.com/coala/coala-bears/blob/master/bears/dart/DartLintBear.py#L13)). We're not using the `linter` executable (that is getting deprecated).

**Comment by pq** [comment]
Ah, cool.  Thanks!

@adtac: How are folks generally advertising their coala support?

**Comment by sils** [comment]
Usually they have a section about integrations that also includes editor plugins (via or not via coala)

**Comment by adtac** [comment]
It looks like you have a few badges at the top of your README, so we made one just for you :)

[![coala support](https://img.shields.io/badge/coala%20support-yes-green.svg)](https://coala.io)

Code:

    [![coala support](https://img.shields.io/badge/coala%20support-yes-green.svg)](https://coala.io)

**Comment by pq** [comment]
Awesome.  Thanks!

@sils, @adtac : who would you rate as your most visible integrators?

**Comment by adtac** [comment]
@pq we have about 107 bears (linter wrappers) supporting about 64 languages right now. Some of my personal favorites are [YapfBear](https://github.com/coala/bear-docs/blob/master/docs/YapfBear.rst) for [google/yapf](https://github.com/google/yapf), [CPDBear](https://github.com/coala/bear-docs/blob/master/docs/CPDBear.rst) for [cpd](https://pmd.github.io/pmd-5.4.1/usage/cpd-usage.html), [GNUIndentBear](https://github.com/coala/bear-docs/blob/master/docs/GNUIndentBear.rst) for [GNU Indent](https://www.gnu.org/software/indent/), [PEP8Bear](https://github.com/coala/bear-docs/blob/master/docs/PEP8Bear.rst) which makes things PEP8 conformant, and [much more](https://github.com/coala/bear-docs) :)

**Comment by pq** [comment]
![image](https://user-images.githubusercontent.com/67586/41389447-c702a696-6f45-11e8-87ba-d61010e474fd.png)

It looks like this is no longer a thing.  Feel free to re-open.
