### ISSUE TITLE
Any thought to creating a JSON output format compatible with Sonarqube

### ISSUE THREAD

**Issue by smclinden** [dart-lang/linter#1941]
**Describe the issue**
JSON output format (enhancement)

**Comment by pq** [comment]
@smclinden do you mean for the `linter` tool?  FWIW `bin/linter` was never meant to be long-lived and is primarily for development.  For the best results I'd suggest using the `dartanalyzer` command-line tool. Note that while `dartanalyzer`  does have a machine output, I'm guessing you'd have to translate it to something Sonarqube is expecting...

As another approach, especially if you want to further customize behavior, you might consider writing a custom "survey" using the _surveyor_ tool:

https://github.com/pq/surveyor#surveying-lint-rule-violations

The linked example shows how you could use it to lint. It should be fairly straightforward to add JSON formatting to the output as well.  (Let me know if you have any questions.)


---

RE: machine output in general, fyi @jwren who is looking at a unified story for all the Dart CLIs.

**Comment by smclinden** [comment]
Thanks! It looks like a great place to start.

**Comment by pq** [comment]
Feel free to reach out if you have any questions.  And let us know whet you end up doing!
