### ISSUE TITLE
unnecessary_this false positives

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/linter#1970]
There are new unnecessary_this false positives in the latest version.

I was not able to figure out a repro :) more info on the internal bug.

**Comment by pq** [comment]
/fyi @scheglov 

Likely related to 4bfa66e1acd286c778b37b57567f1c1368d4be6a.

@davidmorgan: any further ideas on a repro?

**Comment by bwilkerson** [comment]
Could you email Phil and I a link to the internal bug?

**Comment by davidmorgan** [comment]
Done :)

**Comment by scheglov** [comment]
I was able to reproduce the issue, and working on the fix.

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/132381

**Comment by davidmorgan** [comment]
Nice, thanks!
