### ISSUE TITLE
unnecessary_setters_getters should allow when one is deprecated

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#1992]
I have code that looks like this:

```dart
class C {
  List<dynamic> _captured;

  List<dynamic> get captured => _captured;

  @Deprecated(
      'captured should be considered final - assigning this field may be '
      'removed as early as Mockito 5.0.0')
  set captured(List<dynamic> captured) => _captured = captured;
}
```

Both the setter and getter have been flagged by `unnecessary_setters_getters`, but I think they should be allowed, as one is `@Deprecated`.

**Comment by pq** [comment]
I tend to agree.

@bwilkerson?

**Comment by bwilkerson** [comment]
It wouldn't be inconsistent if deprecated elements were treated like they were already gone. Not sure how often this comes up, but I wouldn't object to it.

See also https://github.com/dart-lang/linter/issues/1991 for another possible tweak to the rule.
