### ISSUE TITLE
Why does `effective_dart` cancel out the hints from `pedantic`? 

### ISSUE THREAD

**Issue by andesappal** [dart-lang/linter#2029]
I had 87 hints from `pedantic`. Then I added `effective_dart`, and the hints disappeared.

**Comment by andesappal** [comment]
Also, could your team just automate the correction of `pedantic` hints? Or display an option to correct all hints?

**Comment by andesappal** [comment]
This is what I have:
![image](https://user-images.githubusercontent.com/54340176/76647433-9a095480-653b-11ea-9e29-73d24e24575d.png)

I also noticed I have a warning "Key 'include' is duplicated" in 
![image](https://user-images.githubusercontent.com/54340176/76647574-d472f180-653b-11ea-8c50-1c4b6467e14b.png)

Before I saw this warning, was using pedantic 1.9.0 and effective 1.2.1

**Comment by bwilkerson** [comment]
We don't currently support including more than one other file in an analysis options file (this is the first use case I've heard of for it). There are some interesting questions about how the files would interact in case of conflicts that we decided to solve by disallowing that situation to arise.

My guess is that the second `include` replaces the first.

**Comment by andesappal** [comment]
Disallowing it doesn't solve it, right? But that's ok, I'll use one analysis option at a time. Thank you.

**Comment by andesappal** [comment]
Maybe what's effective implies new code, thereby invalidating the current pedantic hints. I see, it does pose an interesting problem.

**Comment by bwilkerson** [comment]
The problems related to multiple `include`s are around conflicts. If one says to enable a lint and another says to disable it, which one wins? With a single `include` those problems don't exist.

And we defined the "conflicts" between a file and the file it includes to be resolved by saying that the file containing the `include` always takes precedence.

**Comment by domesticmouse** [comment]
Can we get this re-opened? Being able to depend on both of the `pedantic` and `effective_dart` linters is really needed. Last one wins, potentially with a warning. Or even make it an error.

**Comment by bwilkerson** [comment]
I've re-opened the issue, but I'm not sure what you're asking for. We produce a diagnostic (with a severity of error) telling the user that we don't support having multiple `include`s (or, more technically, the YAML parser tells the user that duplicate keys are not allowed).

> Being able to depend on both of the pedantic and effective_dart linters is really needed.

I'd be interested to understand more about _why_ this is needed and just how badly the lack of support is impacting our users. I'm not opposed to adding support, but we need to prioritize our efforts.

Unfortunately, supporting the inclusion of multiple analysis options files is a non-trivial effort. If we only needed to worry about lints, then I suspect that the merge semantics would be fairly easy to define. But we're including the whole analysis options file, and the semantics of merging _all_ of the options isn't quite as straight-forward. (We actually spent some time when first adding inclusion support attempting to do just that and decided that it was more important to be able to have a single chain of inclusion than to postpone the release while we figured it all out.)

**Comment by domesticmouse** [comment]
The core issue is that the two list of lints contain disjoint recommended lints. I want to be able to recommend a best practices setting that contains both.

One work around would be to merge the two sets of lints into a best practices set and publish that list.

**Comment by bwilkerson** [comment]
@mit-mit

**Comment by mit-mit** [comment]
@domesticmouse can you elaborate on _why_ this is really needed? I'm not sure I understand the use case.

**Comment by domesticmouse** [comment]
Let me turn the question around the other way. Why are there lints included in the [`effective_dart` configuration](https://github.com/tenhobi/effective_dart/blob/master/lib/analysis_options.1.3.0.yaml), which AFAICT enforce the best practices we document at [dart.dev/guides/language/effective-dart](https://dart.dev/guides/language/effective-dart), but are not int the [`pedantic` configuration](https://github.com/google/pedantic/blob/master/lib/analysis_options.1.9.0.yaml)?

**Comment by bwilkerson** [comment]
The `pedantic` package represents the collection of lints that are enabled for our internal users. The internal community has not chosen to adopt all of the lints in `effective_dart` for various reasons. Sometimes it's because of the number of false positives, sometimes for other reasons.

**Comment by domesticmouse** [comment]
False positives are bad. I'll stick with just recomending `pedantic` then.
