### ISSUE TITLE
public_member_api_docs needs to be opt-in

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#208]
If we turn on `public_member_api_docs`, we get lots of messages about how our examples are lacking dart docs. This is pointless, since we never actually turn the examples into dartdoc files.

Ideally, we'd be able to opt each library we care about into dartdocs, e.g. by putting a @documented pragma on the `library` directive.

**Comment by yjbanov** [comment]
As of dartdoc [0.8.5](https://github.com/dart-lang/dartdoc/commit/b7ac9653753eb6efec96d173f8ba6d7a52263928) there is a pragma `<nodoc>` that be used to control this. Perhaps `public_member_api_docs` should simply observe that.

**Comment by Hixie** [comment]
Wouldn't that be opt-out?

**Comment by yjbanov** [comment]
It is. I'm mentioning it because it is related and readily available (since it is already supported by dartdoc).

Also, perhaps opt-out might be better because if you forget to opt-in the linter will not remind you to document your API docs. However, if you forget to opt-out the linter will complain. This way you do not accidentally forget to document your public API, which I believe is the point of this lint option.

**Comment by bwilkerson** [comment]
Does this affect anything other than examples? Seems to me that there's a lot more non-example code than example code in most packages, so, in addition to Yegor's point, it seems like it would be less work to opt-out where you don't want them than vice versa.

Of course, it seems like it would be even less work for the lint to simply know to not look at code in the examples directory.

**Comment by Hixie** [comment]
The main thing it affects is end-developer's code, which mostly doesn't need to be documented. What we'd like is to be able to say that specific libraries in flutter/packages/flutter need docs, because we've written lots of docs for them, but not others, because we haven't.

This might honestly be moot at the point where we've written all the docs.

**Comment by pq** [comment]
I think we can mark this as stale as the flutter tool has a (now time-worn) workaround.

https://github.com/flutter/flutter/blob/65069ed4de646b8775de99a1408030ae720f1d80/packages/flutter_tools/lib/src/commands/analyze_once.dart#L136-L139
