### ISSUE TITLE
Export test utilities

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2104]
Test utilities

    test/util/annotation.dart
    test/util/test_resource_provider.dart

are depended on internally.  We should export them (so they don't need to be copied).

**Comment by pq** [comment]
(This is part of #2105.)

**Comment by bwilkerson** [comment]
Prior art: In the `analyzer` package, we created a directory under `lib` (`lib/src/test_utilities`) in which to put such things. The alternative we discussed was to create a separate package to hold testing support that other packages could have a dev dependency on.

**Comment by pq** [comment]
Thanks! `lib/src/test_utilities` is exactly the direction I'm leaning.
