### ISSUE TITLE
unawaited_futures misses cases

### ISSUE THREAD

**Issue by Rockvole** [dart-lang/linter#2123]
Dart VM version: 2.8.2 (stable) (Unknown timestamp) on "linux_x64"

I have noticed while using the unawaited_futures lint feature that the lint misses cases quite often. Maybe 2/10 it will miss the case and show nothing. It could be just cases where there is an async and the function returns void.

**Comment by Rockvole** [comment]
Is there another lint feature which prompts to return Future<void> instead of void on async functions ?

**Comment by pq** [comment]
See [`avoid_void_async`](https://dart-lang.github.io/linter/lints/avoid_void_async.html) and also the conversation in https://github.com/dart-lang/linter/issues/2095.

**Comment by Rockvole** [comment]
Thanks @pq 
I turned on that lint feature and it notified me to replace 321 voids with <code>Future&lt;void&gt;</code>
That enabled me to discover 17 awaits I had missed.

Should save me quite a bit of time going forward - I wasted 3 hours yesterday debugging one of those awaits I had missed.

Would be good if <code>avoid_void_async</code> was turned on by default in new projects.

**Comment by pq** [comment]
Ah, cool.  So nice to hear that it was useful!  There's been a bunch of lively debate on this one and your experience is a great testimonial.  Cheers!

**Comment by Rockvole** [comment]
I did search for such a lint feature before asking - my google history shows I searched :

    dartlang lint async void

But I never managed to find it :(
