### ISSUE TITLE
Bogus literal_only_boolean_expressions

### ISSUE THREAD

**Issue by apwilson** [dart-lang/linter#2139]
This code throws an analyzer warning that's bogus imo:

```
///
typedef bool Foo();

///
class Bar {
  final Foo _foo;

  ///
  Bar(this._foo);

  ///
  void baz() {
    if (_foo?.call() ?? false) {
      print('bar');
    }
    print('foo');
  }
}
```

**Comment by asashour** [comment]
I am unable to reproduce on `master`, there is no `literal_only_boolean_expressions` lint triggered.

**Comment by srawlins** [comment]
I cannot either. Please re-open if you can reproduce in a recent Dart SDK.
