### ISSUE TITLE
RangeError: Value not in range: -1 from unnecessary_string_escapes.dart:109

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#2191]
Caught by internal crash reporting:

```
RangeError: RangeError: Value not in range: -1
  | at _StringBase.substring | (dart:core)
  | at _Visitor.visitLexeme | (unnecessary_string_escapes.dart:109)
  | at _Visitor.visitStringInterpolation | (unnecessary_string_escapes.dart:70)
  | at StringInterpolationImpl.accept | (ast.dart:9212)
  | at LinterVisitor._runSubscriptions | (linter_visitor.dart:725)
  | at LinterVisitor.visitStringInterpolation | (linter_visitor.dart:594)
  | at StringInterpolationImpl.accept | (ast.dart:9212)
  | at NodeListImpl.accept | (ast.dart:7560)
  | at ArgumentListImpl.visitChildren | (ast.dart:360)
  | at RecursiveAstVisitor.visitArgumentList | (visitor.dart:623)
  | at ArgumentListImpl.accept | (ast.dart:356)
  | at MethodInvocationImpl.visitChildren | (ast.dart:7127)
  | at RecursiveAstVisitor.visitMethodInvocation | (visitor.dart:1067)
  | at LinterVisitor.visitMethodInvocation | (linter_visitor.dart:468)
```

stable signature of `RangeError at _StringBase.substring at dart:core-eee791a8`

**Comment by devoncarew** [comment]
2 users had 9 total occurrences of this

**Comment by bwilkerson** [comment]
Do we have a reproduction case?

**Comment by bwilkerson** [comment]
@a14n

**Comment by devoncarew** [comment]
> Do we have a reproduction case?

No, just the exception message and stack trace.

**Comment by a14n** [comment]
There's already a [lot of test](https://github.com/dart-lang/linter/blob/master/test/rules/unnecessary_string_escapes.dart) and it's not obvious what could lead to this error :-/

**Comment by bwilkerson** [comment]
@MichaelRFairhurst I suspect that this might have been impacted by the fix you recently made to `contentOffset` and `contentEnd`. This code probably worked around the bug and needs to be fixed. Can you take a look at it and advise and/or fix the issue?

**Comment by devoncarew** [comment]
We're seeing this pretty consistently internally (a low but consistent reporting rate - hit a few times a day by a few users).

**Comment by MichaelRFairhurst** [comment]
This has been fixed.

**Comment by bwilkerson** [comment]
It's been fixed in `linter`, but the fix hasn't been pulled into the SDK (in case anyone wants to keep this issue open until the roll happens).
