### ISSUE TITLE
investigate code coverage outage

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2200]
Coverage reports are no longer making it to coveralls:

https://coveralls.io/github/dart-lang/linter

Possibly we need to migrate from using [`dart_coveralls`](https://github.com/block-forest/dart-coveralls) to [`coveralls.dart`](https://docs.belin.io/coveralls.dart/)?

**Comment by pq** [comment]
/fyi @devoncarew @kevmoo in case you've seen this on other repos?

**Comment by kevmoo** [comment]
Related? https://github.com/dart-lang/sdk/issues/42819

**Comment by pq** [comment]
Maybe!  Thanks! 👍

**Comment by pq** [comment]
Hmmm, still broken and I think by now that fix has made its way to travis. 🤔

**Comment by pq** [comment]
Rather than try and patch up `dart_coveralls`, I migrated to the approach taken by the `coveralls` package for self-testing.  Marking as fixed w/ #2234.
