### ISSUE TITLE
Who is the user in // TODO(username): message. ?

### ISSUE THREAD

**Issue by Henge9** [dart-lang/linter#2231]
**Describe the issue**
In the linter description for TODOs a username is mentioned. Who is the user? The one that created the TODO or the one who should do the TODO? 

**Expected behavior**
No confusion about the username in the TODO.
 
**Additional context**
// TODO(username): message.
https://dart-lang.github.io/linter/lints/flutter_style_todos.html

**Comment by Henge9** [comment]
I found the answer in https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#comments

"TODOs should include the string TODO in all caps, followed by the GitHub username of the person with the best context about the problem referenced by the TODO in parenthesis. A TODO is not a commitment that the person referenced will fix the problem, it is intended to be the person with enough context to explain the problem. Thus, when you create a TODO, it is almost always your username that is given."

**Comment by pq** [comment]
Thanks @Henge9!

This could really use explanation in the lint to save folks confusion in the future.

**Comment by Henge9** [comment]
Thank you for the fast and nice response. The Dart community is really fantastic.  This was my second time and both have been responded on under an hour and politely.
