### ISSUE TITLE
Lint to warn about importing a package you do not directly depend on

### ISSUE THREAD

**Issue by dnfield** [dart-lang/linter#2304]
Package a.yaml:

```yaml
dependencies:
  b: any
```
package b.yaml:

```yaml
dependencies:
  c: any
```

pacakge a.dart:

```dart
import 'package:c/c.dart'; // should get linted

void main() {}
```

It'd be nice if a lint could catch that package `a` is transitively depending on `c` and importing it - and insteaed should be directly depending on it.

**Comment by pq** [comment]
Thanks Dan!  As it happens I'm hoping to make some time for this in the next few weeks.  Tracked in https://github.com/dart-lang/linter/issues/29.

Feel free to chime in there (or re-open this if you think I closed it mistakenly).

**Comment by dnfield** [comment]
I agree this is a duplicate. Thanks!
