### ISSUE TITLE
gh actions build not running tests?  

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2315]
Looking at a recent run, I'm  not seeing the tests run:

![image](https://user-images.githubusercontent.com/67586/97781057-fad6b300-1b45-11eb-8d71-f1a182e577a5.png)

https://github.com/dart-lang/linter/runs/1333844495?check_suite_focus=true

(**EDIT**: or actually maybe they are but we're not waiting for them to complete?)

Interesting aside, on travis tests are running but not failing as expected.  See for example:

https://travis-ci.org/github/dart-lang/linter/jobs/740287956

(I suspect I messed  this up when I  got coverage working again.)

Also, to investigate: is coverage working properly with gh-actions?

/fyi @devoncarew

**Comment by pq** [comment]
I think maybe this is it:

https://github.com/dart-lang/linter/blob/c02ae2c457951ea680fda3bae932acc679ebfef0/tool/travis.sh#L68

I'm guessing we need to install a coveralls token or maybe use the dedicated GH action?

https://github.com/marketplace/actions/coveralls-github-action

**Comment by devoncarew** [comment]
Ah, yeah, very likely there's a bit more setup to do for actions.

Additionally, perhaps we should have the script run the tests even if there's no coverage token.
