### ISSUE TITLE
package_names: should allow leading `_`

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#2331]
This is very common, especially with unpublished packages used for testing.

**Comment by pq** [comment]
I tend to agree.

@jonasfj: any concerns?

**Comment by pq** [comment]
@kevmoo : to be clear, are you thinking this should be relaxed for all packages or just ones meant for publishing?

**Comment by kevmoo** [comment]
If it was just allowed on packages with `publish_to: none` I'd be fine w/ that.

I know we did have some packages published using `_` first. @jonasfj may have thoughts.

**Comment by sigurdm** [comment]
We have https://pub.dev/packages/_dummy_pkg used for integration tests of pub. And there is the https://pub.dev/packages/_fe_analyzer_shared package.
I think we want to allow these packages. I guess the convention is that a `_` prefix means end-users don't want to depend directly on that package which aligns somewhat with privacy in dart.

**Comment by pq** [comment]
OK!  It sounds to me like widening the check to allow for leading underscores is the right thing to do.  If there are certain packages that should not be directly depended on that  feels like another check.

**Comment by jonasfj** [comment]
> If there are certain packages that should not be directly depended on that feels like another check.

I don't think that needs a check. If authors document that in the README is should be fine.

The pattern of using package names starting with underscore is just a neat convention, it's not something we've formalized.
