### ISSUE TITLE
Missing error when defining local variables with the same name as other parameters in scope

### ISSUE THREAD

**Issue by arielbh** [dart-lang/linter#2400]
I would like the linter to identify the following syntax:
`  Foo bar(int result) {
    Foo result;
    return result;
  }`
and warn/raise the following error: 
"A local variable named `result' is already defined in this scope" 
Similar to C#''s CS0128 (https://docs.microsoft.com/en-us/dotnet/csharp/misc/cs0128)
This rule should be available to any Dart user at any time.

**Comment by srawlins** [comment]
Maybe a duplicate of https://github.com/dart-lang/linter/issues/597, @a14n I think was working on a `avoid_shadowing` lint rule.

**Comment by srawlins** [comment]
Closing as a duplicate of https://github.com/dart-lang/linter/issues/3755; this one is older but that one has a lot of discussion.
