### ISSUE TITLE
add bulk fixes for scored lints

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2404]
The following lints have fixes but no corresponding bulk fixes:

  - [x] `avoid_relative_lib_imports` (https://github.com/dart-lang/sdk/commit/44cb6a17e941abef864f9c502e37b66675db29a4)
  - [x] `always_require_non_null_named_parameters` (https://github.com/dart-lang/sdk/commit/daac91856bfefbd27f03acd4e8d4e73824f41961)
  - [x] `avoid_private_typedef_functions` (https://github.com/dart-lang/sdk/commit/4a7dd03932b462fa9f5a42c16d8add64400cdf7c)
  - [x] `prefer_is_not_operator` (https://github.com/dart-lang/sdk/commit/1d35109cc135d37da44f8216b08dae42dd1ab6ab)
  - [x] `unnecessary_null_in_if_null_operators` (https://github.com/dart-lang/sdk/commit/63795a73e6d13993a8edefffac33c1ff29950742)
  - [x] `unnecessary_string_interpolations` (https://github.com/dart-lang/sdk/commit/f9c3c09a9e745e2a261529a2d4fba1dd0b01a25e)
  - [x] `use_function_type_syntax_for_parameters` (https://github.com/dart-lang/sdk/commit/b29d36c55952528007b12422f9c0fd1a37d3ffd2)

**Comment by pq** [comment]
`prefer_is_not_operator`: https://dart-review.googlesource.com/c/sdk/+/178842

**Comment by pq** [comment]
`avoid_private_typedef_functions`: https://dart-review.googlesource.com/c/sdk/+/178932

**Comment by srawlins** [comment]
Complete?

**Comment by pq** [comment]
I think so.  We still have some fixes to implement (see https://github.com/dart-lang/lints/issues/12) but we're caught up on bulk fixes.  Thanks!
