### ISSUE TITLE
add fixes for fixable canonical lints

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2408]
Add fixes for:

  - [x] `prefer_typing_uninitialized_variables`
  - [x] `avoid_function_literals_in_foreach_calls`
  - [ ] `avoid_null_checks_in_equality_operators`
  - [x] `avoid_returning_null_for_void`
  - [x] `exhaustive_cases`
  - [ ] `prefer_initializing_formals`
  - [x] `prefer_is_not_operator` (covered by an assist)
  - [ ] `prefer_void_to_null`
  - [ ] `unnecessary_getters_setters`
  - [x] `unnecessary_string_escapes`
  - [x] `unnecessary_string_interpolations` (https://github.com/dart-lang/sdk/commit/f9c3c09a9e745e2a261529a2d4fba1dd0b01a25e) cheers @parlough!

See: #2405

**Comment by parlough** [comment]
@pq  Just so I don't do any overlapping work already being done, any suggestions for one to attempt next?

**Comment by bwilkerson** [comment]
That one is already covered by an assist. See `ConvertIntoIsNot`.

It looks like this list didn't take assists into account.

**Comment by pq** [comment]
> It looks like this list didn't take assists into account.

ah... and so maybe I should add that assist processor scraping code to the scorecard after all? 🤔

**Comment by pq** [comment]
@parlough: if you decide to take a look at one, maybe just post your intention here?  I can do the same.

Thanks!

**Comment by bwilkerson** [comment]
> ... so maybe I should add that assist processor scraping code to the scorecard after all?

I don't think there's any connection between assists and the lints that they overlap with, so I don't think you can automate that check.

> if you decide to take a look at one ...

Just don't forget to try it in the IDE first to see whether there's an assist that applies.

**Comment by pq** [comment]
> I don't think there's any connection between assists and the lints that they overlap with

sorry, right, i meant w/ metadata added to capture that in server source but I think it's overkill. probably better to just track those few exceptions here.

**Comment by bwilkerson** [comment]
Closing this in favor of the more complete list in https://github.com/dart-lang/sdk/issues/45932. I believe that there were lints added to the core, recommended and flutter lists after this issue was opened, hence the reason the other list is more complete.
