### ISSUE TITLE
Unicode escape range warning (in `valid_regexps`)

### ISSUE THREAD

**Issue by frankyjuang** [dart-lang/linter#2471]
**Describe the issue**
rule valid_regexps warns about unicode escape range

**To Reproduce**
```dart
  RegExp cjk = new RegExp(r'[\u{4E00}-\u{9FFF}]', unicode: true);
```

**Expected behavior**
no warning

**Comment by pq** [comment]
See also: https://stackoverflow.com/questions/61151471/regexp-for-unicode-13-emojis

**Comment by pq** [comment]
Sorry for the slow response on this one!
