### ISSUE TITLE
failing tests are not failing the main bot

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2475]
See: https://github.com/dart-lang/linter/pull/2474/checks?check_run_id=1949148387.

33 failed tests but the bot is green.  😬 

Possibly this started failing once we moved to the travis workflow?

https://github.com/dart-lang/linter/blob/master/tool/bot.sh#L58

/cc @athomas @devoncarew who may have ideas?

**Comment by pq** [comment]
Hrmmmm.  

Possibly the `dart` cli is not properly setting exit status?

**Comment by devoncarew** [comment]
Is this CI running tests normally (`dart test`) or running them via the coverage package? Perhaps switch to just dart test and see if the CI fails then?

**Comment by pq** [comment]
I'm not using `dart test` (just `dart test/all.dart`).  Interestingly those tests are run in the background (`&`) so coverage can run.  I wonder if fast-fail doesn't work in scripts that way?  Curiously, the coverage package does it's own coverage collection that way too.  I wonder if there's works?

https://github.com/dart-lang/coverage/blob/master/tool/travis.sh

/cc @athomas @kevmoo @grouma

**Comment by pq** [comment]
RE: running using `dart test`, we're doing something funny w/ redirected output and bot runs are doubling output:

![image](https://user-images.githubusercontent.com/67586/108798403-99967d80-7542-11eb-9ed7-5ed4d5cc5708.png)

(See full run: https://github.com/dart-lang/linter/pull/2477/checks?check_run_id=1957977024)

On the upside, run that way does fail the build... 🤔

**Comment by grouma** [comment]
> I'm not using `dart test` (just `dart test/all.dart`). Interestingly those tests are run in the background (`&`) so coverage can run. I wonder if fast-fail doesn't work in scripts that way? Curiously, the coverage package does it's own coverage collection that way too. I wonder if theirs works?
> 
> https://github.com/dart-lang/coverage/blob/master/tool/travis.sh
> 
> /cc @athomas @kevmoo @grouma

I just did a quick test and a failing test does cause a fail: https://github.com/dart-lang/coverage/pull/331

**Comment by pq** [comment]
That's curious for sure. Thanks for checking @grouma!
