### ISSUE TITLE
deprecate avoid_returning_null under null safety

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#2484]
lot's of noise!

see https://github.com/dart-lang/linter/issues/1930

**Comment by bwilkerson** [comment]
@kevmoo Could you be more specific about the kind(s) of noise that you're seeing? I'd like to better understand the problem in order to understand the solution.

**Comment by kevmoo** [comment]
Before null-safety, you don't want `giveMeInt()` to return null, because it breaks `5 + giveMeInt()`.

With any package opting into null-safety, you know get the right static hints.

I'd say we say this lint is obsolete/deprecated for null-safe packages

**Comment by bwilkerson** [comment]
Agreed. Just wanted to know if there was more to it than that.

**Comment by pq** [comment]
Closing in favor of #2636.  (TL;DR: yes, let's!)
