### ISSUE TITLE
prefer_initializing_formals: handle case where ctor param is non-nullable, but field is nullable

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#2491]
```dart
class CheckedFromJsonException implements Exception {
  final Object? innerError;

  final String? message;

  CheckedFromJsonException(this.innerError) : message = null;

  CheckedFromJsonException._(
    Object innerError,
  )   : innerError = innerError,
        message = innerError.toString();
}
```

I'd like to enforce one of my constructors is "stricter" (not allowing null) about `innerError` than the associated field.

But I still get the `prefer_initializing_formals` lint.

**Comment by bwilkerson** [comment]
Would it work to write the following?
```
class CheckedFromJsonException implements Exception {
  final Object? innerError;

  final String? message;

  CheckedFromJsonException(this.innerError) : message = null;

  CheckedFromJsonException._(
    this.innerError,
  ) : message = innerError.toString();
}
```

**Comment by a14n** [comment]
You can add a stricter type to your initializing formal parameter:

```dart
class CheckedFromJsonException implements Exception {
  final Object? innerError;

  final String? message;

  CheckedFromJsonException(this.innerError) : message = null;

  CheckedFromJsonException._(
    Object this.innerError,  // non-null enforced even if innerError is nullable
  )   : message = innerError.toString();
}
```

**Comment by bwilkerson** [comment]
Yes, I missed the type annotation on the private constructor's parameter. Thanks.

But I think the lint is still valid as is.

**Comment by kevmoo** [comment]
The lint is fine.

I guess maybe what i want in my case is the recommendation to type the `this.field` bit then.

**Comment by bwilkerson** [comment]
That should definitely be part of the quick fix, if it isn't already.

**Comment by kevmoo** [comment]
@pq – it'd be nice if the lint pointed the user towards https://github.com/dart-lang/linter/issues/2491#issuecomment-788708379

**Comment by eseidelGoogle** [comment]
Hmm, I just hit this issue on the latest Flutter beta.  Dart 2.14.4

```dart
class Bid {
 final int? amount;
 Bid(int amount) : amount = amount;
 Bid.pass() : amount = null;
}
```

I guess my solution is I'm supposed to type Bid(int this.amount); instead?  

That's not mentioned in the docs:
https://dart-lang.github.io/linter/lints/prefer_initializing_formals.html

**Comment by pq** [comment]
@eseidelGoogle: I think that's the right approach.

I've got a change to the docs in flight: #3088

Sorry for the confusion!

**Comment by bwilkerson** [comment]
That probably is what we're suggesting at this point (@munificent for confirmation), but it seems error prone to me. It seems like it would be really easy for a user to not notice the `?` on the field's type and to assume that the type on the parameter can be deleted, thus accidentally changing the signature of the constructor. But maybe the fact that there's a type on a field formal parameter is enough or a signal?

**Comment by munificent** [comment]
> That probably is what we're suggesting at this point (@munificent for confirmation)

Yeah, I think this is the right suggestion.
