### ISSUE TITLE
Consider another package name? lint? linter? source_lint?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#25]
`dart_` is a bit redundant.

CC @sethladd for his perspective

**Comment by sethladd** [comment]
Our friends in naming would probably like "Linter for Dart".

**Comment by pq** [comment]
:+1:  for "Linter for Dart" for the human-readable/product name, but what about the package name?  Is "linter" too open-ended?

**Comment by kevmoo** [comment]
+1!

**Comment by pq** [comment]
Works for me.  @sethladd : can you do the move?  I'm guessing/hoping history, issues, etc will make the transition?

**Comment by seaneagan** [comment]
Is this package going to expose a command-line app?  If so, I find it nice to have the name of the command-line app match that of the package, and 'linter' wouldn't be a great name for a command-line app.  Just something to consider.

**Comment by pq** [comment]
Absolutely.  I've got a provisional commandline entry point already.  Thanks for chiming in @seaneagan!

**Comment by sethladd** [comment]
Go ahead and rename this repo. GitHub is very good at redirects.

and yes, matching command-line names is generally a good idea.

**Comment by seaneagan** [comment]
Besides a command-line app, another place where namespacing with `dart` or `dart_` would come in handy be #7.  The configuration file should be namespaced e.g. `.dartlintrc` instead of `.linterrc`, and it's much easier to mentally connect that to a `dartlint` or `dart_lint` package than a `linter` package.

**Comment by pq** [comment]
Rename done.  That said, @seaneagan, you bring up some good points.  Let's take the config file conversation over to #7...
