### ISSUE TITLE
null has snuck into linter docs

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#2506]
Check out the `avoid_dynamic_calls` docs: https://dart-lang.github.io/linter/lints/avoid_dynamic_calls.html

I see "Linter vnull". :(

cc @goderbauer

**Comment by bwilkerson** [comment]
@pq

**Comment by parlough** [comment]
I believe this just needs the since information recalculated, but was delayed by https://github.com/dart-lang/linter/issues/2498

**Comment by pq** [comment]
@parlough is right.  The way I was calculating version info hasn't scaled to the frequent dev pushes.  Sorry about that!

**Comment by goderbauer** [comment]
Closing this since null no longer appears in the referenced link.
