### ISSUE TITLE
[linter] Support for non-function type aliases

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2509]
Follow-up from https://github.com/dart-lang/sdk/issues/44078 and https://github.com/dart-lang/sdk/issues/44951, we need to shore up linter support for non-function type aliases.

- [x] consider existing lints 
  - [x] ~`avoid_private_typedef_functions`~ https://github.com/dart-lang/linter/issues/2535
  - [x] `camel_case_types`
  - [x] `prefer_mixin`
  - [x] `public_member_api_docs`
  - [x] `slash_for_doc_comments`
- [x] add test cases
- [x] consider new lints

**Comment by pq** [comment]
I did a quick look through existing lints and besides the fix to `prefer_mixin` didn't come up with anything else to address.  I didn't feel a strong pull to add test cases either though I'm super open to suggestions.

@srawlins, @bwilkerson, @scheglov : curious if anything jumps out at you?

As for new lints, I'm curious if there's any thinking about naming conventions.  CamelCase?  If yes, then thoughts on extending [camel_case_types](https://dart-lang.github.io/linter/lints/camel_case_types.html)?  Alternatively I guess we could add `camel_case_nonfunction_typedefs` 😬 ...

**Comment by bwilkerson** [comment]
Doesn't `camel_case_types` already cover the names defined via `typedef`? I would expect it to just continue to work, but a test for that case would be in order.

As for other places that might need fixed up, you could search for places where `staticElement` is being invoked on a `TypeAnnotation`, though that's probably going to return lots of places where it's used on something other than a type annotation.

**Comment by pq** [comment]
> Doesn't camel_case_types already cover the names defined via typedef? 

Yes it does cover function type aliases.

The question is whether it should flag the following:

```dart
class A { }

typedef a = A;
```

I think yes?

(Currently it does not.)

Thanks for the tip on `staticElement` greps!

**Comment by bwilkerson** [comment]
Ah, that's because it's visiting `FunctionTypeAlias`s when I think it ought to be visiting `GenericTypeAlias`s (it might need to visit both until the experiment is enabled). So you can also look for other implementations of `visitFunctionTypeAlias`.

**Comment by scheglov** [comment]
FWIW, this means that the lint did not work for "modern" function type aliases as well, like `typedef b = void Function();`.
`FunctionTypeAlias` is not going anywhere, I think, because it is a different syntax than `GenericTypeAlias`.

**Comment by pq** [comment]
Looking at `visitFunctionTypeAlias`, brought up these suspects:

* `avoid_private_typedef_functions`
* `public_member_api_docs`
* `slash_for_doc_comments`
* `type_annotate_public_apis`

All seem straightforward.  Thanks!

**Comment by pq** [comment]
Marking as done.  If ideas for lints present themselves we can open new tracking issues.
