### ISSUE TITLE
☂ downstream package updates to prepare for 1.4.0 (and improved `directives_ordering`)

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2609]
Linter [1.4.0](https://github.com/dart-lang/linter/releases/tag/1.4.0) introduces `directives_ordering` updated to sort more cases (see https://github.com/dart-lang/linter/pull/2596).  In order to land in the Dart SDK ([cl/196581](https://dart-review.googlesource.com/c/sdk/+/196581)), a number of downstream fixes need to be made to SDK and Flutter packages.

Dart SDK:

- [x] https://dart-review.googlesource.com/c/sdk/+/196223
- [x] https://dart-review.googlesource.com/c/sdk/+/196180

Flutter:

- [x] https://github.com/flutter/flutter/pull/81017
- [x] https://github.com/flutter/plugins/pull/3823
- [x] https://github.com/flutter/flutter/pull/80817
- [x] https://github.com/flutter/flutter/pull/80901
- [x] https://github.com/flutter/flutter/pull/81210

...

- [x] https://github.com/flutter/flutter/pull/81220 (disable lint temporarily)
- [x] https://github.com/flutter/flutter/issues/81219 (re-enable once SDK lands)

(Some downstream packages):

* https://github.com/dart-lang/args/pull/193
* https://github.com/dart-lang/gcloud/pull/112
* https://github.com/dart-lang/mime/pull/46
* https://github.com/dart-lang/source_span/pull/76
* https://github.com/dart-lang/io/pull/76

**Comment by kevmoo** [comment]
I *like* the change, it just requires some follow-up on the package side.

**Comment by pq** [comment]
**UPDATE:**  I've got yet one more change queued up to fix flutter (flutter/flutter#81210) but even then it's a race and there's a chance that violations will get introduced before the auto-roll.

@goderbauer: do you object to me disabling the lint until the next roll when I can re-enable it and fix up any newly introduced breakages?

**Comment by pq** [comment]
@kevmoo: 💯 

To be honest, I wasn't expecting this broad impact. (Nor do I expect was @davidmorgan 😄.)  Thinking ahead, it'd be great to have some way to get proactive about tracking soon to be breaking ecosystem packages so we can (ideally) fix them up proactively.  @athomas and I were chatting about this a bit...  Maybe we could leverage the index you have in repo_manager?

**Comment by pq** [comment]
FWIW, here's another breakage, unrelated to this change, that would have been nice to detect (and fix) proactively: 

https://github.com/dart-lang/graphs/pull/63

(fyi @bwilkerson @scheglov)

**Comment by goderbauer** [comment]
> @goderbauer: do you object to me disabling the lint until the next roll when I can re-enable it and fix up any newly introduced breakages?

No objections. (I suspect there will still be a race between your change enabling it again and other changes, but maybe that race is easier to manage?)

**Comment by pq** [comment]
Right.  It also has the advantage of something I can do and manage manually (as opposed to an auto-roll that just gets blocked).

**Comment by pq** [comment]
Linter 1.4.0 is re-landed in the SDK as of https://github.com/dart-lang/sdk/commit/513c1a1c7eb273948faa2fd57a8b786ba5314cd7.  When it gets rolled into Flutter, I'll loop back and re-enable the lint in the Flutter options.

**Comment by pq** [comment]
Closed w/ https://github.com/flutter/flutter/issues/81219. Downstream changes may continue to trickle in.
