### ISSUE TITLE
Surface whether a lint belongs to core.yaml or recommended.yaml in the linter docs

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#2624]
In the linter documentation at https://dart-lang.github.io/linter/lints/index.html various lints are tagged with style badges, e.g. "style: flutter", "style: pedantic", etc:

![Screen Shot 2021-05-06 at 10 38 55 AM](https://user-images.githubusercontent.com/1227763/117342537-35ecd280-ae58-11eb-96c5-33fc941cf157.png)

Can we also surface there in a similar manner whether a lint is part of `core.yaml` and/or `recommended.yaml` from package:lints?

Related issue:
* https://github.com/dart-lang/linter/issues/2623 to update "flutter: style" to use package:flutter_lints.

**Comment by bernaferrari** [comment]
You could also remove flutter (make it depend on the new flutter lint) and maybe pendatic (or at least show in gray as it was deprecated).

**Comment by parlough** [comment]
As a reference, I will be including some sort of tags for this as part of the [dart.dev lints page](https://dart.dev/tools/linter-rules) as part of the work in https://github.com/dart-lang/site-www/issues/3222

**Comment by pq** [comment]
The flutter badge reflects lints in `package:flutter_lints` which seems reasonable to me.

Making pedantic grey is a good idea.

I've added logic to badge core and recommended sets and will regenerate docs shortly.

Thanks for the nudge!

**Comment by bernaferrari** [comment]
> The flutter badge reflects lints in package:flutter_lints which seems reasonable to me.

I just clicked on it and it redirected to the deprecated flutter lints.

**Comment by bernaferrari** [comment]
BTW what is the instance with effective dart? Will it keep alive with the new/official dart lints? Or should it also become gray/deprecated with pedantic?

**Comment by pq** [comment]
> I just clicked on it and it redirected to the deprecated flutter lints.

👍  Sorry yes.  The fixed link will be in the regenerated docs.  Thanks!

**Comment by pq** [comment]
> BTW what is the instance with effective dart? 

It's a good question.  That list is community maintained.  As we get more alignment with effective Dart guidelines via core and recommended lints it may become superfluous?

/fyi @tenhobi

**Comment by tenhobi** [comment]
If we have an official package, i.e. `lints`, it makes sense to deprecate it in favor of those packages.
