### ISSUE TITLE
Run rules in parallel

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#265]
Based on the graphs on the system monitor I think analysis runs in a single thread, since rules treat the AST as a read only structure, there is no reason for not to run them in parallel, probably defaulting to the number of reported cores in the system running the analysis. Other possibility would be to run the same rule in several nodes simultaneously.

**Comment by alexeieleusis** [comment]
@pq @bwilkerson thoughts on this?

**Comment by bwilkerson** [comment]
I think that's a great idea, and one that we've talked about for analyzer / server in general. I do think that if we try to do anything multi-threaded we need to think about all of analyzer and not just the linter.

**Comment by pq** [comment]
I'm with Brian.  This would be a great enhancement for analysis in general!

**Comment by pq** [comment]
(Needless to say, a bit tricky to get right!)

**Comment by pq** [comment]
Since this hinges on deep analyzer rethinks (that are not AFIK planned), closing for now.
