### ISSUE TITLE
[Request] Lint for "a == b ? true : false" => "a == b"

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/linter#2654]
I wish Dart had a lint/quick fix for this case:
```dart
a == b ? true : false
// becomes a == b
a != b ? true : false
// becomes a != b

// or

if (a == b) {
    return true;
} else {
    return false;
}
// becomes return a == b;
```

I've seen Kotlin and other languages doing this.

**Comment by a14n** [comment]
[avoid_bool_literals_in_conditional_expressions](https://dart-lang.github.io/linter/lints/avoid_bool_literals_in_conditional_expressions.html) can help to avoid this pattern.

**Comment by bernaferrari** [comment]
for some reason, I never found this before. Thanks!!!
