### ISSUE TITLE
prefer_initializing_formals doesn't seem to understand differences in null-safe or not-null-safe parameters.

### ISSUE THREAD

**Issue by dnfield** [dart-lang/linter#2664]
Consider:

```
class Foo {
  Foo(int initialValue) : value = initialValue;

  int? value;
}
```

I don't think prefer_initializing_formals should fire for this. The ctor is saying you have to initialize this class with a non-null value to start, but it might later become null. I could more or less achieve this with

```
class Foo {
  Foo(this.value) : assert(value != null);

  int? value;
}
```

But then I lose compile time checking.

**Comment by a14n** [comment]
You can type annotate the initializing formal:

```dart
class Foo {
  Foo(int this.value);

  int? value;
}
```

**Comment by dnfield** [comment]
I did not know that.  Maybe the lint doc could be updated to show that?
