### ISSUE TITLE
library_private_types_in_public_api rule conflicts with convention of making flutter State classes private

### ISSUE THREAD

**Issue by Quijx** [dart-lang/linter#2665]
It is convention and common practice in flutter to make the `State` classes of `StatefulWidget`s private (for instance see examples in [StatefulWidget docs](https://api.flutter.dev/flutter/widgets/StatefulWidget-class.html)).
However since `StatefulWidget` contains a public method `createState`, which returns the private state class, the linter rule `library_private_types_in_public_api` complains.

A few possible solutions i could think of:
- Make the rule `library_private_types_in_public_api` ignore methods annotated with `@protected`
- Make a special exception for flutter `State` types.
- Change flutter convention to change signature to `State<Bird> createState() => _BirdState();` instead of `_BirdState createState() => _BirdState();` for private `State` classes.

**Comment by a14n** [comment]
I'd choose the third option: `State<Bird> createState() => _BirdState()`

**Comment by a14n** [comment]
FWIW the sample has been updated 11 days ago via https://github.com/flutter/flutter/pull/81578 . The current documentation relays on stable that doesn't contain yet this change.

**Comment by Quijx** [comment]
Ah. Thanks for that link. Looking at that discussion there, it seems like option 3 is being pursued. Since that means, this is no longer a linter problem, I'm closing this issue.
