### ISSUE TITLE
Graduate avoid_dynamic_calls from experimental

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#2666]
I have enabled avoid_dynamic_calls in a few repos, and really enjoy it's benefits. I'm not sure why it is marked experimental, but I think we should graduate it to not-experimental.

This is probably the first step to getting it into the lints package.

**Comment by pq** [comment]
I think the experimental tag was just to allow for some baking-in of semantics.  I wonder if it'd be appealing as is to folks thinking about canonical lint advice?  If so, let's graduate.  If there are any tweaks, maybe we can wait to hash them out?

Maybe open a proposal on `dart-lang/lints` to discuss?
