### ISSUE TITLE
non_constant_identifier_names should allow a trailing underscore

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#2687]
**Describe the issue**

When naming a variable which the developer _wants_ to name with a keyword (like class, enum, etc), a common pattern is to write a trailing semi-colon. E.g. `var class_` or `var enum_`. I don't think this should count as violating non_constant_identifier_names. I don't know of a good, consistent alternative pattern. (Using `clazz` or `klass` or `enuum` are not consistent names.)

**To Reproduce**

`var class_;`

**Expected behavior**

Allowed

**Comment by srawlins** [comment]
I'd be happy to mail a fix if this is an acceptable relaxation.

**Comment by pq** [comment]
Seems reasonable to me but am curious if @munificent has any feelings?  It'd be great to converge on some consistent advice across all the docs.

**Comment by munificent** [comment]
I don't know if I do it myself, but I think a trailing `_` is reasonable to allow.
