### ISSUE TITLE
add @Semvrij  to AUTHORS

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2689]
Re: https://github.com/dart-lang/linter/pull/2684

Hi @Semvrij!

We'd like to add an attribution to [AUTHORS](https://github.com/dart-lang/linter/blob/master/AUTHORS)...  How would you like that to look?

**Comment by Semvrij** [comment]
Hi @pq,

Can you add me this way? `Sem van Rij <sem@lekkerplakjekaas.nl>`
Thanks in advance!
