### ISSUE TITLE
Implement constructor tearoffs support in the linter

### ISSUE THREAD

**Issue by eernstg** [dart-lang/linter#2693]
This issue tracks support of the [constructor tearoffs feature](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md).  See the [enclosing meta-issue](https://github.com/dart-lang/sdk/issues/46228) for details.

---

## Rules that need investigation, tests, and possible updating

- [x] [`always_specify_types`](https://dart-lang.github.io/linter/lints/always_specify_types.html) (e.g. catch `List<List>;`, `List<List>.filled;`, ~`someFuture.then<List>`~) (https://github.com/dart-lang/linter/pull/2908)
- [x] `avoid_redundant_argument_values` (#2895)
- [x] ~`prefer_const_constructors`~
- [x] `unnecessary_const` (#2903)
- [x] #2911
- [x] #2909
- [x] #2912
- [x] #2910
- [x] `unnecessary_new` (#2902)
- [x] #2907
- [x] [`unnecessary_statements`](https://dart-lang.github.io/linter/lints/unnecessary_statements.html) (https://github.com/dart-lang/linter/pull/2901)

## Server updates

- [x] https://github.com/dart-lang/sdk/issues/47102
- [x] https://github.com/dart-lang/sdk/issues/47103

## New lints

- [x] #2904 (and https://github.com/dart-lang/site-www/issues/3525)

## Related issues / Future work

*  #2928 
*  #2914

**Comment by devoncarew** [comment]
@pq - I see all the existing lints / new lints items checked off above. Is this issue complete (at least from the POV of any work we'd want to do before we ship)?

**Comment by pq** [comment]
Yep.  I think we're good to go! 👍
