### ISSUE TITLE
Lint for catching cases of assigning Iterables to Lists

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#273]
I frequently write code like this:

``` dart
   List<Foo> foos = list.where(condition);
   List<Bar> bars = list.map(mapper);
```

...and so on, and the analyzer's fine with it (because List is a subclass of Iterable) and it crashes at runtime.

It would be great if there was a way to catch this. Even better would be if there was a way to annotate a method as "you cannot assume what subclass will be returned here".

(This shouldn't be the default, because it's very common to have code where you _can_ assume the subclass, at least in Flutter land.)

**Comment by alexeieleusis** [comment]
Do you want it to warn you to change the type of the variable? to remember to invoke toList?

**Comment by Hixie** [comment]
I dunno that it can know which is the right answer, really. It's sometimes one, sometimes the other.

**Comment by bwilkerson** [comment]
I expect that we want the lint rule to be more general and to catch any case where there is an implicit downcast:

void f(num n) {
  int i = n; // LINT
  g(n); // LINT
}

void g(int i) {}

I'm not sure what the correction message should say, but it would be great to eventually have a quick fix for the Iterable-assigned-to-List case to add an invocation of `toList()`.

**Comment by Hixie** [comment]
@bwilkerson It's definitely not _any_ case, for example Flutter code does this all the time and I wouldn't want the call sites to each be annotated with an `// ignore` rule.

But I could definitely get behind a way to say at the definition site what the convention should be.

**Comment by bwilkerson** [comment]
@Hixie Can you give me an example of the pattern?

**Comment by Hixie** [comment]
It's very common in Flutter code to know what the type of a getter will actually return. For example, you have a widget, you know it's render object will use cartesian coordinates (i.e. be a RenderBox), so you do:

```dart
final RenderBox renderBox = _childKey.currentContext.findRenderObject();
```

`BuildContext.findRenderObject()`'s signature is that it returns `RenderObject`, a `RenderBox` superclass.

**Comment by bwilkerson** [comment]
What makes the original case different (in a way that a static analyzer can distinguish)? I would prefer to not special case Iterable-assigned-to-List if we can determine a more general pattern.

Having annotations would be useful, but in general we cannot count on all code bases correctly identifying the cases where this pattern is (or is not) safe, so again, I'd rather not rely on it if possible.

Also, for completeness, I'll point out that in both cases there is an implicit cast, and that in a sound type system (which is what we're moving to) this will require a run-time cast with all of the overhead that implies.

**Comment by Hixie** [comment]
Nothing makes the cases different in a way that the static analyzer can distinguish without annotations.
I think the solution is either hard-coding these common core types, or annotations. See my initial bug description. :-)

I agree that not all code bases will do this. Not all code bases use types at all, in fact. This is just a lint for code bases that want to be particularly usable (such as, ideally, the core libraries and the Flutter libraries).

> Also, for completeness, I'll point out that in both cases there is an implicit cast, and that in a sound type system (which is what we're moving to) this will require a run-time cast with all of the overhead that implies.

The code I pasted is very common in Flutter code. We should not move to a world where overall performance decreases because of such patterns. But that's an issue for another bug.

**Comment by bwilkerson** [comment]
Ok. If there's no general pattern that analyzer can detect, then I think we should go with special casing for now. We can always generalize it later if we decide to add an annotation.

**Comment by devoncarew** [comment]
Ah, yup, this is it.

**Comment by srawlins** [comment]
I would expect this to be handled by `--no-implicit-casts`... but it appears not to... This isn't an _explicit_ cast right, just because there are types on the left side?

**Comment by bwilkerson** [comment]
As far as I know, yes, this is an implicit cast.

**Comment by srawlins** [comment]
This is caught by `--no-implicit-casts` (not recognized in `analysis_options.yaml` by dartanalyzer currently, as per https://github.com/dart-lang/sdk/issues/32235, which is what lead me to the false belief [above](https://github.com/dart-lang/linter/issues/273#issuecomment-400591138)).
