### ISSUE TITLE
How can I use 'require_trailing_commas' lint rule?

### ISSUE THREAD

**Issue by weakvar** [dart-lang/linter#2822]
I'd like to add the 'require_trailing_commas' lint rule in my project. Can I use it right now?

**Comment by pq** [comment]
Hi @weakvar.  The lints are bundled with the Dart SDK.  If you're on a fairly recent build, you should be able to use `require_trailing_commas`.  Have you added it to your `analysis_options.yaml`?

**Comment by weakvar** [comment]
Hey, @pq. Thanks for the reply! I've tried to add this rule in the `analysis_options.yaml`, but there is a warning: 'require_trailing_commas' is not a recognized lint rule. Is this lint are bundled on the latest stable Dart SDK? I'm running Dart 2.13.4.

**Comment by pq** [comment]
Hey!  So, yeah, to get this one you'd need to have a `dev` or `beta` channel release.

Sorry for the confusion!

**Comment by weakvar** [comment]
OK. Thank you!

**Comment by pq** [comment]
You're welcome!
