### ISSUE TITLE
Ignore lowercase_with_underscores for specific files

### ISSUE THREAD

**Issue by tgpsantos** [dart-lang/linter#2884]
Hello guys! 
I have some very specific **files that must have a number in the start of their name** (eg `1sun.dart`; `2moon.dart`; `3earth.dart`). Unfortunately, this does not pass on the `lowercase_with_underscores` rule. 

I've noticed that using an underscore such as `1_sun.dart` does not have any effect. I also noticed that changing the file name to `sun1.dart` makes the warning go away.

Is this the intended behaviour?
If so, is there any way to ignore `lowercase_with_underscores` rule for these files? Adding comment `//ignore_for_file: lowercase_with_underscores` is not working

**Comment by pq** [comment]
> files that must have a number in the start of their name 

Out of curiosity why does the number need to prefix?

**Comment by tgpsantos** [comment]
> 
> 
> > files that must have a number in the start of their name
> 
> Out of curiosity why does the number need to prefix?

to get the files ordered by index number, which improves accessability. there many files and each represents one class. These classes can be as commonly referred to by their index number or by their string name

**Comment by eernstg** [comment]
Perspective one: @tgpsantos, why don't you rename those files such that there is another prefix in front of the name (like `x1sun.dart`, `x2moon.dart`, `x3earth.dart`)? I supposed that could give rise to many changes in the source (e.g., imports)?

Perspective two: @pq, why don't we just change the rule to require a slightly more forgiving variant of `lowercase_with_underscores` where digits are allowed as the first character (as well as the _n_'th character for any _n_>0)? ;-)

**Comment by tgpsantos** [comment]
@eernstg thanks for the workaround! we'll probably go with that

**Comment by pq** [comment]
Thanks for the feedback @tgpsantos and for the perspective @eernstg!

If a (currently) legal suffix like @eernstg suggested would work, that'd be preferred but we can definitely revisit the rule. (I do note that the logic is shared currently with package-naming and I can't recall if there are any legitimate reasons to disallow leading numerals there.  Not that they can't be decoupled, of course.)

Again, thanks and let me know if this works for you and if not we can re-open this issue and explore further.
