### ISSUE TITLE
lint to discourage `.new` constructor declarations?

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2904]
With [constructor tear-offs](https://github.com/dart-lang/language/blob/master/accepted/future-releases/constructor-tearoffs/feature-specification.md), there is a "new" way to define the unnamed constructor for a class.

```dart
class A {
  A.new();
}
```

It's a little surprising that this is equivalent to the shorter version:

```dart
class A {
  A();
}
```

We might consider a lint to discourage people from using this new syntax.

See also: https://github.com/dart-lang/site-www/issues/3525

**Comment by pq** [comment]
Puzzling about what such a lint would be called...  Maybe:

* `use_unnamed_constructors` (or `use_unnamed_constructors` )
* `use_implicit_unnamed_constructors` (or `implicit_unnamed_constructors`)

(See https://github.com/dart-lang/language/pull/1826 for some more useful context.)

/cc @bwilkerson @lrhn

**Comment by bwilkerson** [comment]
Will the lint only flag the use of `.new` in declarations, or will it also flag it in constructor invocations and anywhere else where it might appear but not be necessary? Seems like most people would want all these cases covered, but knowing the answer might influence the name of the lint.

**Comment by pq** [comment]
Excellent point.  Yes, I think we'd want to recommend against both declarations and invocations.

Thoughts on naming?

**Comment by pq** [comment]
Maybe something prefixed w/ "unnecesary_" (like `unnecessary_new` and `unnecessary_const`).

`unnecessary_named_unnamed_constructors` ?

(A mouthful.)

**Comment by lrhn** [comment]
Name-wise, you could just wrap it into `unnecessary_new` :grin:. 
However, since it's still new, and the dominant style might change over time, it's probably a good idea to keep it separately selectable.
How about `unnecessesary_constructor_new` or `unnecessary_new_name`

**Comment by bwilkerson** [comment]
Or `unnecessesary_constructor_name`.

**Comment by pq** [comment]
> Name-wise, you could just wrap it into unnecessary_new

That was my initial thought too but ultimately came to the same conclusion we should keep it separate.

Thanks for the name suggestions!

> Or `unnecessesary_constructor_name`.

I'm leaning towards this one myself.

**Comment by lrhn** [comment]
We could *also* add a symmetric lint, "always_use_constructor_name", and see if someone wants to use that.
Just to not bias people before we know what they really want :)
