### ISSUE TITLE
update`sort_unnamed_constructors_first` for constructor tear-offs

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#2912]
From @srawlins.

> (where to sort `.new`? alternatively, a lint to prefer unnamed vs .new?)

**Comment by pq** [comment]
Chatting w/ @scheglov @bwilkerson my sense is that alphabetical may be the least surprising (and is consistent w/ what the sort action currently does).

Also note that w/ #2904, these may be discouraged (or at least very rare) in the wild.

**Comment by bwilkerson** [comment]
Whatever order is selected, I do believe that the sort order expected by the lint should match the sort order produced by the `edit.sortMembers` protocol.

**Comment by pq** [comment]
Agreed!  Besides being (probably) least surprising, alphabetical has the added perk of being what `edit.sortMembers` currently produces.  (It also means `sort_unnamed_constructors_first` will continue to work unchanged.)

**Comment by pq** [comment]
OK.  So my thinking is we close this for now as WAI.  If this raises concerns in practice when the feature rolls out, we can revisit.

Feel free to re-open if anyone wants to continue the discussion!
