### ISSUE TITLE
Single and double quote string literal consistency

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/linter#298]
It would be nice to have a lint that enforces consistency of `'` and `"` string literal usage.

String literals in a given file should entirely use `'` or `"`, but not a mixture of both.

**GOOD**:

``` dart
void main() {
  var foo = 'Hello';
  var bar = 'World';
  print('$foo $bar');
}
```

**GOOD**:

``` dart
void main() {
  var foo = "Hello";
  var bar = "World";
  print("$foo $bar");
} 
```

**GOOD**:

An exception should be granted if you are using the inconsistent literal character to simplify the usage of characters within strings. Best explained through this example:

``` dart
void main() {
  // OK, we just used " to not have to escape \' twice!
  var foo = "Hello 'World'";
  var bar = '!';

  print('$foo $bar');
}
```

**BAD**:

``` dart
void main() {
  var foo = 'Hello';
  var bar = "World"; // LINT

  print('$foo $bar');
}
```

**Comment by pq** [comment]
I'm guessing this is consistency _within a file_?

**Comment by matanlurey** [comment]
Yes, within a file.

**Comment by kentcb** [comment]
Found this looking to enforce consistency across a team. I don't know that I agree with the per-file suggestion. I think there should be two linters, `prefer_single_quoted_strings`, and `prefer_double_quoted_strings`. That way, it's easier to enforce consistency across a code base. I agree with allowing exceptions when it's being used to simplify literals.

**Comment by pq** [comment]
Hi @kentcb.  We actually have [`prefer_single_quotes`](http://dart-lang.github.io/linter/lints/prefer_single_quotes.html), so we're half way there at least! 😄

**Comment by kentcb** [comment]
Thanks @pq! I missed that because I searched the linters for "string". It looks like it works exactly as I'd hoped. Do you know if there are plans to add `prefer_double_quotes`?

**Comment by pq** [comment]
You're welcome!  I'm not aware of any plans to add `prefer_double_quotes` as most folks seem to prefer single.  Feel free to open a feature request if it would be valuable to you.

Thanks!

**Comment by kentcb** [comment]
OK, I created #1096 for this.

**Comment by pq** [comment]
Perfect.  Thanks!

**Comment by matanlurey** [comment]
This is quite stale, there is both `prefer_single_quotes` and `prefer_double_quotes`.
