### ISSUE TITLE
Ordering import and export directives

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/linter#299]
From https://www.dartlang.org/guides/language/effective-dart/style, I won't copy and paste all of the cases here. The only pre-requisite for me is that we should also allow Bazel-style (internal) imports without linting accidentally.

**Comment by evanweible-wf** [comment]
This has been addressed by the `directives_ordering` lint rule, right?
http://dart-lang.github.io/linter/lints/directives_ordering.html

**Comment by kuhnroyal** [comment]
According to the effective-dart page `directives_ordering` should take care of this.
But due to https://github.com/dart-lang/linter/issues/1844 in currently fails in part.

**Comment by roman-petrov** [comment]
There is also [import_sorter](https://pub.dev/packages/import_sorter) package which IMHO provides a good import sorting logic.

**Comment by matanlurey** [comment]
This is stale, discussion at https://github.com/dart-lang/linter/issues/1844 SGTM.
