### ISSUE TITLE
avoid_return_types_on_setters should apply to operator[]=

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/linter#300]
`operator[]=` is a form of setter and therefore `avoid_return_types_on_setters` should apply to it too, however currently with `always_declare_return_types` the linter will demand that it has its return type declared.

/cc @pq @Hixie

**Comment by pq** [comment]
Spot on.  I'll take a look today.  Thanks!

**Comment by pq** [comment]
https://codereview.chromium.org/2302053002/

**Comment by yjbanov** [comment]
Thanks! \o/
