### ISSUE TITLE
Duplicates in this repos issue template?

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#3047]
![image](https://user-images.githubusercontent.com/17034/139143925-781645a0-f264-4bca-be3f-467c8e367abf.png)

What's the diff between a lint proposal and a lint request?

**Comment by pq** [comment]
The distinction is a little subtle but I think valuable.  A proposal is meant to be pretty formal and actionable.  I do think we want something else for more freeform ideas/requests/ruminations.

Maybe we can rename "request" to something that better communicates that.

* idea?
* discussion?

Something else?

**Comment by pq** [comment]
Closing for now.  Feel free to re-open if you need further clarification or if you have ideas for improvement!
