### ISSUE TITLE
Description for omit_local_variable_types is confusing

### ISSUE THREAD

**Issue by natebosch** [dart-lang/linter#3054]
> Usually, the types of local variables can be easily inferred, so it isn't necessary to annotate them.

https://dart-lang.github.io/linter/lints/omit_local_variable_types.html

It isn't clear to me whether this means "easily inferred by the reader" (my guess) or "easily inferred by the compiler".

In Effective Dart we frame things a little differently.

> Local variables, especially in modern code where functions tend to be small, have very little scope. Omitting the type focuses the reader’s attention on the more important name of the variable and its initialized value.

https://dart.dev/guides/language/effective-dart/design#dont-redundantly-type-annotate-initialized-local-variables

Here we don't talk about inference at all - either from the compiler or the reader. When this has come up in past discussions, I don't think the framing of the type being easy to infer by a reader has been as convincing as the framing that very often the specific type isn't very important to the reader.

**Comment by natebosch** [comment]
IMO the description from Effective Dart is more clear.

@pq @munificent - are there any concerns with using the same description in both places?

**Comment by pq** [comment]
> are there any concerns with using the same description in both places?

Not for me.  Seems like the right thing to do.

Thanks!
