### ISSUE TITLE
☂️ linter implementation for enhanced enums

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#3090]
See https://github.com/dart-lang/sdk/issues/47849 for the main tracking issue.

---

## 🛠️  existing lints

- [x] #3093 
  - [x] #3186
- [x] #3094
  - [x] #3233
- [x] #3095
  - [x] #3188 
- [x] #3092
- [x] #3205
- [x] #3096
- [x] enhanced enum support for `camel_case_types` #3091
- [x] #3195
  - [x] #3202 
- [ ] #3193
- [x] #3196
- [ ] #3194
- [x] #3197
- [x] ~#3191~
- [x] #3198
  - [x] #3203 
- [x] #3190 
- [x] #3207
- [x] #3208
- [x] #3097 
  - [x] #3187
- [x] ~#3199~
- [x] #3200
  - [x] #3204
- [x] #3201
  - [x] #3235 
- [x] #3192

## 💡 new lints

- [x] #3173

**Comment by pq** [comment]
Closing as fundamentally done w/ #3322.
