### ISSUE TITLE
`camel_case_types` should cover enums

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3091]
As per the style guide:

> Classes, **enum types**, typedefs, and type parameters should capitalize the first letter of each word (including the first word), and use no separators.

https://dart.dev/guides/language/effective-dart/style#do-name-types-using-uppercamelcase

Would be nice to have this in place in time for enhanced enums (#3090). 

---

Alternatively, we could consider a discrete lint `camel_case_enums` (in keeping with `camel_case_extensions`).

**Comment by pq** [comment]
@bwilkerson @munificent @jakemac53 @natebosch @lrhn @eernstg: any gut reactions on extending `camel_case_types ` vs. adding `camel_case_enums`?

**Comment by natebosch** [comment]
I would extend `camel_case_types`

**Comment by lrhn** [comment]
Agree. Enums are classes. They are special classes with a lot of restrictions (some of which we plan to remove) and an extra syntax for creating named instances, but they are fundamentally classes and should be named the same way.

**Comment by bwilkerson** [comment]
Agreed. Unless we have evidence that changing the rule would break too many users it would be better for users if er extended the existing lint rather than adding a new one.

**Comment by HelioStrike** [comment]
Created a PR for this as it seemed like a good first issue... Will revert PR incase I did something wrong and there's some process to be followed for contributing. Thanks! :)

**Comment by pq** [comment]
Awesome.  Since this could potentially block an internal Dart SDK roll (if there are violations to address), we'll have to do some testing before landing.  I'l look into that.

Thanks!
