### ISSUE TITLE
enhanced enums support for `unnecessary_overrides`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3097]

**Comment by scheglov** [comment]
Do you use the bleeding edge analyzer? I can run this test without a crash (it fails).
```dart
  test_X() async {
    await assertNoErrorsInCode(r'''
enum A {
  a,b,c;
  @override
  int get foo => 0;
}
''');
  }
```

**Comment by pq** [comment]
Ah, yes. sorry, should have added that.  I see a failure on bleeding edge (but no crash) too.
