### ISSUE TITLE
Documentation for avoid_void_async

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/linter#3119]
The documentation for `avoid_void_async` only mentions the use of `void` with the `async` modifier, but the lint also checks for using `void` with `async*` and `sync*`. The documentation should be expanded to cover these cases.

**Comment by parlough** [comment]
I'm curious, does the rule even need to check these cases?

Wouldn't the diagnostics [`illegal_sync_generator_return_type`](https://dart.dev/tools/diagnostic-messages#illegal_sync_generator_return_type) and [`illegal_async_generator_return_type`](https://dart.dev/tools/diagnostic-messages#illegal_async_generator_return_type) catch these issues?
