### ISSUE TITLE
no_leading_underscores_for_local_identifiers reports variables named `_`

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#3126]
**Describe the issue**

no_leading_underscores_for_local_identifiers reports variables named `_`, which I think should be allowed (perhaps only for parameters).

**To Reproduce**

```dart
try {
  // ...
} catch (_) {
  // _ is not used.
}
```

**Expected behavior**

This should be allowed. A catch clause _must_ accept 1 or 2 parameters, not 0.

**Comment by srawlins** [comment]
This is for the SDK code at HEAD today; I see that linter _appears_ to try to allow this with `void visitCatchClause(CatchClause node) { checkIdentifier(node.exceptionParameter, isJustUnderscoresOK: true);` so, hmm...

**Comment by pq** [comment]
Yeah.  This *should* be fixed w/ https://github.com/dart-lang/linter/commit/6e288d80af0b936a327e932e08b9703608d97341.

**Comment by pq** [comment]
Seems to be working for me w/ a fresh build:

```sh
☁  sdk [main] ⚡  dart --version
Dart SDK version: 2.16.0-edge.41384d7544fe870f4a4dc56160d833796db3030b (be) (Mon Jan 3 17:07:25 2022 +0000) on "macos_x64"
```

Maybe double check on your end?

**Comment by srawlins** [comment]
I just rebuilt a fresh SDK; problem is gone! Thanks!

**Comment by jamesderlin** [comment]
The fix for this fixed the specific case for `catch` clauses but did not seem to fix the issue for local identifiers named `_` in general, which is what @srawlins originally suggested.  Another example:

```dart
for (var _ in someIterable) {}
```
where I want to drain some `Iterable` (because iterating might have side-effects).

IMO a plain `_` should *always* be ignored by this lint because it's not a *leading* underscore; it *is* an underscore, and a bare underscore is usually used intentionally.

**Comment by pq** [comment]
💯 

```dart
for (var _ in someIterable) {}
```

for sure should be made OK.

I'm inclined to agree w/ the generalization too (all bare underscores) but would value other input too.

📟  @munificent?

**Comment by munificent** [comment]
> IMO a plain `_` should _always_ be ignored by this lint because it's not a _leading_ underscore; it _is_ an underscore, and a bare underscore is usually used intentionally.

+1.

Note that with the in-progress support for pattern matching, we are considering making a global change to the language that *all* variable declarations named `_` do not bind a name. This would mean that you can use `_` multiple times instead of having to do `_`, `__`, `___`, etc.

**Comment by pq** [comment]
Thanks @munificent!
