### ISSUE TITLE
Linter crashes

### ISSUE THREAD

**Issue by dskloetg** [dart-lang/linter#315]
I'm trying to use the linter but it crashes.

Task failed: GenerateLintsTask for source [google confidential]
An error occurred while linting
  Please report it at: github.com/dart-lang/linter/issues
AnalysisException: Cannot compute DART_ERRORS for [google confidential]
Caused by Unexpected exception while performing GenerateLintsTask for source [google confidential]
#0      AnalysisTask._safelyPerform (package:analyzer/task/model.dart:350)
#1      AnalysisTask.perform (package:analyzer/task/model.dart:238)
#2      AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#3      AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#4      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721)
#5      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:669)
#6      AnalysisDriver.analyze (package:linter/src/analysis.dart:139)
#7      DartLinter.lintFiles (package:linter/src/linter.dart:68)
#8      runLinter (http://localhost:39173/linter.dart:158)
#9      main (http://localhost:39173/linter.dart:18)
#10     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#11     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

Caused by The null object does not have a getter 'parameters'.

NoSuchMethodError: method not found: 'parameters'

Receiver: null
Arguments: []
#0      Object._noSuchMethod (dart:core-patch/object_patch.dart:44)
#1      Object.noSuchMethod (dart:core-patch/object_patch.dart:47)
#2      _Visitor.visitFunctionDeclaration (package:linter/src/rules/parameter_assignments.dart:72)
#3      DelegatingAstVisitor.visitFunctionDeclaration.<anonymous closure> (package:analyzer/dart/ast/visitor.dart:431)
#4      List.forEach (dart:core-patch/growable_array.dart:258)
#5      DelegatingAstVisitor.visitFunctionDeclaration (package:analyzer/dart/ast/visitor.dart:431)
#6      FunctionDeclarationImpl.accept (package:analyzer/src/dart/ast/ast.dart:5073)
#7      NodeListImpl.accept (package:analyzer/src/dart/ast/ast.dart:7688)
#8      CompilationUnitImpl.visitChildren (package:analyzer/src/dart/ast/ast.dart:2446)
#9      DelegatingAstVisitor.visitCompilationUnit (package:analyzer/dart/ast/visitor.dart:252)
#10     CompilationUnitImpl.accept (package:analyzer/src/dart/ast/ast.dart:2439)
#11     GenerateLintsTask.internalPerform (package:analyzer/src/task/dart.dart:3259)
#12     AnalysisTask._safelyPerform (package:analyzer/task/model.dart:338)
#13     AnalysisTask.perform (package:analyzer/task/model.dart:238)
#14     AnalysisDriver.performWorkItem (package:analyzer/src/task/driver.dart:284)
#15     AnalysisDriver.computeResult (package:analyzer/src/task/driver.dart:109)
#16     AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:721)
#17     AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:669)
#18     AnalysisDriver.analyze (package:linter/src/analysis.dart:139)
#19     DartLinter.lintFiles (package:linter/src/linter.dart:68)
#20     runLinter (http://localhost:39173/linter.dart:158)
#21     main (http://localhost:39173/linter.dart:18)
#22     _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#23     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

#0      AnalysisContextImpl.computeResult (package:analyzer/src/context/context.dart:726)
#1      AnalysisContextImpl.computeErrors (package:analyzer/src/context/context.dart:669)
#2      AnalysisDriver.analyze (package:linter/src/analysis.dart:139)
#3      DartLinter.lintFiles (package:linter/src/linter.dart:68)
#4      runLinter (http://localhost:39173/linter.dart:158)
#5      main (http://localhost:39173/linter.dart:18)
#6      _startIsolate.<anonymous closure> (dart:isolate-patch/isolate_patch.dart:259)
#7      _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:148)

**Comment by zoechi** [comment]
How are you using it? Just by adding an `.analysis_options` file?

**Comment by dskloetg** [comment]
`$ pub global run linter some/google/path`

**Comment by bwilkerson** [comment]
https://codereview.chromium.org/2424743004/

**Comment by alexeieleusis** [comment]
thank you Brian!
