### ISSUE TITLE
enhanced enums support for `prefer_constructors_over_static_methods`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3191]

**Comment by srawlins** [comment]
I think we may need a description here. I'm trying to think of a case where an enum is created in a static method, but should have been a constructor...

**Comment by bwilkerson** [comment]
@pq

**Comment by pq** [comment]
I'm trying to remember what I was thinking here.  It's possible I didn't understand that [generative enum constructors can only be used as targets of redirection](https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=invalid_reference_to_generative_enum_constructor#invalid_reference_to_generative_enum_constructor) making the common cases for this impossible with enums.  I'll close this for now and we can reopen if anyone can come up with some real motivation.

Thanks!
