### ISSUE TITLE
Can I write lint definitions in a DSL (or Dart) that the linter understands?

### ISSUE THREAD

**Issue by sethladd** [dart-lang/linter#32]
OK: writing lint rules in english and then implementing the rule as Dart (see https://github.com/dart-lang/linter/blob/master/lib/src/rules/library_prefixes.dart)

AMAZING: writing the rules in a single way (a DSL? Dart code?)

**Comment by pq** [comment]
Would *love* to pursue this but not on the current roadmap.  Closing for now.... 😢
