### ISSUE TITLE
Release new version

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#327]
That includes https://github.com/dart-lang/linter/commit/aca98436fa1223b3824ea4f5e476bae52daffab2 which would allow the rule to be added to our CI and IDE analysis optinos file.

**Comment by pq** [comment]
Sounds good.

@bwilkerson : should I change the analyzer dependency bounds at this point too?

**Comment by bwilkerson** [comment]
If linter works with later versions of analyzer than are currently allowed, or if it no longer works with earlier versions, then yes. But you know that, so I'm probably not understanding the question. :-)

**Comment by pq** [comment]
The question was a little vague maybe.  I just recall mails about version changes and I wonder if there's anything to consider here.  But maybe not!

**Comment by bwilkerson** [comment]
No, we haven't released the new version of analyzer yet.

**Comment by pq** [comment]
Linter published.

@alexeieleusis : I'm guessing you want this updated version pulled into SDK DEPS?

**Comment by alexeieleusis** [comment]
Thank you Phil! I can wait for the public SDK, it is in the internal one where I was unable to enable the lint. But also I can wait, just wanted to make sure the fix will make it in the next release.
