### ISSUE TITLE
`unknown` should be `log` to be identical to the GOOD example

### ISSUE THREAD

**Issue by Cat-sushi** [dart-lang/linter#3290]
`static const unknown = LogPriority._unknown('Log');` in the BAD example should be 
`static const log = LogPriority._unknown('Log');` to be identical to the GOOD example.

https://github.com/dart-lang/linter/blob/ed26087ae1b54fb8c532fcda618e6bf08827e315/lib/src/rules/use_enums.dart#L37

**Comment by pq** [comment]
Great catch. Thank you.  In fact, looking closer I see a few other issues here to fix here too.

👍
