### ISSUE TITLE
Complaints about this library declaration which seems valid to me.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#33]
`library bwu_server.shared.datastore.some_file;`

> DO name libraries and source files using lowercase_with_underscores. (.../my_package/lib/src/shared/datastore/some_file.dart, line 1, col 1)

Are you interested in such bug reports already?

**Comment by pq** [comment]
Cool.  Absolutely yes, @zoechi, bug reports and feature requests most welcome. 

Thanks!

(Lint in question: #18.)

**Comment by pq** [comment]
Should be fixed.  Please file any other issues you catch.

Thanks!

**Comment by zoechi** [comment]
Great! It would be even more fun to test/use if there were any way to disable checks like `linter --ignore=3 17 25 `

**Comment by pq** [comment]
Agreed! I think we need to hammer this out sooner than later. Feel free to chime in over on #7 if you have thoughts.

Again, thanks for the report. Keep 'em coming!
