### ISSUE TITLE
`depend_on_referenced_packages` triggers falsely on virtual `flutter_gen` package

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#3308]
When a flutter developer adds internationalization to their app as explained in https://docs.flutter.dev/development/accessibility-and-localization/internationalization#adding-your-own-localized-messages it generates a virtual `flutter_gen` package that the developer has to import in their app (see examples on the linked page). That package does not show up in the `pubspec.yaml`, but the `depend_on_referenced_packages` complains about it missing in there.

The `flutter_gen` package is made available by a rewrite of the package config file. It's a little suspect, but that's what we have right now. Long-term we can hopefully replace this with a macro or something.

In the short-term we need to fix the lint to not complain about this non-existent dependency.

**Comment by goderbauer** [comment]
@mit-mit @pq @srawlins @jonahwilliams

This is currently blocking for rolling the new lints version 2.0 into Flutter. We either need to exclude this lint from the package or come up with a quick fix. Outside of hardcoding an exception into the lint rule itself, I don't see many options, though...

**Comment by jakemac53** [comment]
😞 ya this package causes issues for build_runner and I think pub itself as well had some problems with it modifying the package config. We really should change how it works, but in the meantime a hack in the lint can suffice.

**Comment by pq** [comment]
OK.  I've got a "fix" out in #3309.  I can roll this with some fixes for `use_super_parameters` (#3306) into a Monday release.

**Comment by goderbauer** [comment]
Thank you!

**Comment by bwilkerson** [comment]
@goderbauer Is there a tracking issue to resolve the question of whether it's appropriate to special-case `flutter_gen`? The issue has come up again (https://github.com/Dart-Code/Dart-Code/issues/3948). It's expensive for the tooling to have to handle special cases like this, but I don't know whether this is a special case that we can get avoid.

**Comment by goderbauer** [comment]
@bwilkerson I filed https://github.com/flutter/flutter/issues/102983 to start a discussion for that.

**Comment by pq** [comment]
Excellent.  Thanks @goderbauer!
