### ISSUE TITLE
`noop_primitive_operations` enhancements

### ISSUE THREAD

**Issue by asashour** [dart-lang/linter#3334]
Update:

as communicated below:

>Would it make sense to expand it to covering additional cases where a non-String will automatically be converted, such as in string interpolations ('aaa ${x.toString()} zzz') and asserts, or in SDK APIs that take any object and convert it to a string using toString, such as StringBuffer.write.

~~## unnecessary_toString~~

~~## Description~~

~~Avoid calling `toString` on strings.~~

~~## Details~~

~~Avoid calling `toString` on strings.  The target is already a `String`.~~

~~## Kind~~

~~Unneeded code.~~

~~## Good Examples ~~

~~String s1 = '';~~
~~String s2 = s1;~~

~~## Bad Examples~~

~~String s1 = '';~~
~~String s2 = s1.toString();~~

~~## Discussion~~

~~`avoid_type_to_string` is related.~~

**Comment by bwilkerson** [comment]
How often does this occur in real code?

Would it make sense to expand it to covering additional cases where a non-`String` will automatically be converted, such as in string interpolations (`'aaa ${x.toString()} zzz'`) and asserts, or in SDK APIs that take any object and convert it to a string using `toString`, such as `StringBuffer.write`.

**Comment by pq** [comment]
[`noop_primitive_operations`](https://dart-lang.github.io/linter/lints/noop_primitive_operations.html) might fit this bill already?

**Comment by asashour** [comment]
> [`noop_primitive_operations`](https://dart-lang.github.io/linter/lints/noop_primitive_operations.html) might fit this bill already?

Indeed, this is it.

> ... to expand it to covering additional cases ..

I guess yes, why not. The more value is added to the user, the better.

`'aaa ${x.toString()} zzz'` is already covered. Not sure about the rest.

**Comment by a14n** [comment]
As #3379 has been merged can we close this issue?
