### ISSUE TITLE
proposal: deprecate `invariant_booleans`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3336]
Despite it's popularity and value-add, `invariant_booleans` is plagued w/ so many false-positives that I think we should seriously consider deprecating it and potentially removing it.

Comments and reactions most welcome!

🍿

**Comment by srawlins** [comment]
+1 to remove it soon-ish

**Comment by asashour** [comment]
I obviously came very late to the party, but I believe the functionality is needed, whether by fixing the current lint or introducing a new one.

I see it is marked as `experimental`, which removes the embarrassment, that something is not good enough.

Why it is being abandoned? The thing which I am most afraid of, is that Dart languages itself prevents solid implementation of the lint (e.g. static-analysis vs run-time type), but other reasons could possibly be resolved, I assume.

**Comment by srawlins** [comment]
I like the idea of the lint, so I might support a new attempt.

But the current rule has many bugs, must still be maintained by the team, and is not high enough priority for anyone to have re-written. Right now we're just putting time and effort into dead code.

**Comment by bwilkerson** [comment]
If anyone has time and interest to work on this, I think the best path forward is to write a design proposal for the desired behavior. The proposal would need to be explicit about the proposed algorithm: what information the analysis can definitively know for various kinds of nodes, how the flow analysis would be implemented, etc. It would need to be fairly formal so that we could more easily see whether it's accurate.

I think the problem with the current implementation is that it's too ad hoc, and that has led to many of the bugs in the last.

**Comment by pq** [comment]
> If anyone has time and interest to work on this, I think the best path forward is to write a design proposal for the desired behavior.

💯 this.

> I think the problem with the current implementation is that it's too ad hoc,

Yes.  In hindsight I think we do some significant tidying up.  My gut says too that a good approach might be to scale the promise back a bit.  A good thought experiment anyway would be to start with identifying a subset of the current cases that we feel confident could be reported w/o false positives and explore growing out from there.

Thanks for the continued interest @asashour!

**Comment by srawlins** [comment]
If I sent a PR that deletes invariant_booleans, would it be accepted?

Or is that a breaking change, and the rule needs to be deprecated first?

**Comment by pq** [comment]
I think we should probably start with deprecation and an update to the docs that makes it clear that the lint is slated to be removed.  (Maybe w/ a back-pointer to this issue for any feedback.)
