### ISSUE TITLE
lint rule which force some async functions called with await

### ISSUE THREAD

**Issue by dikinova** [dart-lang/linter#3347]
I write some async functions, and I know definitely these functions must be called with await keyword. 
So, I hope there was a lint rule, suppose named as await_call_forced, which should disallow those functions be called asynchronously when both conditions are satisfied:
	(1) async function returns Future (or FutureOr etc)
	(2) function marked with @AwaitCallForced annotation

**Comment by pq** [comment]
[`unawaited_futures`](https://dart-lang.github.io/linter/lints/unawaited_futures.html) may get you close?

**Comment by dikinova** [comment]
thanks, it is just fine. I didn't find this lint rule, it's  my problem.
