### ISSUE TITLE
unnecessary_await_in_return suggestion

### ISSUE THREAD

**Issue by bernaferrari** [dart-lang/linter#3373]
I always forget to remove 'async' after the 'await' is gone and there is no lint warning for that. Could unnecessary_await_in_return see that?

```
  // LINT WARNING
  Future<void> testFunction1() async => await Future.delayed(Duration(seconds: 1), () {
    print('testFunction');
  });

  // NO LINT WARNING, but async is unnecessary
  Future<void> testFunction3() async => Future.delayed(Duration(seconds: 1), () {
    print('testFunction');
  });
```

**Comment by srawlins** [comment]
I think you might be suggesting a new lint rule (the example you show has nothing to do with `await`). Something like "unnecessary async" which might, at a minimum, be applied to arrow-functions (`Future<void> f() async => someFuture;`) which return a Future.

It could apply to all functions, but the body-checking could be complex. Something like:

* Body has no `awaits`
* For functions typed `Future<T>` where `T` is not `void`, `dynamic`, or `Never`, every return statement returns a value that is of type `Future<T>` (none are of type `T`)

**Comment by a14n** [comment]
Dup of #1257
