### ISSUE TITLE
Lint for outdated pubspec dependency constraints

### ISSUE THREAD

**Issue by seaneagan** [dart-lang/linter#34]
One should `CONSIDER keeping your dependencies up-to-date` to:
- get bug fixes.
- avoid dependency resolution conflicts with other packages that have updated.
- use new features and stop using deprecated features.

This could be a separate tool, e.g. see https://david-dm.org/, but it would be quite similar in purpose and implementation to the other pub lints e.g. #29.  For example, many pub lints would be reported on a `YamlNode` from the pubspec.  And a quick fix would edit that node.

[den](https://github.com/seaneagan/den) already has functionality to detect and fix outdated dependencies via its CLI, and a [dart API](https://github.com/seaneagan/den/issues/5) will be available soon.

**Comment by pq** [comment]
@seaneagan: I love the idea of a user notification that deps are out of date.   Playing with it as a lint seems reasonable to me.  (And certainly expedient.)  If it makes sense elsewhere we can certainly migrate.

Keep me posted on the dart API. In the meantime, I'm most of the way done with the basic parser/visitor bits to plumb in pubspec lints.  I'll ping you when it lands and we can start playing.

Cheers!

**Comment by pq** [comment]
I think this is now more or less handled by the [`pub outdated`](https://dart.dev/tools/pub/cmd/pub-outdated) command and any improved UX should probably tie it into something like an IntelliJ "inspection" (rather than a lint).

/fyi @jwren @alexander-doroshko
