### ISSUE TITLE
Avoid using private types in public APIs trigger on Stful  in flutter

### ISSUE THREAD

**Issue by nikhilbadyal** [dart-lang/linter#3406]
**Describe the issue**
[Closed issue](https://github.com/Dart-Code/Dart-Code/issues/3827)

`Avoid using private types in public APIs`
Above lint should not trigger on stful in flutter.

**Example**
[See this Github Run in Flutter Analyzer step](https://github.com/nikhilbadyal/keepnotes/runs/6431420644?check_suite_focus=true)

Picking up the first location in code. Linter is issuing warning on stful  [See here](https://github.com/nikhilbadyal/keepnotes/blob/8cd8cbf9c14d61aee73bbc2d6b9e5a1006752294/lib/screen/edit/components/bottom_bar_options.dart#L16).

This is back in 
*flutter 3.0,flutter_lint 2.1* and it used `lints: ^2.0.0` version.

Please fix this as soon as possible. It is causing builds to fail. I have git-hook on Flutter analyzer so I'm not even able to commit my code.

**Comment by bwilkerson** [comment]
As a short term work around, would you be able to change the declaration of `createState` to return `State<BottomBarOptions>` rather than `_BottomBarOptionsState`?

**Comment by a14n** [comment]
I don't think the lint should be changed. What @goderbauer [said](https://github.com/flutter/flutter-intellij/issues/5962#issue-1132947594):

> This is violating the [library_private_types_in_public_api](https://dart-lang.github.io/linter/lints/library_private_types_in_public_api.html) lint and bad style because among other things it exposes the private _FooState type in the API docs. Private types shouldn't be exposed in public API.

**Comment by andynvt** [comment]
But is there any way to pass this rule? Because of the app structure

**Comment by srawlins** [comment]
Brian's [suggestion](https://github.com/dart-lang/linter/issues/3406#issuecomment-1127776046) should work.
