### ISSUE TITLE
Add lint for unused "// ignore" comments

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/linter#347]
The linter should provide a lint that tags unused "// ignore" comments. This could help with cleaning up the code from ignores that are obsolete or misplaced.

/cc @alexeieleusis

**Comment by alexeieleusis** [comment]
I am happy to work on this, though I don't know if it should be fixed in the analyzer itself.

@bwilkerson any hints?

**Comment by bwilkerson** [comment]
Given that ignore comments are used for more than disabling lints, and given their similarity to dead code hints, I'd probably make this a hint. If you want more specific direction for how to do this, let's talk off-line.

**Comment by pq** [comment]
I started looking at this a million years ago and bailed due to performance implications.

Some relevant conversation here:

https://codereview.chromium.org/1767723002/

**Comment by bwilkerson** [comment]
This cannot be done as a lint, so I am closing this in favor of https://github.com/dart-lang/sdk/issues/35234.

**Comment by zoechi** [comment]
@bwilkerson you didn't close ;-)
