### ISSUE TITLE
lowercase_with_underscore should allow prefixes generated by code_builder

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#348]
![image](https://cloud.githubusercontent.com/assets/405837/20789595/4eba6d16-b7b5-11e6-8748-457b9b858857.png)

**Comment by natebosch** [comment]
In theory this should be resolved. Filed also as https://github.com/dart-lang/linter/issues/684 and fixed in https://github.com/dart-lang/linter/pull/770 but I'm still seeing the issue

**Comment by natebosch** [comment]
Closing in favor of https://github.com/dart-lang/linter/issues/684 since that issue has a longer discussion. I reopened it to investigate if we've regressed on this.
