### ISSUE TITLE
integration_tests depend on a 'packages' file

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#3485]
**Describe the issue**

The integration tests seem to depend on a `--packages` flag, which is now failing with analyzer 4.2.0.

See CI failures here: https://github.com/dart-lang/linter/runs/7123357781?check_suite_focus=true

Reproduce with `dart run test test/integration_test.dart`.

**Comment by srawlins** [comment]
@scheglov I'm sort of guessing here, and I know work was done recently to remove some legacy support for 'packages' files. Can you confirm this landed recently, and may only be showing up in 4.2.0?

**Comment by srawlins** [comment]
Looks like linter sets 'packages' files via analyzer's `DriverOptions.packageConfigPath`.

**Comment by srawlins** [comment]
Seems fixable by adding several `.dart_tool/package_config.json` files.

**Comment by scheglov** [comment]
Yes, we removed support for `.packages` just before `analyzer 4.2.0`.
