### ISSUE TITLE
linter rule for using  `=` or ':` for default values for optional named parameters

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#351]
Recently support for `=` in
```dart
foo({String p = 'xxx'}) { ... }
```
was added in addition to
```dart
foo({String p : 'xxx'}) { ... }
```
To support consistency within a project linter rules for one or the other style would be great.

**Comment by a14n** [comment]
@munificent any recommendation regarding the [style guide](https://www.dartlang.org/guides/language/effective-dart/style) ?

**Comment by munificent** [comment]
I think the style guide should flatly state to use `=` for all optional and named parameters. There's no reason to use `:` anymore. I'll make a note to try to put that in there.

**Comment by a14n** [comment]
Thanks! I will add a lint to prefer `=` over `:`.

**Comment by munificent** [comment]
Thank you!
