### ISSUE TITLE
`public_member_api_docs` causes body of extension to be underlined

### ISSUE THREAD

**Issue by Pante** [dart-lang/linter#3525]
**Describe the issue**
Not documenting an extension causes the body of a extension to be underlined as well. This is inconsistent with how only the name of classes and mixins are underlined when the lint is applied to those types.

![duality](https://user-images.githubusercontent.com/9427324/178898813-3036ef28-3c58-4046-96d2-d37435e1af56.png)

**Expected behavior**
Only the extension name should be underlined.

**Comment by pq** [comment]
💯 

I see this issue here and will fix it up.  Thanks for the report!

**Comment by Pante** [comment]
I just realized that mixins have the same issue in Dart 2.18.6 too contrary to what I mentioned. Should I file a separate issue for it?

![mixins](https://user-images.githubusercontent.com/9427324/211542059-f2d634f1-4cd4-461e-8296-dae9cf350541.png)

**Comment by pq** [comment]
That would be great.  Thanks @Pante!
