### ISSUE TITLE
`flutter_style_todos` not covered all TODOs

### ISSUE THREAD

**Issue by AlexV525** [dart-lang/linter#3616]
**Describe the issue**

We want to force all recognizable TODOs to follow the `flutter_style_todos` in our projects, but only uppercase `TODO` can be applied, they are all recognized by the editor.

![image](https://user-images.githubusercontent.com/15884415/186821922-ed880613-824a-420e-90f4-916bfe3cf6ef.png)

```dart
// TODO something <- Worked
// Todo something <- Not working
// todo something <- Not working
```

It could be checked with a lowercase string.

**Comment by AlexV525** [comment]
cc @a14n and @pq would like to consult your opinion

**Comment by bwilkerson** [comment]
The rest of the tooling currently recognizes exactly four case-sensitive markers: 'TODO', 'FIXME', 'HACK', and 'UNDONE'. It does not recognize variants of these.

Whether we should make these case insensitive is an open question, but I think it's important that all of the features use the same convention, so I would not approve of changing the lint without changing the rest of the tooling to match.

**Comment by AlexV525** [comment]
> The rest of the tooling currently recognizes exactly four case-sensitive markers: 'TODO', 'FIXME', 'HACK', and 'UNDONE'. It does not recognize variants of these.

Thanks for the coverage. This is based on what I saw in the editor. I'm glad to submit more commits if we can turn all of them into non-case sensitive.

**Comment by AlexV525** [comment]
> I would not approve of changing the lint without changing the rest of the tooling to match.

If I get it right, these codes recognition is backed by [`todo_codes.dart`](https://github.com/dart-lang/sdk/blob/d40f06ee2ac4ea9ddfdfd4d205d1e39ccefb20a9/pkg/analyzer/lib/src/dart/error/todo_codes.dart#L42), and we need the regex to become not case sensitive too. Is that correct?

**Comment by bwilkerson** [comment]
If we decide to allow non-caps version of these markers, then yes, that's the only other place I know of that would need to be changed. But I'd like to see more feedback from the rest of the team before deciding whether we want to change the behavior. In particular, I don't know whether the current limitation was intentional, and if it was what the motivation was.

@goderbauer

**Comment by a14n** [comment]
This lint was created to enforce the style described at https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo#comments. I think only uppercase TODO is accepted.

**Comment by bwilkerson** [comment]
To quote:

> TODOs should include the string TODO in all caps

**Comment by goderbauer** [comment]
For Flutter, we only want to accept TODO in all upper case, as stated in the guide. 

What is this issue actually asking for? Is it asking to flag something like "Todo(foo): bla" as wrong to remind people to use "TODO(foo): bla"? I think that would be an acceptable improvement.

Or is it asking to mark "Todo(foo): bla" as acceptable? That would not be acceptable.

**Comment by AlexV525** [comment]
> What is this issue actually asking for?

As I stated:

> We want to force all recognizable TODOs to follow the flutter_style_todos in our projects, but only uppercase TODO can be applied, they are all recognized by the editor.

> Is it asking to flag something like "Todo(foo): bla" as wrong to remind people to use "TODO(foo): bla"? I think that would be an acceptable improvement.

@goderbauer Indeed. See the image below, "TODO"s in other caps are all recognized by the editor (at least in IDEA), but only an uppercased "TODO" has applied to the rules.

![image](https://user-images.githubusercontent.com/15884415/187326717-fe5971da-5723-4d8a-a6f0-74044a3d5d57.png)

So one day our teammate wrote `// todo something` and escaped from this rule because
https://github.com/dart-lang/linter/blob/0e52f162e61f937e1ea034115bd1f5270ba4f5ad/lib/src/rules/flutter_style_todos.dart#L47
only `TODO` can be recognized.

**Comment by bwilkerson** [comment]
If the goal is to identify TODO-like comments, then I don't have any problem with the lint using a broader definition of 'todo' than the rest of the tools.

**Comment by AlexV525** [comment]
> If the goal is to identify TODO-like comments, then I don't have any problem with the lint using a broader definition of 'todo' than the rest of the tools.

Yes, it's my intention. With the PR the rule can recognize "TODO", "todo", "Todo", etc. And make them obey the flutter-style todos. Is "I don't have any problem" means my intention is acceptable?

**Comment by bwilkerson** [comment]
Yes.

**Comment by pq** [comment]
> If the goal is to identify TODO-like comments, then I don't have any problem with the lint using a broader definition of 'todo' than the rest of the tools.

Me neither.

The sense I got from @goderbauer is that we don't want to _encourage_ non ALL-CAPS todos but **rejecting** those is likely another lint.

**Comment by bwilkerson** [comment]
> ... we don't want to encourage non ALL-CAPS todos but __rejecting__ those is likely another lint.

I don't think it would be inappropriate for `flutter_style_todos` to reject those. It seems to me that using all-caps is part of following Flutter's guidelines.

**Comment by goderbauer** [comment]
> It seems to me that using all-caps is part of following Flutter's guidelines.

That is correct. I also agree that it would be appropriate for `flutter_style_todos` to reject anything that isn't all-caps.

**Comment by goderbauer** [comment]
(would be interesting to run this improved line through flutter/flutter to see if we have any violations and whether the lint was correct in flagging them)

**Comment by AlexV525** [comment]
> (would be interesting to run this improved line through flutter/flutter to see if we have any violations and whether the lint was correct in flagging them)

Yesterday I've checked with flutter/packages/flutter and all TODOs are well-formatted. 😄 I can follow up if other packages are facing this.

**Comment by pq** [comment]
@AlexV525: it sounds like @goderbauer's proposal is to flag all non ALL-CAPS todos as violating this lint (rather than accepting them as in your current implementation).  Does that sound right?

**Comment by AlexV525** [comment]
😂 I'm coufused now. I thought we have already have some agreements that the rule should "accept" non-all-caps's visitor and warns if they don't match the rule. Can you guys indicates by examples? Like multiple cases that the rule should raise warnings? Or something else maybe.

**Comment by pq** [comment]
> 😂 I'm coufused now. 

😄 

If I understand @goderbauer correctly, I think the following should be _disallowed_ by this lint:

**BAD**

```dart
// todo(username): message.
// ToDo(username): message.
// Todo(username): message.
```

And really only ALL-CAPS should be accepted:

**GOOD:**
```dart
// TODO(username): message.
// TODO(username): message, https://URL-to-issue.
```

**Comment by bwilkerson** [comment]
FWIW, I suspect that the confusion might be the word "accepted". The rule should treat all case-variants of "TODO" as comments to be linted, and should produce a diagnostic if the comment has any variant other than "TODO" or any of the problems it was previously generating a diagnostic for.

**Comment by AlexV525** [comment]
> **BAD**
> 
> ```dart
> // todo(username): message.
> // ToDo(username): message.
> // Todo(username): message.
> ```

These should raise warnings in the PR. I can add more test cases tomorrow. The incoming expression now ignores cases, but the expecting expression remains.

**Comment by AlexV525** [comment]
Just added more test cases. Notice that the original functionality is not broken.

```dart
// TODO something
// Todo something
// todo something
// TODO(somebody) something
// TODO: something
// Todo(somebody): something
// todo(somebody): something
// ToDo(somebody): something
// TODO(somebody): something
```

All above should raise warnings.

**Comment by pq** [comment]
<img width="657" alt="image" src="https://user-images.githubusercontent.com/67586/190704366-6134cd41-6a6e-466b-b22d-04bec96bdfc5.png">

💎
