### ISSUE TITLE
Lint to prefer `isEmpty`.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#363]
We have `prefer_is_not_empty` but we should also check for chances to use `isEmpty`.  IOW: `list.isEmpty` should be preferred over `list.length == 0`.

More context in the conversation here: https://github.com/flutter/flutter/pull/7207.

**Comment by a14n** [comment]
related to #353

**Comment by pq** [comment]
@a14n 👍  Yes, thanks!

**Comment by pq** [comment]
Implemented w/ https://github.com/dart-lang/linter/pull/353/commits/451b0808bfec5adf386e8626a6e74ccecd4a8777.
