### ISSUE TITLE
extend `constant_identifier_names`  to include record expressions

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3630]

**Comment by bwilkerson** [comment]
I'm not sure what you mean by "record declarations". An example would probably help.

**Comment by pq** [comment]
Ah, maybe I mean record "expressions".

I was thinking something like:

```dart

const r = (x: 1); //OK
const R = (x: 1); //LINT
```

**Comment by bwilkerson** [comment]
The initializers are record literals. I would expect that the lint wouldn't depend on the kind of expression on the right-hand side, so there shouldn't be anything to do here.

**Comment by pq** [comment]
Great!  Well that'll be easy.  😄  I'll go ahead and just add a test.

Thanks!
