### ISSUE TITLE
consider extending `avoid_annotating_with_dynamic` to include record fields

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3649]

**Comment by pq** [comment]
recordFields can only have identifiers so this is unnecessary.

```
literal      ::= record
               | // Existing literal productions...
record       ::= 'const'? '(' recordField ( ',' recordField )* ','? ')'
recordField  ::= (identifier ':' )? expression
```

**Comment by bwilkerson** [comment]
While it's true that record _literals_ don't have type annotations, record _types_ (see `recordType` in the grammar) do have type annotations on the fields, and it seems reasonable for this lint to be extended to cover those cases. Consider, for example
```
(int, dynamic) f() => throw '';
```
where the use of `dynamic` is likely to be suboptimal.

**Comment by srawlins** [comment]
The lint description is:

> AVOID annotating with dynamic when not required.

I don't know how you could write a record type which has a field typed `dynamic` without writing `dynamic`. I don't think there is anything to do here.

**Comment by bwilkerson** [comment]
Misremembered the semantics of the lint, but you're right, there's nothing to do here.
