### ISSUE TITLE
Lint Request: `sort_exports`

### ISSUE THREAD

**Issue by Pante** [dart-lang/linter#3656]
**Describe the rule you'd like to see implemented**
It will be nice if there is a rule to sort exports alphabetically similar to [sort_pub_dependencies](https://dart-lang.github.io/linter/lints/sort_pub_dependencies.html). In my opinion, it'll be a nice QOL improvement for library maintainers. 

I also believe it will compliment [combinators_ordering](https://dart-lang.github.io/linter/lints/combinators_ordering.html) nicely.

**Examples**

Bad:
```dart
export 'b.dart';
export 'a.dart';
```

Good: 
```dart
export 'a.dart';
export 'b.dart';
```

**Comment by pq** [comment]
See also https://github.com/dart-lang/linter/issues/2367.

**Comment by srawlins** [comment]
export ordering is covered by [directives_ordering](https://dart-lang.github.io/linter/lints/directives_ordering.html).

**Comment by Pante** [comment]
Just curious, is it possible to configure/disable part of the lint, specifically the part on alphabetically ordered imports? Also from what I'm reading in the rule's description, is it recommended to use relative imports for files in the same project?

**Comment by srawlins** [comment]
> Just curious, is it possible to configure/disable part of the lint, specifically the part on alphabetically ordered imports? 

It is not. The rule just enforces the Effective Dart guidance.

> Also from what I'm reading in the rule's description, is it recommended to use relative imports for files in the same project?

I don't think the `directives_ordering` rule concerns itself with that. Effective Dart might have guidance. If it does not, there is no specific recommendation.

**Comment by Pante** [comment]
Ah fair enough, I assumed that Effective Dart was implying that imports should be broken down into separate sections like `<dart imports> <other packages> <same package>`. Using `directives_ordering`, if the project uses package imports for files in the same package, `<other packages>` and `<same package>` will be merged together in alphabetical order. I guess that led to my confusion.
