### ISSUE TITLE
document that `no_duplicate_case_values` is a no-op in Dart 3.0+

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3674]
https://github.com/dart-lang/language/blob/master/working/0546-patterns/patterns-feature-specification.md#switch-expression

**Comment by pq** [comment]
If I understand the [exhaustiveness proposal](https://github.com/dart-lang/language/blob/master/working/0546-patterns/exhaustiveness.md) right, unreachable cases will be treated as **errors** so this lint should _not fire_ and there should be nothing to do here.

**Comment by pq** [comment]
@munificent: is this right?

**Comment by srawlins** [comment]
The `no_duplicate_case_values` example text has [this test case](https://github.com/dart-lang/linter/blob/main/test_data/rules/no_duplicate_case_values.dart#L28):

```dart
  const String A = 'a';
  String v = 'aa';

  switch (v) {
    case 'aa':  // OK
    case 'bb':  // OK
    case A + A: // LINT
    case 'bb':  // LINT
    case A + 'b': // OK
    default:
  }
```

The exhaustiveness spec talks about [**literal or constant matcher**](https://github.com/dart-lang/language/blob/master/working/0546-patterns/exhaustiveness.md#lifting-types-and-patterns-to-spaces):

> We lift other constants to an extract pattern whose type is a synthesized subtype of the constant's type based on the constant's **identity**.

> This means you don't get exhaustiveness checking for constants, but do get reachability checking:

  ```
  String s = ...
  switch (s) {
    case 'a string': ...
    case 'a string': ...
  }
  ```

> Here, there is an unreachable error on the second case since it matches the same string constant. Also the switch has a non-exhaustive error since it doesn't match the entire String type.

`no_duplicate_case_values` works by evaluating case expressions as constants, and then putting them in a Map and checking whether a case value is already in the Map. This may not be the same as **identity**... I'm not sure...

Anyhow, even if there is a difference, maybe we can claim its not interesting.

**Comment by lrhn** [comment]
Another thing to worry about with generalized pattern matching: Cases also get `when` clauses which can change the behavior of the `case`.
Say:
```dart
switch (e) {
  case 1 when random.nextBool():  print("1/1");
  case 1: print("1/2");
}
```
which is a kind-of silly way to randomly select between two cases, but it's allowed.

Safest aproach is probably to not apply this lint to any `case` with a `when` clause. (Such a `case` would probably also be ignored for exhaustiveness checking.)

**Comment by pq** [comment]
As implemented, this lint will not fire on `SwitchPatternCase`s so it won't report anything on 3.0 ASTs.  (It will continue to work for libraries that are opted back though.)  We should update the docs to make this clear.
