### ISSUE TITLE
proposal: Change `avoid_multiple_declarations_per_line` to ignore for-loop initializers.

### ISSUE THREAD

**Issue by renancaraujo** [dart-lang/linter#3690]
## Description

`avoid_multiple_declarations_per_line` should ignore usages in for-loop initializers:

```dart
for (var i = 0.0, index = 0;
  i <= UnicornEatingHabits.poundsOfPopocornADay;
  i += 0.3, index++) {...}
```

## Details

I love this rule. But while it prevents people from writing unnecessarily unintuitive code, it hurts one place that is unavoidable: For loops with multiple initializers. 

## Kind

Add exception to a existing rule.

## Good Examples 

This example is real code from an application I wrote:

```dart
for (var i = 0.0, index = 0; // <- linter shouldn't scream here
  i <= UnicornEatingHabits.poundsOfPopocornADay;
  i += 0.3, index++) {
     ///  yay, we got index! and something else...
 }
``` 

## Bad Examples

The same as today: 

```dart
String? foo, bar, baz; // <- so unnecessary, right?
```

## Discussion

Especially because iterating lambadas on dart (ex: `.forEach` or `.map`) don't usually provide an index parameter, as an alternative I find really clear to add an "index" variable in loops that rely on different progressions than (inteteger)++. In this way we still get an index in every iteration block. 

### Prior art:

The `eslint` equivalent, `one-var`, has an exception for `for` loop initializers. 
See [here](https://eslint.org/docs/latest/rules/one-var): 

> declarations with multiple variables are allowed in for-loop initializers

### Discussion checklist

- [x] List any existing rules this proposal modifies, complements, overlaps or conflicts with.
- [x] List any relevant issues (reported here, the [SDK Tracker], or elsewhere).
- [x] If there's any prior art (e.g., in other linters), please add references here.
- [x] If this proposal corresponds to [Effective Dart] or [Flutter Style Guide] advice, please call it out. (If there isn’t any corresponding advice, should there be?)
- [x] If this proposal is motivated by real-world examples, please provide as many details as you can.  Demonstrating potential impact is _especially valuable_.

[Writing Lints]: https://github.com/dart-lang/linter/blob/main/doc/writing-lints.md
[Effective Dart]: https://dart.dev/guides/language/effective-dart
[Flutter Style Guide]: https://github.com/flutter/flutter/wiki/Style-guide-for-Flutter-repo
[SDK Tracker]: https://github.com/dart-lang/sdk/issues

**Comment by renancaraujo** [comment]
[Here is another example ](https://wiki.sei.cmu.edu/confluence/display/c/DCL04-C.+Do+not+declare+more+than+one+variable+per+declaration#DCL04C.Donotdeclaremorethanonevariableperdeclaration-Exceptions)  of precedence in styleguides.

**Comment by pq** [comment]
If I'm not mistaken, this was fixed by @a14n in https://github.com/dart-lang/linter/pull/3460.

**Comment by renancaraujo** [comment]
My bad for not finding the previous issue. 

Can confirm it is fixed on beta. 

However, stable (2.18.1) doesn't include that fix.

**Comment by pq** [comment]
> My bad for not finding the previous issue.

No worries!

Never hesitate to report an issue.  Feedback is always welcome.
