### ISSUE TITLE
linter repo issue templates are hard to follow for a bug report

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#3699]
**Describe the issue**

Here is the screen I am presented when filing an issue:

<img width="724" alt="Screen Shot 2022-09-18 at 7 19 06 PM" src="https://user-images.githubusercontent.com/103167/190940194-0425c2fc-7b98-4151-8030-1f7402c368d0.png">

Maybe most people follow this better than I, but here's how my process went:

* "Issue report - Create a report to help us make the linter better." I don't really know what that means, but I know for certain I don't want to create a report.
* "Lint proposal - Propose a new lint rule or a modification to an existing one." Er... I suppose I'm proposing a modification, when I'm filing a bug.

This leads me to this template:

<img width="729" alt="Screen Shot 2022-09-18 at 7 25 09 PM" src="https://user-images.githubusercontent.com/103167/190940601-8ae76987-c9c0-4e02-a2b4-d001235808e2.png">

This looks a little odd, as I'm "proposing a modification." None of these prompts seem to make sense... This led me to fill out the very bizzare issue: https://github.com/dart-lang/linter/issues/3697

**Comment by bwilkerson** [comment]
I agree that the current options are confusing. Let's figure out the different kinds of issues users typically report (that we want to gather different information for) and create a menu based on that.

I can think of a couple:

__Lint proposal__
Propose or request the addition of a new lint rule.

__Lint bug report__
Report a bug with or propose a modification to, an existing lint.

__Dart team recommended lints__
Propose including or excluding a lint in the core, recommended, or flutter lint sets, or discuss any other aspect of those lint sets.

__Request a fix for a lint__
Request that a fix be added for an existing lint.

What am I missing? Do we need/want the "Report a security vulnerability" item?

**Comment by srawlins** [comment]
Hmm what's the difference between "Lint bug report" and "Request a fix for a lint"?

I can't think of any other items though.

**Comment by pq** [comment]
> Hmm what's the difference between "Lint bug report" and "Request a fix for a lint"?

Maybe the intention is "Quick Fix"?

Otherwise, LGTM!

**Comment by bwilkerson** [comment]
Yes, I meant quick fix. (I like having a pointer to other repos where the issue is more appropriate to limit the number of issues we have to transfer.) Clearly it could use some word-smithing. :-)

**Comment by srawlins** [comment]
Ah of course. Yes, I like it!

**Comment by srawlins** [comment]
Thanks @pq !
