### ISSUE TITLE
flag `xxx != null ? xxx : null`

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#370]
This is the same as `xxx`

**Comment by bwilkerson** [comment]
It prevents unnecessary complexity.

One question is just how many kinds of complicated code to lint. Conditional expressions that can be simplified is good, but what about `x * 1` (when `x` is known to be a `num`), or `x?.y` when we can prove that `x` cannot be null, or hundreds of other kinds of overly complicated code? Maybe I'm overthinking it, though.

Do we have evidence that this kind of code is written frequently enough that a rule for it would add value?

**Comment by srawlins** [comment]
> Do we have evidence that this kind of code is written frequently enough that a rule for it would add value?

That's what I'm getting at. There are zero cases of this in internal code though.

**Comment by srawlins** [comment]
I'll close this as not high enough value. But if we have evidence that people write this, and would benefit from the rule, we can revisit.
