### ISSUE TITLE
recursive_getters can be very slow

### ISSUE THREAD

**Issue by davidmorgan** [dart-lang/linter#3706]
It looks like the recursive_getters lint time can be quadratic in ast size; the slow case we saw is a simple (generated) class with getters that are very large (500k of source) const collections. For these inputs, analysis of the lint took minutes.

**Comment by pq** [comment]
Yeah.  This is pretty bad.  I'll take a look.

@davidmorgan: can you distill something from what you saw into a test case I can benchmark against?

**Comment by pq** [comment]
Maybe something as simple as:

```dart
static get List<String> strings = const <String>[
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  'foo', 'bar', 'baz', 'foo', 'bar', 'baz','foo', 'bar', 'baz','foo', 'bar',
  ...
];
```

**Comment by bwilkerson** [comment]
Or generate the source code (as part of the test set-up) with as many lines of code as necessary. I don't know what the 500K collections look like, but if we did we could probably duplicate it fairly closely.

**Comment by davidmorgan** [comment]
Pinged Phil with the specific internal-only example; I wasn't able to figure out a good example to extract--it may be more complex than I assumed.
