### ISSUE TITLE
`// ignore: unawaited_futures` doesn't suppress the warning

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#382]
![image](https://cloud.githubusercontent.com/assets/405837/22257059/1068659a-e25d-11e6-9b57-86e3f8741bea.png)

**Comment by pq** [comment]
This seems like an `analyzer/server` bug...  Is it persisting?  Are any warnings suppressing?

**Comment by zoechi** [comment]
I just opened the project and can't reproduce. I'm sure I saw it very recently (a few hours ago or perhaps yesterday). I'll post a comment when I see it again.

**Comment by pq** [comment]
Great thanks!  Feel free to re-open if it crops up again. 👍

**Comment by zoechi** [comment]
I occasionally switched to older SDK versions because of issues. Perhaps this was when I saw it. 
Sure, will reopen when I see it atain.

**Comment by pq** [comment]
Thanks @zoechi .  Your feedback is really appreciated!
