### ISSUE TITLE
remove deprecated lints in 3.0

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3880]
3.0 would be a good time to remove deprecated lints.

Candidates:

- [x] #4005
- [x] #4009
- [x] #4012
- [x] #4013
- [x] #4014
- [x] #4020
  * (replaced by https://github.com/dart-lang/sdk/issues/50694)

**Comment by srawlins** [comment]
I think [enable_null_safety](https://dart-lang.github.io/linter/lints/enable_null_safety.html) should also be removed in 3.0. This rule is being replaced by https://github.com/dart-lang/sdk/issues/50694.

**Comment by srawlins** [comment]
I'd also like to remove [`avoid_null_checks_in_equality_operators`](https://dart-lang.github.io/linter/lints/avoid_null_checks_in_equality_operators.html), which mostly doesn't make sense under null safety, with a proposed rule: [`equality_operator_override_with_nullable_parameter `](https://github.com/dart-lang/linter/issues/3906)

**Comment by srawlins** [comment]
None of these have to do with null safety, so they can be deleted even before Google internal is null safe.

(The last one, `enable_null_safety`, _does_ obviously pertain to null safety, but is not used internally, so it can also be deleted.)

**Comment by mit-mit** [comment]
Can we also remove `default_list_constructor` ?

**Comment by mit-mit** [comment]
Also, how is the present issue different from https://github.com/dart-lang/lints/issues/95 ?

**Comment by pq** [comment]
> Can we also remove default_list_constructor ?

I think so?  @bwilkerson?

> Also, how is the present issue different from https://github.com/dart-lang/lints/issues/95 ?

This issue tracks the removal of the lint implementations from the linter.  https://github.com/dart-lang/lints/issues/95 is about removing newly removed/deprecated lints from the published lint sets.

**Comment by bwilkerson** [comment]
The `default_list_constructor` diagnostic is a compile-time error, not a lint, but I believe that we can remove it. It won't be reported in 3.0 because it looks for invocations of the default constructor, but the default constructor is gone so there can't be an invocation of it (the error instead is "The class 'List' doesn't have an unnamed constructor.").

**Comment by pq** [comment]
Closing linter side as complete.
