### ISSUE TITLE
Deprecate `iterable_contains_unrelated_type` and `list_remove_unrelated_type`

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#3893]
in favor of `collection_methods_unrelated_type`

See my proposal to replace those two with the new rule in the lints package: https://github.com/dart-lang/lints/issues/93.

The best way to do this would be to ship a lints release with `iterable_contains_unrelated_type` and `list_remove_unrelated_type` replaced by `collection_methods_unrelated_type`, _then_ deprecated them. This would result in less churn.

**Comment by pq** [comment]
Great point re: less churn.   We'll want to be thoughtful about how we time updates to `package:lints`.  (See also: https://github.com/dart-lang/linter/issues/3879 which proposes we deprecate a few recommended lints.)

**Comment by pq** [comment]
@srawlins: I'm thinking this is a little close to the wire to pull off?

**Comment by srawlins** [comment]
Hmm close to what wire? I don't know what is involved with deprecating a lint rule, but it doesn't need to be... associated with any Dart SDK or language version, right? It's not breaking?

**Comment by srawlins** [comment]
Although in the summary above I mention that the best way forward might be some work in the lints package first, before deprecating. No strong opinions here.

**Comment by pq** [comment]
> Hmm close to what wire?

Sorry, I wasn't clear at all! It was on the list to consider for 3.0.  I guess I'd just like to push it to later.

**Comment by srawlins** [comment]
Sounds good to me.

**Comment by srawlins** [comment]
@devoncarew mentioned [here](https://github.com/dart-lang/lints/issues/118#issuecomment-1548344633) it should be safe to deprecate first, then remove from package:lints. Mind if I ship that, @pq ?

**Comment by pq** [comment]
You mean, deprecate these lints here now? Sure thing.

**Comment by srawlins** [comment]
Sorry, I don't know what the difference is, but I'd like to _remove_ the rules. Is there a reason to deprecate them before removing them?

**Comment by pq** [comment]
The difference is that a removed lint will no longer work whereas a deprecated one will.

> Is there a reason to deprecate them before removing them?

It's a nice way to give folks an opportunity to give feedback (and continue to give them lints before they've adopted the new recommendation).

Unless a lint is deeply broken or made obsolete (e.g., pre-null safety), I'd prefer a deprecation period.

We could add more details here I guess:

https://github.com/dart-lang/linter/blob/main/doc/lint-lifecycle.md#removed

**Comment by srawlins** [comment]
OK
