### ISSUE TITLE
deprecate `LintRule` maturity in favor of a more general state

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3896]
Lint rules currently have an associated _maturity_ (stable, experimental or deprecated).  Looking ahead, we'd like to expand this to a more generalized notion of "state" to model additional things like renames (#3827), replacements and removes (#3880) and allow for the further association of additional metadata like "when".

**Breaking in 3.0.** Note that this change will be "breaking" in 3.0, removing the `maturity` parameter in favor of a `state`.  In the short-term I propose we deprecate (but support) `maturity` until we can get our internal lints moved over (and give lint plugin authors a chance too).

I'll follow-up with a CL on the analyzer (where `Maturity` lives) but wanted to open the idea up to a general conversation here.

Feedback welcome!

**Comment by srawlins** [comment]
Why is `maturity` part of the public API? If it's private API, shouldn't be breaking.

**Comment by pq** [comment]
> Why is maturity part of the public API? 

Anyone who is maintaining lints outside of the linter repo will be effected (e.g., plugin authors and Google3 lint maintainers).  Maybe not technically _breaking_, but definitely **impacting**.

**Comment by srawlins** [comment]
I see. It seems fine to call it breaking, since I think we would not want to break plugins in a minor release like 3.1.0

**Comment by pq** [comment]
Analyzer change in flight [here](https://dart-review.googlesource.com/c/sdk/+/276682). Local changes staged in https://github.com/dart-lang/linter/pull/3956.

**Comment by pq** [comment]
Internal changes are in flight and we're all migrated here.
