### ISSUE TITLE
Fix rule tests (by ensuring rule registry is populated).

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#390]
Rule tests are failing because the way rules get registered changed in the `analyzer 0.29` stream.  the rub is we need a good place to ensure that `registerLintRules()` has been called before we lookup lints.  We might consider changing `Registry.ruleRegistry` (in analyzer) to a smart getter. Alternatively, we might wrap registry access in the linter in a separate object that handles initialization.  (Other options too.)

**Comment by bwilkerson** [comment]
Is this needed outside of tests? If not, then I think we should just call `registerListRules` in the setUp function.

Analyzer cannot have a dependency on the linter plugin, so I don't think `Registry.ruleRegistry` can be a "smart" getter. And if I understood your idea for linter, it would only change the function that has to be called in setUp, which wouldn't add much value.

**Comment by pq** [comment]
> Is this needed outside of tests? 

At the moment, yes.  It is also used in `bin/linter`.  Of course, if that goes then the point is at least partly moot!

**Comment by pq** [comment]
Fixed w/ #392
