### ISSUE TITLE
proposal: mark `use_enums` stable

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3909]

**Comment by srawlins** [comment]
I'm all for this. Have we enabled it in analyzer-owned packages? Might be a good smoke test.

**Comment by pq** [comment]
I haven't looked exhaustively.  A quick check on analyzer identifies `AnalysisStatus`.  Worth looking at.

**Comment by pq** [comment]
This one is already enabled for flutter FWIW (which @jacob314 was asking about).

OKing for stable.
