### ISSUE TITLE
🔴  proposal: mark `use_build_context_synchronously` stable

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3915]
This is heavily depended on internally, is in the flutter rule set and adding lots of measurable value.  I propose promotion.

**Comment by srawlins** [comment]
Should we first look at the [open bugs](https://github.com/dart-lang/linter/issues?q=is%3Aissue+is%3Aopen+use_build_context_synchronously)? There are quite a few, and it could cost more to fix them after marking stable. 🤷  maybe the horse is out of the barn.

**Comment by pq** [comment]
Yeah.  I think this one would be pretty hard to roll back so I think it's kind of _de facto_ not experimental anymore.

**Comment by pq** [comment]
Given the open issues, let's leave experimental for now.
