### ISSUE TITLE
[Class modifiers] Linter implementation

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3917]
## New class modifiers
This issue tracks the linter implementation of the new class modifiers feature.

- [ ] #3920
- [x] #3928

### Specs
* [Sealed types](https://github.com/dart-lang/language/blob/master/accepted/future-releases/sealed-types/feature-specification.md)
* [Class modifiers](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md)

**Comment by pq** [comment]
The spec says `@sealed` classes are implicitly abstract classes: 

> A class marked sealed is implicitly an abstract class with all of the existing restrictions and capabilities that implies. 

and so we should look at lints that treat abstract classes specially.

One such lint is [`one_member_abstracts`](https://dart-lang.github.io/linter/lints/one_member_abstracts.html).  That said, my initial reaction is that we do **not** want to extend it to lint one member sealed classes since sealed classes can't just be replaced with functions (as the lint advice suggests).

@munificent?

**Comment by srawlins** [comment]
> The spec says `@sealed` classes are implicitly abstract classes:

You mean `sealed` here, right? Not `@sealed`?

**Comment by pq** [comment]
Ha!  Yes, absolutely. 😬

**Comment by munificent** [comment]
> That said, my initial reaction is that we do **not** want to extend it to lint one member sealed classes since sealed classes can't just be replaced with functions (as the lint advice suggests).

👍 

I wonder if one_member_abstracts still carries its weight. I added that corresponding rule to "Effective Dart" back in the days when many programmers still wrote Java in whatever language they were using and weren't comfortable with closures. These days, it seems like everyone is pretty fluent with lambdas and aren't likely to think they need to write an entire interface just for a single operation any more.

**Comment by pq** [comment]
> I wonder if one_member_abstracts still carries its weight. 

I wonder this too.  I'm not sure it merits deprecation quite but just shy maybe?

In any event, the initial issue seems settled, we will not upgrade it to be `sealed` class aware.

Thanks for the feedback!

**Comment by bwilkerson** [comment]
Actually, we'll need to have a test in order to not produce the diagnostic when the `sealed` modifier exists. It's not so much a case of making it work with the new syntax as it is a matter of preventing it from working when the new syntax is being used.

**Comment by pq** [comment]
Closing in favor of individual tracking issues.
