### ISSUE TITLE
implement `implicit_reopen`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#3920]
From the [base-interface-final spec](https://github.com/dart-lang/language/blob/master/accepted/future-releases/class-modifiers/feature-specification.md#reopen-lint):

**`@reopen` lint**
 ...

A metadata annotation `@reopen` is added to package [meta](https://pub.dev/packages/meta) and a lint ~~"require_reopen"~~ `implicit_reopen` is added to the [linter](https://dart.dev/guides/language/analysis-options#enabling-linter-rules). When the lint is enabled, a lint warning is reported if a class or mixin is not annotated `@reopen` and it:

Extends or mixes in a class, mixin, or mixin class marked interface or final and is not itself marked interface or final.

**Comment by pq** [comment]
Updating the proposed name to `implicit_reopen` as per the conversation in https://dart-review.googlesource.com/c/sdk/+/278888.

/fyi @lrhn @bwilkerson

**Comment by pq** [comment]
See also: https://github.com/dart-lang/language/issues/2871

**Comment by srawlins** [comment]
Is this ticket blocked?

**Comment by pq** [comment]
Yes. I'm scrapping a prototype that duplicates the class modifier induction algorithm in analyzer in favor of a new implementation that will leverage @kallentu's work (underway) to thread that information through the element model (when it's complete).

**Comment by srawlins** [comment]
Thanks, @kallentu is there a ticket for your work, or a CL?

**Comment by kallentu** [comment]
@srawlins There isn't. Made a quick one here https://github.com/dart-lang/sdk/issues/51671
CL is still WIP.

**Comment by srawlins** [comment]
Thanks much!
