### ISSUE TITLE
`unnecessary_getters` not in docs

### ISSUE THREAD

**Issue by MaryaBelanger** [dart-lang/linter#3925]
I might be missing some context, but there's `unnecessary_getters` does not appear in the [Linter rules](https://dart.dev/tools/linter-rules) docs. I wanted to fix an Effective Dart sections that's pointing to an unrelated lint: https://github.com/dart-lang/site-www/pull/4454

**Comment by bwilkerson** [comment]
@pq

**Comment by parlough** [comment]
The lint is currently disabled so it’s not surfaced in the docs. See https://github.com/dart-lang/linter/issues/23 for more context

**Comment by MaryaBelanger** [comment]
Well that answers my question! Thanks @parlough I'll close this

**Comment by pq** [comment]
Ah!  Sorry for the confusion, @MaryaBelanger.  (And thanks for the sanity check @parlough!)
