### ISSUE TITLE
use_build_context_synchronously example code and description are wrong

### ISSUE THREAD

**Issue by fourman-alex** [dart-lang/linter#3943]
The [documentation](https://dart-lang.github.io/linter/lints/use_build_context_synchronously.html) states `When a BuildContext is used, its mounted property must be checked after an asynchronous gap` While `mounted` is a property of `State` and NOT `BuildContext`

Also this example (in the description) is wrong for the reason mentioned above:
```
void onButtonTapped() async {
  await Future.delayed(const Duration(seconds: 1));

  if (!context.mounted) return;
  Navigator.of(context).pop();
}
```
This statement will not compile: `if (!context.mounted) return;`

**Expected behavior**

- A better example that takes into account a StatelessWidget that has an async gap in one of its callbacks
- change ` if (!context.mounted) return;` to `if (!mounted) return;` but emphasize that this is only for StatefulWidgets

**Comment by pq** [comment]
Ah, yes.  Looks like we have lots of room for improvement here.  Thanks!  (And sorry for any confusion caused.)

If you want to take a crack at improving the docs, a PR is most welcome.  Otherwise any ideas for better examples would be appreciated!

**Comment by fourman-alex** [comment]
@pq I've made an initial attempt at this. Though this lint seems to touch upon a problematic limitation of `BuildContext` and its lifecycle. Any way, if someone can have a look at my PR and comment, that would be great.

**Comment by pq** [comment]
Thanks a million!

**Comment by srawlins** [comment]
Closing as `mounted` is now a property on `BuildContext`. Please re-open if the issue remains.
