### ISSUE TITLE
Prevent equality checks as statements

### ISSUE THREAD

**Issue by jonmountjoy** [dart-lang/linter#4046]
**Describe the rule you'd like to see added and to what rule set**
I'd like to prevent this kind of bug:

    ...
    itemState.learningAspect == LearningAspect.learnNumber;
    ...

In other words, I have a statement, and that statement is an equality check, the value of which I'm discarding.

It's almost always an error (for me, it's *always* an error), because what I invariably want to write is:

    itemState.learningAspect = LearningAspect.learnNumber;

In other words, I've used an equality check (copy pasta or finger slip or whatever) instead of an assignment.

I can't imagine a scenario when anyone would *want* to write that kind of statement, but I guess it's possible.  In other contexts (embedded as an expression), types would usually catch the error.  But as a standalone statement, the type system is quite happy.  I imagine at run time it performs the equality check and discards the boolean result.

In some ways I think it's similar to [unawaited_futures](https://dart-lang.github.io/linter/lints/unawaited_futures.html).  I wouldn't mind an "unused_boolean" - it would cover me in this situation and force me to think more about my other methods too.

Thoughts?

(thanks!)

**Comment by bwilkerson** [comment]
@srawlins Who might also remember whether we used to have such a diagnostic.

**Comment by pq** [comment]
@eernstg, you may be thinking of [`unnecessary_statements`](https://dart-lang.github.io/linter/lints/unnecessary_statements.html)?

**Comment by pq** [comment]
In fact, @jonmountjoy: I think `unnecessary_statements` covers your case?

**Comment by eernstg** [comment]
Exactly, `unnecessary_statements` is what I was looking for, I just didn't come up with the right words to search for. ;-)

**Comment by jonmountjoy** [comment]
Ahhh that's fabulous @eernstg @pq @bwilkerson  - that does the job! 
I would seriously consider putting this in the default recommended lints.

This is so nice - thank you!
