### ISSUE TITLE
Migrate mixins to be mixin declarations

### ISSUE THREAD

**Issue by jakemac53** [dart-lang/linter#4058]
With the "class modifiers" feature coming, we need to migrate all of the `abstract class` declarations that are used as mixins to be either `mixin` declarations, or possibly `mixin class` declarations.

This will likely be a blocker for enabling Dart 3 internally.

**Comment by jakemac53** [comment]
cc @itsjustkevin I am not sure if there is a good meta issue to attach this to for tracking

**Comment by lrhn** [comment]
We can mark the library as `// @dart=2.19` until we add the `mixin` to the `mixin class`. That would allow the code to stay valid when we switch to Dart 3.0 (or enable class modifiers), without having to fix all the mixin classes in the same commit.

**Comment by jakemac53** [comment]
Oh good point, that might be a good workaround for internal also
