### ISSUE TITLE
Should `prefer_mixins` be removed for Dart 3?

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#4065]
Dart 3 only allows mixing in classes if they have been marked as mixin-able with the new `mixin` class modifier. If a class has specifically been marked with that modifier, it should be OK to be mixed in. Is there still value in having this lint that disallows mixing in classes?

I believe, this lint should be removed for Dart 3.

**Comment by goderbauer** [comment]
@pq @srawlins @munificent @leafpetersen

**Comment by pq** [comment]
Hmmmm.  On the surface, it seems like this is ripe for removal.

Maybe @lrhn can see some nuance though?

**Comment by lrhn** [comment]
The lint still applies to classes defined in (the still supported) language version 2.12 .. 2.19 code.

Those _can_ be mixed in by both pre and post 3.0 code, and usually you shouldn't.

**Comment by goderbauer** [comment]
Ah, that makes sense. Does the lint need to be adapted to not warn about classes that do have the mixin modifier, though?

**Comment by pq** [comment]
> Does the lint need to be adapted to not warn about classes that do have the mixin modifier, though?

💯 

Good catch.  Will fix.

Thanks!
