### ISSUE TITLE
`prefer_const_literals_to_create_immutables` reflective tests cannot report a lint

### ISSUE THREAD

**Issue by srawlins** [dart-lang/linter#4108]
**Describe the issue**

prefer_const_literals_to_create_immutables reflective tests cannot report a lint, because they [refer to a non-existent lint rule](https://github.com/dart-lang/linter/blob/main/test/rules/prefer_const_literals_to_create_immutables_test.dart#L21), notice the trailing `.dart`.

**Comment by pq** [comment]
Yikes! Good catch. 😬
