### ISSUE TITLE
Auto-generated list of rules should not contain "removed" ones

### ISSUE THREAD

**Issue by tsimbalar** [dart-lang/linter#4135]
(reporting it as a bug, but not sure this is right )

**Describe the issue**
The documentation hosted here: https://dart-lang.github.io/linter/lints/options/options.html contains rules such as `avoid_as` (https://dart-lang.github.io/linter/lints/avoid_as.html) which are marked as **_removed_**.

**To Reproduce**
Look at https://dart-lang.github.io/linter/lints/options/options.html

**Expected behavior**
https://dart-lang.github.io/linter/lints/options/options.html should only contain rules that are considered valid.

**Additional context**
Not sure if fixing it would be considered a breaking change, or if maybe there should be a separate page with that filtering applied, or maybe there should be a page for each version of the Dart SDK, showing only the list of options that make sense "as of" that version ?

**Comment by pq** [comment]
Good catch and totally agreed.  Thanks!
