### ISSUE TITLE
`prefer_final_locals` reporting on wrong node

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4228]
<img width="336" alt="image" src="https://user-images.githubusercontent.com/67586/228075068-b035ab5e-de09-43fc-ac61-8252fd6c7813.png">

```dart
f() {
  var (a, b) = (1, 2);
}
```

**Comment by pq** [comment]
/fyi @srawlins -- maybe your PR fixes these?

**Comment by srawlins** [comment]
It... might!

Was this an existing test case? If not, I will add it and confirm.

**Comment by pq** [comment]
Not sure. It's possible I didn't check the offsets right in my test expectations? 😬

**Comment by pq** [comment]
Fixed w/ #4230 4225.
