### ISSUE TITLE
Implement rule to verify DO place “package:” imports before relative imports.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#423]
From https://www.dartlang.org/guides/language/effective-dart/style#do-place-package-imports-before-relative-imports

**Comment by bwilkerson** [comment]
I have to wonder whether we ought to have multiple lints related to the order of import and export directives, or whether it might be better to have a single lint that enforces the one blessed order.

**Comment by JPaulsen** [comment]
Yes, we will add the 5 ordering rules to the lint https://github.com/dart-lang/linter/pull/422 in different pull requests

**Comment by bwilkerson** [comment]
But then you merged https://github.com/dart-lang/linter/pull/425, which added a new lint rule rather than extending the previous rule. I'm not sure we're communicating.

**Comment by JPaulsen** [comment]
I didn't merged it, I discarded it, so we can add to the rule implemented in https://github.com/dart-lang/linter/pull/422 in a subsequent pull request. Master branch is still at https://github.com/dart-lang/linter/commit/47e125bc31ffed31e3482a5d935f3666bcaefe68

**Comment by bwilkerson** [comment]
Oh, sorry, I must have misread something.
