### ISSUE TITLE
Extend directives_ordering rule: third-party imports first

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#429]
From https://www.dartlang.org/guides/language/effective-dart/style#prefer-placing-third-party-package-imports-before-other-imports

To implement this, I guess that I need to recover the package name of the current CompilationUnit that I am visiting, someone knows how to recover it?

**Comment by zoechi** [comment]
I guess this [linter rule](http://dart-lang.github.io/linter/lints/package_prefixed_library_names.html) uses something like what you're looking for
