### ISSUE TITLE
Lint for empty catch blocks

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#43]
This is a code smell and would be great if the linter could inform about it.

**Comment by pq** [comment]
Would you want to treat the following equally?
```
try {
  ...
} catch(exception, stackTrace) {
  // ignore
}
```
vs.
```
try {
  ...
} catch(exception, stackTrace) { }
```

Maybe this is where linter-specific comments come into play:
```
try {
  ...
} catch(exception, stackTrace) {
  // dartlint:ignore:empty_catch
}
```

(Not a real comment format but you get the idea.)

**Comment by zoechi** [comment]
I would require a linter comment to silent hints/warning like in your 3rd example

**Comment by pq** [comment]
@zoechi :+1:  #44.
