### ISSUE TITLE
`unnecessary_late` ignores lazy initialization pattern ?

### ISSUE THREAD

**Issue by polina-c** [dart-lang/linter#4307]
Quick fix makes the variable initializing immediately. Should this lint be removed from standard flutter lints?

<img width="686" alt="Screenshot 2023-04-24 at 1 12 34 PM" src="https://user-images.githubusercontent.com/12115586/234105797-d843be6a-b0e8-4946-8ff1-df1a2d8193a9.png">

**Comment by pq** [comment]
My understanding is that  static variables with initializers are evaluated lazily as-is and marking them `late` is redundant.

@bwilkerson: can you confirm?

**Comment by scheglov** [comment]
The [specification](https://spec.dart.dev/DartLangSpecDraft.pdf) seems to support this.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/384794/234117317-87d64d8d-141f-4bec-aa48-a72589c98338.png">

**Comment by pq** [comment]
Thanks for confirming! @polina-c: I think this is WAI.  Feel free to re-open if you think that's mistaken!
