### ISSUE TITLE
`flutter_style_todos` not allowing usernames with dots

### ISSUE THREAD

**Issue by vrnvorona** [dart-lang/linter#4348]
Describe the issue
The regex does not accept usernames with dots in the middle.
// TODO(myname): would work
// TODO(my.name): would not

Expected behavior
// TODO(my.name): should be valid

**Comment by srawlins** [comment]
@goderbauer Sound ok to you?

**Comment by goderbauer** [comment]
Dots in names are fine with me!

**Comment by srawlins** [comment]
Fixed in https://github.com/dart-lang/sdk/commit/be5ad6192ba0c6a5f61cb49bea6b072221eee811
