### ISSUE TITLE
Lint docs should include installation instructions / example of usage

### ISSUE THREAD

**Issue by eseidel** [dart-lang/linter#4351]
I always forget the syntax to include lints.  Would love to have something copy-paste in the docs, e.g.:

https://dart-lang.github.io/linter/lints/unawaited_futures.html

Should have a small section:

## Usage

```yaml
linter:
  rules:
    - unawaited_futures
```

Similar to what we do in pub:
https://pub.dev/packages/openapi_generator/install

Although honestly maybe a command line would be easier. :)  But even just adding the usage docs I think would be an improvement.

**Comment by pq** [comment]
Great suggestion!

We've talked about a CLI for enabling lints but have never taken it anywhere (fyi @srawlins) but worth revisiting.

/fyi @MaryaBelanger @parlough @bwilkerson re: doc improvements. It'd be super-easy to add a usage footer to the generated docs. I'd be curious to get your 2 cents.

**Comment by parlough** [comment]
I created an SDK issue to track a CLI command: https://github.com/dart-lang/sdk/issues/52394. It has made explaining adding pub dependencies so much easier and would be a big win for documentation purposes.
