### ISSUE TITLE
prefer_conditional_assignment message is confusing

### ISSUE THREAD

**Issue by Hixie** [dart-lang/linter#4398]
The message for "prefer_conditional_assignment" is "Unnecessary 'null' comparison before assigning a value":

```
Object?	bar() => null;

void main() {
  Object? foo = bar();
  if (foo == null) { // "Unnecessary 'null' comparison before assigning a value"
    foo = bar();
  }
  print(foo);
}  
```

This makes it sound like the fix is to remove the comparison:

```
Object?	bar() => null;

void main() {
  Object? foo = bar();
  foo = bar();
  print(foo);
}  
```

...which of course is semantically quite different.

Something like "Prefer the "??=" operator instead of an "if" statement" might be clearer?

**Comment by pq** [comment]
@bwilkerson

**Comment by bwilkerson** [comment]
I agree that the current message is misleading. We generally write our problem messages to indicate what's wrong and use the correction message to indicate how to solve the problem, so perhaps something like "The 'if' statement could be replaced by a null-aware assignment. Use the `??=` operator to conditionally assign a value." or maybe "be simplified by using".

**Comment by Hixie** [comment]
I almost introduced a bug in my code today because of this linter message.
