### ISSUE TITLE
Lint not ignored with `// ignore_for_file: type=lint`

### ISSUE THREAD

**Issue by osa1** [dart-lang/linter#4402]
```dart
// a.dart
import 'dart:core';

@Deprecated("Don't use")
void f() {}

// b.dart
// ignore_for_file: type=lint

import 'a.dart';

void g() {
  f();
}
```

Try with SDK main branch (https://github.com/dart-lang/sdk/commits/2e29ed3874c):

```
$ ~/dart/sdk/sdk/out/ReleaseX64/dart-sdk/bin/dart analyze b.dart
Analyzing b.dart...

   info - b.dart:6:3 - 'f' is deprecated and shouldn't be used. Don't use. Try replacing the use of the deprecated member with the replacement. -
          deprecated_member_use_from_same_package

1 issue found.
```

**Comment by srawlins** [comment]
That is a hint being reported, not a lint.

**Comment by srawlins** [comment]
That's true. There are actually two rules. We are in the process of migrating [the hint](https://dart.dev/tools/diagnostic-messages#deprecated_member_use_from_same_package) to be a lint. Right now each can be reported, depending on analysis options.

> How do I know what's included in `type=lint`?

Everything [here](https://dart-lang.github.io/linter/lints/index.html) is a lint.

**Comment by osa1** [comment]
> Everything [here](https://dart-lang.github.io/linter/lints/index.html) is a lint.

I'm confused. That page lists `deprecated_member_use_from_same_package`, but you just said it's not a lint above. Is it a lint or not?

**Comment by srawlins** [comment]
There are two rules named `deprecated_member_use_from_same_package`. [One](https://dart.dev/tools/diagnostic-messages#deprecated_member_use_from_same_package) is a hint, and [the other](https://dart-lang.github.io/linter/lints/index.html) is a lint. The diagnostic which is reported by `dart analyze` above is the hint.

**Comment by osa1** [comment]
Thanks for the details. Closing as this is not a bug.
