### ISSUE TITLE
prefer_final_fields don't lint if field never initializes

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#441]
A common pattern in POs is to generate code using the class developers write, the lint is warning correctly but users are turning this rule off because is spammy.

Change in the rule should be such that if the field is never initialized there is no lint.

**Comment by alexeieleusis** [comment]
Here is an example of a user turning the rule off precisely for this reason https://github.com/sturmf/regatta-angular2/blob/04023c85439c86856592b57c1c7932ae47e2c811/frontend/.analysis_options#L49

**Comment by JPaulsen** [comment]
Working on it! (couldn't assign)
