### ISSUE TITLE
stop documenting "linter version"

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4426]
Related to #4389 and part of #4424, I'd like to remove all the bits that identify and document linter versions.  Versions show up, for example, in docs here:

<img width="384" alt="image" src="https://github.com/dart-lang/linter/assets/67586/f9fc4779-242c-4e68-a6e2-cf3d21ca1eb6">

@parlough (and others) is there anything downstream that would break if we stopped tracking linter version?

**Comment by parlough** [comment]
I've never used the linter version as I don't think it's relevant to users.

**Comment by pq** [comment]
Awesome. Thanks!

**Comment by bwilkerson** [comment]
I'm not sure how useful having an SDK lower bound is for users, but if it's helpful we could just make it a field on `State`. New lints would presumably get the next release number at the time they were written.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/linter/pull/4435.
