### ISSUE TITLE
remove stale entries from `rules.json`

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4432]
I'd like to remove a few things from our generated json descriptions of lint rules (https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json).

Specifically, I'd like to remove:

* `"maturity"` (now state)
* `"sinceLinter"` (see: https://github.com/dart-lang/linter/issues/4426)

@parlough, @devoncarew: do you have any idea who (if anyone) is using this file?

(I feel like I put this together for @csells a while back but can't recall how it's use has evolved...)

**Comment by devoncarew** [comment]
From dart-lang/lints, we're using `name` and `description` (and may end up using `hasFix`).

**Comment by parlough** [comment]
We currently [use it](https://github.com/dart-lang/site-www/blob/main/src/_includes/linter-rules-section.md) to generate https://dart.dev/tools/linter-rules but I imagine that may change in the future.

However, we don't use `maturity` or `sinceLinter` anymore, so those should be safe to remove.
