### ISSUE TITLE
[Question] Are there any users of the generated markdown docs?

### ISSUE THREAD

**Issue by parlough** [dart-lang/linter#4459]
I know this isn't a discussion board or an actionable issue, but I wasn't sure where else to ask.

I'm trying to plan documentation work, so I'm curious if anyone who sees this issue is currently using them?

If so, are they helpful to you? How do you use them? What could be improved? If they disappeared for a while, would that be a problem?

I appreciate your insight, thanks!

**Comment by pq** [comment]
@devoncarew?

**Comment by devoncarew** [comment]
> If so, are they helpful to you? How do you use them? What could be improved? If they disappeared for a while, would that be a problem?

I don't think I was aware of them :) Are they committed somewhere? Hosted somewhere?

Getting down to one system of record for where to host linter docs (i.e. dart.dev) seems useful.

**Comment by parlough** [comment]
I don't think they are committed or hosted somewhere, it's just the generation capability is there. I have a feeling no one uses the functionality currently, but wanted to make sure before I strip it out to make way for the future.
