### ISSUE TITLE
plan for hosting linter documentation post repo-move

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4460]
@parlough: would you mind spitballing some of your ideas for post-repo move doc-hosting?

**Comment by parlough** [comment]
In the short term, before we update and introduce split diagnostic and discovery docs, or whatever that will entail, my plan is loosely as follows:

- [ ] Make dart.dev/lints cover everything currently on https://dart-lang.github.io/linter/
  - [x] Add a page which lists all linter rules. (https://github.com/dart-lang/site-www/pull/4990)
  - [ ] Introduce an index similar to [the old one](https://dart-lang.github.io/linter/lints/index.html) which allows for easy discovery. (https://github.com/dart-lang/site-www/pull/4999)
  - [ ] Move linter rule information to their own pages. (https://github.com/dart-lang/site-www/pull/4999)
- [ ] Update the generator on `dart-lang/linter` to redirect to `dart.dev/lints/<rule>`.
  - [ ] Use [`http-equiv`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta#http-equiv) and specify a [canonical URL](https://developers.google.com/search/docs/crawling-indexing/consolidate-duplicate-urls#rel-canonical-link-method).
  - [ ] Add backup text directing to the new locations.
- [ ] Update links around `dart-lang` and `flutter` repos to point to the new dart.dev equivalents.
  - [ ] Update all links within `dart-lang/linter`, specifically the one in the repository description.
  - [x] Update the analyzer to point to `dart.dev/lints/<rule>` in diagnostic messages (https://github.com/dart-lang/sdk/commit/25c0ae1c423e32e9e539232318ca1c32bb70eee6).
  - [ ] Update other miscellaneous links.

**Comment by parlough** [comment]
At least in the short term, the generated document that remains useful for dart.dev, `package:lints`, and perhaps elsewhere is the [`rules.json`](https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json). Perhaps we can move this in tree and have a test that makes sure it is up to date?

**Comment by pq** [comment]
@parlough: are we basically done here?  Anything else we need to be tracking?

**Comment by parlough** [comment]
I think this issue can be closed :)
