### ISSUE TITLE
unreachable_from_main ignores classes used through `external` members

### ISSUE THREAD

**Issue by natebosch** [dart-lang/linter#4474]
The following has an unexpected lint:

```dart
void main() {
  c.doStuff();
}

class C {}
//    ^ unreachable_from_main

extension on C {
  void doStuff() {}
}

external C get c;
```

The real code this came up for has an `@JS()` on the `class` and the `external` getter, but it doesn't require the annotations for the static reproduction.

https://github.com/dart-lang/test/blob/3d5afedce6fe9643cafbeb89af45ebe9754233c2/pkgs/test/tool/host.dart#L18-L28

**Comment by bwilkerson** [comment]
@srawlins

**Comment by srawlins** [comment]
Is there a specification for... what code might exist in `external` implementations? Can they access private elements? Can an `external` implementation of a field access other fields?

**Comment by natebosch** [comment]
I don't think we need to worry about what the `external` implementation might need to access. We only need to know that if an `external` returns a `Foo`, then `Foo` is not unused.

**Comment by srawlins** [comment]
Sounds good.
