### ISSUE TITLE
false positives for recursive_getters

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#452]
In flutter 2 false positives for 

- https://github.com/flutter/flutter/blob/9a9a3ffd11f7cdc4f69f5a57b925c0005f327281/packages/flutter/lib/src/widgets/scroll_position.dart#L97
- https://github.com/flutter/flutter/blob/9a9a3ffd11f7cdc4f69f5a57b925c0005f327281/packages/flutter/lib/src/widgets/scroll_position.dart#L107

**Comment by pq** [comment]
Thanks @a14n !

**Comment by alexeieleusis** [comment]
I think this was fixed in https://github.com/dart-lang/linter/commit/8675b2f4524ff5a887356f87b8351d1e9a80a081
