### ISSUE TITLE
public_member_api_docs: constructors on sealed classes are not really public

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/linter#4526]
_Similar to https://github.com/dart-lang/linter/issues/284 (/cc @yjbanov)._

Here is a more recent (2023-era) problem, constructors that are not _really_ public.

Consider:

```dart
sealed class Fruit {
  Fruit();
}

final class Apple extends Fruit {}
final class Orange extends Fruit {}
final class Banana extends Fruit {}
```

The `Fruit()` constructor _appears_ public (i.e. it does not start with `_`), but in Dart 3+, it is _functionally_ private (that is, it's only accessible in the same library, similar to methods declared with `_`).

**Comment by lrhn** [comment]
The class is abstract (so constructor cannot be called or torn off) and cannot be subclassed, so there is indeed no valid way to use the constructor.

The constructor could just as well have been private.
Or would make sense for, e.g., dartdoc to only any reference to the constructor, similar to constructors of abstract interface or final classes.

**Comment by pq** [comment]
Following the lead of #4470, I think we want to extend this to similarly skip generative constructors in classes that are 

* abstract and interface
* abstract and final.

**Comment by pq** [comment]
> It would make sense for, e.g., dartdoc to omit any reference to the constructor, similar to constructors of abstract interface or final classes.

fyi @srawlins

**Comment by matanlurey** [comment]
Thanks @pq!

**Comment by pq** [comment]
You bet @matanlurey. Thanks for the thoughtful report!
