### ISSUE TITLE
Preserve machine-generated linter rules JSON file

### ISSUE THREAD

**Issue by parlough** [dart-lang/linter#4587]
The machine-generated `rules.json` file found on the `gh-pages` branch at https://github.com/dart-lang/linter/blob/gh-pages/lints/machine/rules.json is still used by a few clients. 

For the purposes of moving to the SDK, it should potentially be checked in to the `main` branch with a test to make sure it's up to date.

\cc @pq

**Comment by pq** [comment]
Thinking about a location... We could put it adjacent to `all.yaml`?  (Though `example/` is maybe a strange directory for it to live in.)  Maybe a `doc` dir like server has?

@parlough: thoughts?

**Comment by parlough** [comment]
Yeah I agree that `example/` might be a bit confusing since it's not an example. 

I was think the generation logic and the file itself could live in `/tool/machine` to keep things together but a `doc` directory would be fine too.

**Comment by pq** [comment]
`/tool/machine` SGTM. Thanks!
