### ISSUE TITLE
remove lint checking workflow

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4643]
@parlough, I'm guessing you do something similar on dart.dev and this can safely just be removed?

https://github.com/dart-lang/linter/blob/main/.github/workflows/linkcheck.yml

See: https://github.com/dart-lang/linter/issues/4411

**Comment by parlough** [comment]
Nice catch, I forgot to remove this workflow. Opened https://github.com/dart-lang/linter/pull/4644 to remove it.
