### ISSUE TITLE
A way to suppress lints on file level

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#468]
For generated code it's difficult to suppress linter hints/warnings because it's difficult to find the right place where to add the comment. For example in https://github.com/dart-lang/code_builder it would be quite difficult to support all possible places where such comments might be required.

It would be better if for example at the beginning of a file specific linter rules could be suppressed for the whole file.
File level would be preferred over library level, for example when the main library file is manually created and a part file generated.

Exclusions in the `analysis_options.yaml` file don't allow to exclude specific linter rules for specific files, only to exclude files entirely for all checks.  
Most linter rules are also useful in generated code, but for some it's just hard to make the generated code comply.

**Comment by bwilkerson** [comment]
I would think that it would be better to add support for disabling specific lint rules for specific files in the analysis options file rather than to require everyone writing a code generator to generate 'ignore' comments for the lint rules that their generated code won't conform to (including those lints that don't exist yet :-).

**Comment by zoechi** [comment]
On the other side the user of a code generator library would need to maintain the config while with suppressions in the code file this could be avoided.
I have no strong opinion. I just wish for a way to disable some lints in a set of files while not excluding them entirely.

**Comment by pq** [comment]
As of Dart 1.24 you can ignore a specific rule for a specific file using an `ignore_for_file` comment:

    // ignore_for_file: unused_import

More in the [docs](https://www.dartlang.org/guides/language/analysis-options#ignoring-specific-analysis-rules).

🤘
