### ISSUE TITLE
`await_only_futures` support for extension types

### ISSUE THREAD

**Issue by bwilkerson** [dart-lang/linter#4685]
The `await_only_futures` lint should not generate a lint if the type of the expression is an extension type. It is a compile-time error to `await` an expression whose type is an extension type that doesn't implement `Future`, so the reporting in that case is duplicated.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/c1cacbef5a593f97ed012020ca12f8698111e29f.
