### ISSUE TITLE
Implement DON’T use this. when not needed to avoid shadowing.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#469]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/usage#dont-use-this-when-not-needed-to-avoid-shadowing)

**Comment by JPaulsen** [comment]
Does someone know how to get the variables in scope in a certain part of the code?, It seems like it will be necessary to implement this rule

**Comment by bwilkerson** [comment]
Analyzer doesn't keep that information around, so you'll effectively need to re-compute that data. There is a class (NamespaceBuilder if I recall correctly) that can help. I think we had a utility somewhere that would take an AstNode and return the namespace in force for that node, but I don't remember off-hand where it was. You can probably find it by searching for references to NamespaceBuilder.
