### ISSUE TITLE
unnecessary_lambdas issue

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#474]
I see a lint for:

```dart
onTap: () {
  _inputFieldKey.currentState?.requestKeyboard();
}
```

but it's not completly the same as `onTap: _inputFieldKey.currentState?.requestKeyboard` in the case when `_inputFieldKey.currentState` is null.

**Comment by alexeieleusis** [comment]
@JPaulsen

**Comment by alexeieleusis** [comment]
Fixed with https://github.com/dart-lang/linter/pull/484
