### ISSUE TITLE
`avoid_types_as_parameter_types`  support for extension types

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4744]

**Comment by pq** [comment]
Fixed w/  https://github.com/dart-lang/sdk/commit/2221dc01dc79eacf48a1f616295d6486ee7be05f

**Comment by eernstg** [comment]
(Ah, it's `avoid_types_as_parameter_names`. Not so confusing, then ;-)

**Comment by pq** [comment]
Ha! Quite right!
