### ISSUE TITLE
Update `invariant_booleans` docs to warn of perf issues.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#476]
Follow-up from #434.  As per @JPaulsen's suggestion, we should add some docs to warn of performance in general (though we should still strive to do a bit better).

Consider linking to #434 as well.

**Comment by pq** [comment]
Spitballing text, how about something like this:

> **WARNING:** this lint is comparatively expensive as, in general, calculating [boolean satisfiability](https://en.wikipedia.org/wiki/Boolean_satisfiability_problem) is hard. Performance improvements are planned ([#434](https://github.com/dart-lang/linter/issues/434)) but in the meantime, this lint should be sparingly enabled in large projects or when lint performance is a concern.

cc @JPaulsen @bwilkerson @filiph @alexeieleusis for word-smithing.

**Comment by bwilkerson** [comment]
lgtm

**Comment by filiph** [comment]
Ex-post LGTM!
