### ISSUE TITLE
`avoid_unstable_final_fields` needs specific metadata to declare that a getter is unstable

### ISSUE THREAD

**Issue by eernstg** [dart-lang/linter#4763]
Currently, the lint `avoid_unstable_final_fields` uses an annotation of `@Object()` to indicate that a final instance variable that has this metadata has an unstable getter (otherwise all final instance variables are considered to introduce a stable getter).

In order to make this feature usable we must use some other way to specify this property, e.g., a declaration somewhere (`meta.dart`?) with a relevant name like `unstableGetter`. For example:

```dart
class A {
  @unstableGetter
  final int i;
  A(this.i);
}

class B implements A {
  int _i = 0;
  int get i => ++_i; // No lint, this getter is not required to be stable.
}
```

**Comment by bwilkerson** [comment]
Adding it to `package:meta` seems reasonable.

Would `unstable` be too short, or too likely to conflict with future needs? I'm not sure with the `Getter` suffix adds to the readability, though it might when applied to fields.

**Comment by pq** [comment]
I like `@unstable` (unless @eernstg, you anticipate conflicts down the road)?

**Comment by eernstg** [comment]
`@unstable` would be great, unless we get a lot of push back because it's short and hence conflictable. ;-)

**Comment by lrhn** [comment]
If the annotation only applies to final field declarations, then it's unlikely to conflict with anything else.
If something else can also be "unstable", for some meaning of that, then maybe it can use the same annotation.

I'd use
```dart
@Target({TargetKind.field})
const Object stable = pragma("analyzer: lint-unstable");
```
That signifies that it's an annotation that only the analyzer needs to care about, it's related to lints, and it's marking something as "unstable", without saying anything more precise.

**Comment by srawlins** [comment]
This rule has been removed.
