### ISSUE TITLE
forced unawaied on async set/get

### ISSUE THREAD

**Issue by bsz0206** [dart-lang/linter#4786]
When there is async set/get and the caller is not specifying await it should be warned:

Bad:
class A {
  String get name async => "";
}
m=a.name;

Good:

class A {
  String get name async => "";
}
m=await a.name;

**Comment by srawlins** [comment]
The bad case is illegal code. Please post examples with legal code. Also please use the "lint proposal" form to propose a new lint rule (if that is what you're doing; forgive me for assuming): https://github.com/dart-lang/linter/issues/new?assignees=&labels=lint-proposal%2C+status-pending&projects=&template=lint-proposal.md&title=proposal%3A+%60%3Crule_name%3E%60
