### ISSUE TITLE
Redundant Variable Lint

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#480]
If a local variable is assigned to an instance field and this is not reassigned should be linted

**Comment by bwilkerson** [comment]
I don't understand what you're proposing. Can you provide an example?

**Comment by alexeieleusis** [comment]
```dart
class Foo {
    SomeClass _bar = ...;

    void baz (...) {
        SomeClass redundant = this._bar;
        // do stuff but never reassign redundant
        // if it makes code easier to read, the problem is _bar's name.
    }
}
```

**Comment by JPaulsen** [comment]
And never reassign this._bar too

**Comment by srawlins** [comment]
Closing as this is now the recommended way to promote fields (lift to a local variable).
