### ISSUE TITLE
rule `prefer_expression_function_bodies` does not find all occurrences

### ISSUE THREAD

**Issue by rickypid** [dart-lang/linter#4802]
adding the `prefer_expression_function_bodies` rule does not match all matches within the project.

```dart
  void setPresent(bool value) {
    write('$nodeFullPath."Present"', OpcType.bool, value);
  }
```

**Comment by srawlins** [comment]
Thanks for filing an issue. This rule only reports on function bodies with a single return statement. The function you show does not have a return statement.

If you'd like a rule to suggest expression function bodies for void-returning functions with single statement bodies, you could suggest a new one. We are unlikely to expand the behavior of an existing rule like this; it is a a lot of work to expand behavior in this way.

**Comment by rickypid** [comment]
Thanks @srawlins for reply, 

If you think it is a feasible implementation I would propose it, otherwise I will close this issue.

Thank you.
​

**Comment by bwilkerson** [comment]
The [style guide entry related to this](https://dart.dev/effective-dart/usage#consider-using--for-simple-members) isn't very clear about the preferred way to write the original example.

Given the lack of clear direction here, I'm guessing that we'd end up saying 'no' to such a proposal.

I'm going to close this issue, but if you have an argument in favor of adding the support we'll still see and read it.
