### ISSUE TITLE
Lint to use ??= instead of if statement

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#483]
```dart
  String get fullName {
    if (_fullName == null) {
      _fullName = getFullUserName(this);
    }
    return _fullName;
  }
```
Should be
```dart
  String get fullName {
    return _fullName ??= getFullUserName(this);;
  }
```

**Comment by JPaulsen** [comment]
@bwilkerson @a14n @alexeieleusis, would someone like to propose a name for this rule?

**Comment by alexeieleusis** [comment]
Probably `prefer_conditional_assignation`.

**Comment by a14n** [comment]
`prefer_conditional_assignment` sgtm

**Comment by bwilkerson** [comment]
`prefer_conditional_assignment` sgtm too.

If you're going to provide a quick fix for the lint, though, consider producing
```
String get fullName => _fullName ??= getFullUserName(this);
```

**Comment by JPaulsen** [comment]
Yes, I am thinking about lint and detect this patter in codes:

```dart
if (_fullName == null) {
  _fullName = getFullUserName(this);
}
```

That must be replaced by:

```dart
_fullName ??= getFullUserName(this);
```

But the return and => is not something relevant in this case: maybe we could create another lint to merge some returns with assignment expressions, what do you think about that? to lint this cases:

```dart
String get fullName {
  _fullName ??= getFullUserName(this);
  return _fullName;
}
```

Because if they join them: 

```dart
String get fullName {
  return _fullName ??= getFullUserName(this);;
}
```

Then this [lint](https://github.com/dart-lang/linter/pull/464) will finish to suggest doing what @bwilkerson said:

```dart
String get fullName => _fullName ??= getFullUserName(this);
```

**Comment by bwilkerson** [comment]
Generally speaking, modularity is good, so thinking about splitting this up into a sequence of steps seems reasonable, but we have to weigh that against the extra steps that a user would need to go through.

Assume that we generate a lint that suggests using conditional assignment for the original example:
```
String get fullName {
  if (_fullName == null) {
    _fullName = getFullUserName(this);
  }
  return _fullName;
}
```
It would be much more valuable for the user if we could offer a single fix that would perform all three transformations than if we offered a fix that transformed it into something (conditional assignment followed by a return) that would cause a different lint to be generated where that had a fix that would transform it into something (single return statement) that would cause a different lint to be generated where that had a fix that would finally get rid of the lints (using an expression body).

But that's an issue for when we get to writing a quick fix :-) As far as the rule is concerned, you're right that all you need to look for is code that compares with null before assigning a value.
