### ISSUE TITLE
`deprecated_member_use` in a switch statement results in `non_exhaustive_switch_statements`

### ISSUE THREAD

**Issue by Levi-Lesches** [dart-lang/linter#4852]
**Describe the issue**
When using an enum with a deprecated member, we're forced to consider it in a switch statement/expression or else it won't be exhaustive. But the lint suggests we remove the deprecated reference, breaking exhaustiveness on the switch. 

**To Reproduce**
Here's an example with an enum: 
```dart
enum A { 
  b, 
  @Deprecated("Use A.b instead") c,
}

void test(A a) => switch (a) {
  A.b => print("B"),
  A.c => print("C"),  // Including this gives a lint, removing it gives an error.
};
```
This happens for both switch statements and switch expressions. The same also occurs for sealed class pattern matching: 
```dart
sealed class A { }
class B extends A { }
@Deprecated("Use B instead") class C extends A { }

void test(A a) => switch (a) {
  B() => print("B"),
  C() => print("C"),
};
```

**Expected behavior**
I'd expect the `deprecated_member_use` to not lint in cases where it would be an error to _not_ use the deprecated member.

**Additional context**
This was reproduced on `Dart SDK 3.3.0-279.0.dev` on DartPad's `master` channel.

**Comment by bwilkerson** [comment]
The counter argument is that a deprecated enum constant shouldn't be produced by any code, so there theoretically shouldn't be any way for it to be passed to `test`. At that point you could (though maybe not should) add a `default` (or wildcard pattern) to the switch. When the constant is later removed you'll get a diagnostic telling you that the default is not reachable and you can remove it.

**Comment by srawlins** [comment]
> Problem is, as the author of `test()`, you have no control over what value is passed into your function. Someone on an older, undeprecated version (or someone who simply ignored the lint) might send you a deprecated value anyway.

I think Brian's suggestion still stands.

> At that point you could (though maybe not should) add a `default` (or wildcard pattern) to the switch. When the constant is later removed you'll get a diagnostic telling you that the default is not reachable and you can remove it.

Note that I don't think any of us considered how `deprecated_member_use` would interact with `non_exhaustive_switch_statements`; it's just enums, but also any classes or fields called out in patterns, etc. But I think Brian's solution is elegant.

In cases where the deprecated case is not expected, or cannot be acted on with a specific case, then use a default case. If it is still expected, or should still be received specifically, and acted on specifically, then `// ignore: deprecated_member_use` should be written.

**Comment by Levi-Lesches** [comment]
Looking back, the default case does seem to work as intended, going away when the deprecated member/class is removed. Not sure why I didn't think so before but DartPad can be a bit slow to update lints so maybe that was it. Maybe this should just be the documented workaround instead?

**Comment by lrhn** [comment]
The deprecation warning is correct, whether it is actionable out not.
You are referring to a declaration which will be removed, which is what deprecation warnings are intended to tell you.

In this particular case, simply removing the reference won't leave you with a valid program, so the only thing that we should change is perhaps the suggestion, not whether there is a warning.

You don't have to remove all deprecation warnings from your program, they are only warnings, not errors.
If you decide to not do anything until the ballot is actually removed, which is a reasonable choice for removing an element from an enum, you can use an `// ignore: deprecated_member_use` comment, maybe with a `// TODO`.

You'll have to make a major version increment on the dependency when it ships with the breaking change of removing the value anyway, and the code will stop being valid when you do, so it's not like you can forget to fix it.

**Comment by bwilkerson** [comment]
I'm going to close this issue given that the current behavior isn't necessarily wrong and there's a reasonable work around.
