### ISSUE TITLE
[macros] support for `camel_case_types` (augmented enums)

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#4882]

**Comment by pq** [comment]
Common cases handled in https://github.com/dart-lang/sdk/commit/7b63c20fba83668401aedda0045a5aa2ab952882.

Parser support for enums is still pending so we'll keep this open until that lands and we can add the corresponding support.

(See: https://dart-review.googlesource.com/c/sdk/+/352995.)

**Comment by bwilkerson** [comment]
> Parser support for enums is still pending ...

It's probably also pending for mixins, extensions, and extension types as well.

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/sdk/commit/de84385653631c6283b02f09fb1944f8d8dd3b17
