### ISSUE TITLE
Update `DEPS` to pull in linter `0.1.30`.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#491]
A few items (not ordered):

* [x] tag a `0.1.30` branch
* [x] migrate `DEPS` _back_ to using tags rather than versions
* [ ] verify that name changes (#489) won't break internal users (FYI @srawlins, @matanlurey)

**Comment by pq** [comment]
I believe @srawlins did a spot-check on renames...

**Comment by srawlins** [comment]
Erm, I don't remember doing that.

**Comment by pq** [comment]
Sorry @srawlins, I think @alexeieleusis eye-balled this and I got mixed up.  Anyhoo, I trust you'll tell me if we got it **_wrong_**! 😉
