### ISSUE TITLE
require_trailing_commas highlights the wrong token on named parameter lists.

### ISSUE THREAD

**Issue by sigurdm** [dart-lang/linter#4918]
I have this code
```
Future<void> superFunction(String arg1, String arg2,
    {required String named1, String? named2}) {}
```
I would expect the lint to highlight the closing `}` as that is where I am missing a trailing comma.

The lint highlights the closing `)` instead.

<img width="1132" alt="image" src="https://github.com/dart-lang/linter/assets/8613953/b27d9e1a-4a75-48fe-8b79-98f5c8d8bfa9">

After applying the fix, the code is indeed:
```
Future<void> superFunction(
  String arg1,
  String arg2, {
  required String named1,
  String? named2,
}) {}
```

(I know this might seems small - but it disturbs my inner peace immensely :) )

**Comment by srawlins** [comment]
I'd go a step further and say maybe it should be on the last thing in the list. E.g. in this code:

```
Future<void> superFunction(
  String arg1, {
  String? named2
}) {}
```

It would be better to highlight `String? named2`, which is the line that needs the comma, rather than highlighting the `}` on the next line.

**Comment by bwilkerson** [comment]
I'm not saying that it has to be this way, but the parser usually (maybe always) highlights the token after a missing token, so highlighting the `}` would be consistent with other behaviors.

**Comment by srawlins** [comment]
Fixed by https://github.com/dart-lang/sdk/commit/bcf64bdfeb28d1038bf01991939f518bcadecbe0.
