### ISSUE TITLE
False positive in overridden_fields

### ISSUE THREAD

**Issue by alexeieleusis** [dart-lang/linter#499]
The rule is not verifying that the base class field has the `@virtual` annotation which allows the field to be overridden in strong mode.

**Comment by zoechi** [comment]
AFAIK @virtual is deprecated and shouldn't be needed anymore

https://github.com/dart-lang/sdk/issues/28117 (see Cleanup tasks)

**Comment by alexeieleusis** [comment]
Thanks for the heads up!
