### ISSUE TITLE
Lint to use curly bodies for statements except one-line ifs (Style Guide).

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#5]
Migrated from [dartbug.com/22001](http:dartbug.com/22001):

Should warn or fix if a for, while, or else clause does not have a curly brace body. It should also flag the then clause of an if if it doesn't fit on a single line.

**Comment by seaneagan** [comment]
Does this issue include a "quick fix" to convert overlong one-line if statements to block statements?

**Comment by pq** [comment]
I've been treating lint warnings and fixes as separate requests but maybe we should consolidate.  In any event, your comment is timely because my current focus is getting the linter plugged into the analysis server which is the key to getting fixes implemented (#87) .   Stay tuned!

**Comment by pq** [comment]
My sense is this one is largely subsumed by `curly_braces_in_flow_control_structures` which is enabled in `package:pedantic`.

We can re-open if anyone feels strongly otherwise...
