### ISSUE TITLE
`unawaited_futures` not working in `forEach`

### ISSUE THREAD

**Issue by mgenware** [dart-lang/linter#5005]
**Describe the issue**

Try calling an async func in `forEach`:

<img width="763" alt="image" src="https://github.com/dart-lang/linter/assets/11565096/9713e6c9-36f1-4bf4-b08c-3efda7294c43">

**Expected behavior**

- If `forEach` supports async callbacks, if should report `unawaited_futures`
- If not, it should warn that the async function param might not be awaited

**Additional context**

Flutter (Channel stable, 3.22.2, on macOS 14.5 23F79 darwin-arm64, locale
    en-US)

**Comment by srawlins** [comment]
Thanks for the report! This is a case of https://github.com/dart-lang/linter/issues/836
