### ISSUE TITLE
`comment_references` has trouble with images and links

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#5009]
The `comment_references` fires on the following lines even though it shouldn't:

- https://github.com/flutter/flutter/blob/44622dac46a954b38111fc6ec1de6e2c74065de3/packages/flutter/lib/src/semantics/semantics.dart#L2424-L2425
- https://github.com/flutter/flutter/blob/44622dac46a954b38111fc6ec1de6e2c74065de3/packages/flutter/lib/src/services/autofill.dart#L595-L596

**Comment by goderbauer** [comment]
cc @srawlins

**Comment by srawlins** [comment]
Fixed with https://github.com/dart-lang/sdk/commit/eb57d21bf36eb1dca27b93f35ac841f18d43614f
