### ISSUE TITLE
Lint for existing TODO, FIXME coments

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#51]

**Comment by zoechi** [comment]
TODO seems to be supported in the analyzer directly
https://github.com/dart-lang/sdk/blob/master/pkg/analyzer/lib/src/dart/error/todo_codes.dart

**Comment by bwilkerson** [comment]
Correct. It is supported as a "hint" with a severity of "TODO". IntelliJ shows TODOs in a separate view so as not to clutter the "Dart Analysis" view.

**Comment by rdehouss** [comment]
Why aren't FIXME comments highlighted?
Also, they could/should have another level than INFO, like WARNING?

**Comment by pq** [comment]
I think the way to do this in IntelliJ is by editing the TODO comment inspection.

![image](https://user-images.githubusercontent.com/67586/79127207-52523480-7d56-11ea-9435-e57530ee9b86.png)

You can change the pattern that the inspection matches in preferences as well

![image](https://user-images.githubusercontent.com/67586/79127715-3ef39900-7d57-11ea-9631-5414bdfe92ab.png)
