### ISSUE TITLE
Update AUTHORS.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#511]
@a14n , @JPaulsen : I'd like to put you in Authors...  What emails are most appropriate to list?

Thanks in advance!

**Comment by a14n** [comment]
You can use https://github.com/flutter/flutter/blob/deb71cc6dcf45297ab4fb6e6ccf3d14fb05be9ab/AUTHORS#L14

Thanks

**Comment by JPaulsen** [comment]
Juan Pablo Paulsen
juanpablo.paulsen@gmail.com
(I am an intern so this is my best email)

**Comment by pq** [comment]
Thanks to you both!
