### ISSUE TITLE
Blank Line between class definition and members

### ISSUE THREAD

**Issue by Ignacio1224** [dart-lang/linter#5110]
I'd like to see the class definition following with an empty line before the members, additionally if were possible, a blank line before the last } (curly brace) of the class definition.
Example:

abstract interface class Foo {
// Empty line
  Future<void> bar();
// Optional empty line too!!
}

Without comments:

class Foo {

  const Foo({ 
    required this.bar, 
  });

  final int bar;

}

Thanks in advance for considering the idea, the amazing library you maintain and your time!

**Comment by srawlins** [comment]
Thanks for the issue. The formatter would conflict with both of these requests, so we wouldn't add a style rule to insert the blank lines. To request a change to the formatter, you can file an issue at https://github.com/dart-lang/dart_style/issues.

**Comment by pq** [comment]
Yeah. It'd be hard to justify a lint that would conflict with the formatter's opinions. I'm with Sam. If you think the formatter should have a different opinion here, it'd be best to file an issue [there](https://github.com/dart-lang/dart_style/issues).

Thanks!
