### ISSUE TITLE
Implement AVOID annotating types on function expressions.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#543]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/design#avoid-annotating-types-on-function-expressions)

**Comment by bwilkerson** [comment]
I'm not sure how well this advice works with type inference. There might well be times when we need to annotate in order to avoid strong mode errors. (Just something to check out and keep in mind.)

**Comment by alexeieleusis** [comment]
As a user of the language and the effective dart guidelines, I think this rule makes a lot of sense and if annotating is needed (to help type inference) definitely the expression needs to be extracted to a named function or method.

That said I wonder if a similar approach to how things are done in `omit_type_for_local_variables`, though that needs to have the function expression used as a parameter, which might not always be the case.
