### ISSUE TITLE
Implement AVOID annotating with dynamic when not required.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#550]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/design#avoid-annotating-with-dynamic-when-not-required)

**Comment by bwilkerson** [comment]
The guide says:

> In most places in Dart, a type annotation can be omitted, in which case the type will automatically be `dynamic`.

Note that this is no longer going to be true. With type inference, omitting a type will sometimes cause a type other than `dynamic` to be inferred. Figuring out whether a type is required (even `dynamic`) will be fairly difficult.

**Comment by JPaulsen** [comment]
Yes also if you do this:

```dart
foo () {
}
```
you will not have any lint, but if you do this:

```dart
dynamic foo() {
}
```

you will get the lint that says: "this function declares a type of 'dynamic' but it does not end in a return statement."

**Comment by JPaulsen** [comment]
@bwilkerson is it a way to use some code of the SDK or analyzer to get the return type to be inferred from a function or method declaration?

**Comment by bwilkerson** [comment]
The top-level inference *is* implemented in analyzer, so technically, yes, there should be a way, but there isn't a reasonable public API for it yet. I don't think we considered the need to ask "what if" questions like the one we need here, so it also wouldn't be very efficient at the moment (I suspect you'd have to fully analyze an edited version of the file, which would probably take too long).

I suspect that the only practical answer here is to ignore for now the question of whether the type is necessary to avoid type inference.
