### ISSUE TITLE
Implement AVOID optional positional parameters if the user may want to omit earlier parameters.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#568]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/design#avoid-optional-positional-parameters-if-the-user-may-want-to-omit-earlier-parameters)

**Comment by JPaulsen** [comment]
What we want to implement, is to check that the positional parameters with no default value should go at the end

**Comment by bwilkerson** [comment]
I think a lot of people omit the default value when `null` is the appropriate default value. I don't think you can use the presence or absence of a default value to indicate whether users of an API might want to omit the parameter.

**Comment by JPaulsen** [comment]
Ok, so what should we do?

**Comment by bwilkerson** [comment]
I hate to say this, but perhaps you should skip this rule. I can't think of anything that semantic analysis can tell you about possible future uses of an API, nor about user intent, that you can use to implement this. Not all of the guidelines can be automated.

**Comment by JPaulsen** [comment]
@bwilkerson it is ok, I learnt while implement this, so let's close the issue?

**Comment by bwilkerson** [comment]
sgtm
