### ISSUE TITLE
Implement PREFER making fields and top-level variables final.

### ISSUE THREAD

**Issue by JPaulsen** [dart-lang/linter#575]
From [Effective Dart](https://www.dartlang.org/guides/language/effective-dart/design#prefer-making-fields-and-top-level-variables-final)

**Comment by JPaulsen** [comment]
With @alexeieleusis would like to set that if a top-level variable is public, then it should be final, if it is private, then you accept mutability only in its local file. What do you think @bwilkerson?

**Comment by bwilkerson** [comment]
As the guideline says:

> Of course, it is often useful to have mutable data. But, if you don’t need it, your default should be to make fields and top-level variables final when you can.

The question is, how can you statically determine, without having access to all possible clients of a library, whether a variable *needs* to be mutable? I don't think the visibility of the variable is a good indicator. I mean, if you do need mutable state wouldn't you expect it to be public? How else can clients mutate it?

**Comment by JPaulsen** [comment]
public functions who handles with that private top-variable

**Comment by zoechi** [comment]
Isn't this what `prefer_final_fields` already does?

**Comment by JPaulsen** [comment]
The logic is similar, that rule check if a private class field is not modified in the whole file after it is initialized in the constructors of the class, in that case it should be final, we could do something similar here, it is the other option, but with @alexeieleusis think that this kind of ways to code is not the best (have a mutable top-level variable, and worse a public top-level variable), but we should definitely add what prefer_final_fields does, because what @bwilkerson said.
