### ISSUE TITLE
false hint "Property getter recursively returns itself"

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#586]
![image](https://cloud.githubusercontent.com/assets/405837/24851169/fb3c3e9c-1dd2-11e7-8712-eceb574c6f4c.png)

**Comment by zoechi** [comment]
A similar example 

![image](https://cloud.githubusercontent.com/assets/405837/24868326/fcde9366-1e0f-11e7-8d41-e8adedbadc4f.png)

**Comment by zoechi** [comment]
Friendly ping. This is still an issue.

**Comment by alexeieleusis** [comment]
Now that Q2 is finally over I will schedule some time to go over all the open issues soon.
