### ISSUE TITLE
"Use initializing formals when possible for property" for property of super-class

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#591]
![image](https://cloud.githubusercontent.com/assets/405837/24869993/33b1d2b8-1e15-11e7-9102-688c61208512.png)

Dart does not support that.

**Comment by alexeieleusis** [comment]
Is `baseUrl` an instance field in the base class?

**Comment by zoechi** [comment]
Exactly

```dart
class FhirConnectionImpl extends FhirConnection {
  BaseClient httpClient;
  JsonPrettyPrintService _jsonPrint;
  String baseUrl = defaultFhirServerUrl;
```

**Comment by JPaulsen** [comment]
Thanks for reporting the bug, I will fix it as soon as possible
