### ISSUE TITLE
How to ignore deprecated warning?

### ISSUE THREAD

**Issue by xster** [dart-lang/linter#593]
May be the wrong place to file this but is there a way to disable deprecated warning on one line? Since the // ignore: syntax requires the rule to be in http://dart-lang.github.io/linter/lints and deprecated isn't.

**Comment by alexeieleusis** [comment]
You can also ignore warnings from the analyzer and the same annotation should work, I am surprised it does not work, can you provide an example?

I don't know of any deprecated rule in the linter, but if that is the case, why not just removing it from the analysis options file?

**Comment by xster** [comment]
I want to disable the linter on one specific line only. 

```dart
@Deprecated
void deprecatedMethod() {
  ...
}

void main() {
  // ignore: <what should I put here? leaving it empty or putting 'deprecated' both doesn't disable it>
  deprecatedMethod();
}
```

**Comment by JPaulsen** [comment]
Try with this:

```dart
// ignore: deprecated_member_use
```

**Comment by xster** [comment]
Woohoo! That worked. Should it be documented in http://dart-lang.github.io/linter/lints/ as well?

**Comment by JPaulsen** [comment]
I do not really know, maybe @alexeieleusis or @bwilkerson can answer that, but in my case IntelliJ auto-generated to me.

**Comment by bwilkerson** [comment]
It's a bit confusing, unfortunately, and definitely something we need to improve, but `deprecated_member_use` is a *hint*, not a *lint*, so I don't think it's appropriate to document it with the lints. The `// ignore:` comments can be used with more than just lints.

**Comment by xster** [comment]
Ah, it's indeed a bit complex. Could the lint page link to any other documentations listing 'hints' in the disable one line section?

**Comment by pq** [comment]
We call out docs for [analysis configuration](https://www.dartlang.org/guides/language/analysis-options#the-analysis-options-file) in the [README](https://github.com/dart-lang/linter/blob/master/README.md).  For now maybe this is good enough?  Optimistically closing.
