### ISSUE TITLE
linter docs (on the readme) should be updated to explain how to change a lint's severity

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#645]
We should tell people how to change the severity of lints; I'm not up to speed on where all lints are documented, but the https://github.com/dart-lang/linter/blob/master/README.md may be a good place to do this.

**Comment by zoechi** [comment]
> I'm not up to speed on where all lints are documented

are you looking for 

> are catalogued [here](http://dart-lang.github.io/linter/lints/)

(contained in https://github.com/dart-lang/linter/blob/master/README.md)?
