### ISSUE TITLE
Cleanup and unify labels.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#647]
Specifically, we should align them with the SDK to ease moving issues back and forth.

**Comment by pq** [comment]
@kevmoo @devoncarew : is there a write-up anywhere of the SDK labels?  There seem to be a fair number of defunct ones.  Do we have a triage process written up?

**Comment by pq** [comment]
Update:  looks like triage process is captured on the wiki here:

https://github.com/dart-lang/sdk/wiki/Triaging-Dart-SDK-Issues

**Comment by devoncarew** [comment]
The sdk repo may pick up stray labels when people use the github issue mover - you end up with one-off labels from the source repo.

**Comment by pq** [comment]
Ah, I've seen that too but wasn't 100% sure that's how it was happening.  Thanks for confirming! 👍

**Comment by pq** [comment]
First cut done.
