### ISSUE TITLE
Make isValidPackageName public

### ISSUE THREAD

**Issue by goderbauer** [dart-lang/linter#654]
For Flutter (and anybody else, who is programmatically creating packages (e.g. to give the user a template to start with)), it would be great if `isValidPackageName` from `package:linter/src/rules/pub/package_names.dart` would be public.

**Comment by pq** [comment]
Interesting!

Or, maybe better still, it'd be great if `pub` provided a package that defined this validation.  We've talked about this a bit but I don't think a `pub` library has much of a chance of materializing.  (cc @munificent @nex3 in case that's changed.)

That aside, if we do provide this as a service of the linter, I'd propose we break it away from the lint rule and provide some kind of service API.

cc @bwilkerson for thoughts on that.

Thanks @goderbauer!

**Comment by bwilkerson** [comment]
Yeah, this definitely feels like something that belongs in the 'analyzer' package (if it isn't in a more general package). I can easily imagine plugin authors wanting to use it as well.

**Comment by pq** [comment]
@bwilkerson : are you willing to take on a new "validation" API?  A few possible downsides to hosting in `analyzer`:

  * yet another bit of surface area to manage
  * more pressure to publish
  * we may want to expand to embrace programmatic validation that extends beyond the analyzer (and be more opinionated to boot)

In an case (and either way), let's discuss! 👍

**Comment by bwilkerson** [comment]
I'm fine with having the functionality somewhere other than 'analyzer' as long as it is in a general purpose package. I don't think 'linter' is general purpose, and I think lots of code that could use this utility won't want to introduce a dependency on 'linter'. Of the existing packages, I think 'analyzer' is the best fit (after 'pub', but I'm not sure a dependency on 'pub' would be any more welcome).

> yet another bit of surface area to manage

That's true no matter which package it goes in.

> more pressure to publish

I wouldn't expect the definition of what is or isn't a valid package name to change much over time, so I don't think there will be any additional pressure.

> we may want to expand to embrace programmatic validation that extends beyond the analyzer (and be more opinionated to boot)

I don't understand what you mean by this.

**Comment by pq** [comment]
> I wouldn't expect the definition of what is or isn't a valid package name to change much over time, so I don't think there will be any additional pressure.

I just mean that regular releases of `analyzer` have been tricky.

>> we may want to expand to embrace programmatic validation that extends beyond the analyzer (and be more opinionated to boot)

> I don't understand what you mean by this.

Sorry, I mean we might want to validate frameworks that we don't want to have `analyzer` be aware of.  But maybe that's too academic?

**Comment by Hixie** [comment]
This is now a Flutter blocker because the member we were relying on has been made private in the latest linter package and so we can no longer upgrade our dependencies.

**Comment by pq** [comment]
For anyone reading along, here's some context.

In [create.dart](https://github.com/flutter/flutter/blob/master/packages/flutter_tools/lib/src/commands/create.dart#L370), flutter tools accesses linter internals like this:

```dart
  if (!linter_utils.isValidPackageName(projectName))
    return '"$projectName" is not a valid Dart package name.\n\n${package_names.details}';
```
where warnings on the implementation imports are suppressed like so:

```dart
import 'package:linter/src/rules/pub/package_names.dart' as package_names; // ignore: implementation_imports
import 'package:linter/src/utils.dart' as linter_utils; // ignore: implementation_imports
```

The breakage is that the `details` constant in `package_names.dart` became private with https://github.com/dart-lang/linter/pull/830.

A quick (though in elegant) fix would be to access the value from the `LintRule` getter instead, caching it for checking something like this:

```dart
final String packageNameDetails = new package_names.PubPackageNames().details;
```

@Hixie : how does this sit with you?  We can certainly finish the though and come up with a proper API for accessing rule details but would this get you by in the meantime?

**Comment by Hixie** [comment]
Changing our current hack to a different hack is fine by me.

**Comment by pq** [comment]
I was hoping you'd say that! 👍
