### ISSUE TITLE
sort_constructors_first should ignore static members

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#696]
I would like to keep static members and instance members separated but sort_constructors_first complains about a static getter before the constructor.

**Comment by pq** [comment]
@scheglov : is this in agreement with how the server "sort members" action works in server?

**Comment by scheglov** [comment]
"Sort members" puts static fields on the top, and static methods on the bottom of classes.
See [the source](https://github.com/dart-lang/sdk/blob/fb982f547620032f57d6111b1017ce0278a4a0ba/pkg/analysis_server/lib/src/services/correction/sort_members.dart#L27) for the exact order (static, kind, private).

**Comment by pq** [comment]
Thanks @scheglov .

Thinking on this some more, I believe @Hixie motivated this one for flutter style.  @Hixie: any objections?

**Comment by Hixie** [comment]
The Flutter style is to have constructors be strictly first, before anything else including statics, such that you can at a glance look at a class and tell if it has an implied constructor or not.

If there's anything that could be before the constructor, then you have to carefully look at each thing until you get to something you know can't be before a constructor to determine if you have an implied constructor, which makes the code slower to read.

**Comment by pq** [comment]
Ah, K.  I remember this rationale.  Thanks.

@zoechi : it sounds like this rule isn't quite what you want.  If you want to enforce a different ordering rule, feel free to open up a new issue to track.  Thanks!
