### ISSUE TITLE
cascade_invocations conflict with null operator

### ISSUE THREAD

**Issue by AdalbertoLacruz** [dart-lang/linter#701]
Linter generates a false error with this code:

error ??= something;
error
   ..val1 = 1
   ..val2 = 2;

**Comment by dustyholmes-wf** [comment]
I ran into this yesterday, we resolved by wrapping the assignment in parenthesis. 

(error ??= something)..val1=1

I'd really prefer not to have to do that though.

**Comment by AdalbertoLacruz** [comment]
Something strange, but it's a solution.

Thanks.
