### ISSUE TITLE
suggestion: method overrides should use the same argument names

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#702]
I've hit this a few times w/ the SDK where the dartdoc is inherited w/ an overridden member – and the docs are "broken" because the arg name changed in the override.

I'd argue it's good to keep alignment w/ the superclass.

**Comment by matanlurey** [comment]
Isn't this a dartdoc issue?

**Comment by kevmoo** [comment]
Eh, maybe?

I someone overrides a method and changes the argument names – what should dartdoc do?

Should it try to rewrite the references in the content? Possibly error prone.
I'd rather say folks should try to align with the thing they are overriding.

Just a thought...

**Comment by srawlins** [comment]
Implemented as [avoid_renaming_method_parameters ](http://dart-lang.github.io/linter/lints/avoid_renaming_method_parameters.html)
