### ISSUE TITLE
Make // ignore easier to use

### ISSUE THREAD

**Issue by xster** [dart-lang/linter#706]
The current syntax forces ignores to be in the shape of

```
// Explain why the ignore is here for readers
// ignore: rule
expressionThatCausesWarning();
```

whereas it would be a lot more natural if it could be 

```
// ignore(rule): explain why it's ignore in
// possibly more than one line of comments
expressionThatCausesWarning();
```

**Comment by xster** [comment]
What do you guys think? :)

**Comment by Hixie** [comment]
The following style should work currently and is what I would recommend for Flutter code:
```dart
expressionThatCausesWarning(); // ignore: rule, explain why
```

**Comment by Hixie** [comment]
Or:
```dart
  // explanation
  expressionThatCausesWarning(); // ignore: rule
```

**Comment by xster** [comment]
I've used the latter for now. I'm a little worried about the possible side effects of reappropriating the `// ignore: rule_1, rule_2` syntax for non functional things

**Comment by pq** [comment]
This issue was moved to dart-lang/sdk#33560
