### ISSUE TITLE
Investigate Appveyor failures

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#714]
For example: https://ci.appveyor.com/project/pq/linter/build/1.0.1098.

@devoncarew, @kevmoo : any thoughts?

**Comment by kevmoo** [comment]
Pub server error. Retry?

**Comment by pq** [comment]
I thought it was happening a lot but it looks like it was in a short window.


![image](https://user-images.githubusercontent.com/67586/27446455-7a191d5a-5732-11e7-8fdc-2b2c5e836bfa.png)

Optimistically closing.
