### ISSUE TITLE
only lint with prefer_interpolation_to_compose_strings when one using at least one string literal

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/linter#735]
Hey there, I think I came across an issue with the `prefer_interpolation_to_compose_strings` lint. When combining two non-literal strings I still get the lint, it seems odd that I should create a new string literal just to combine two existing strings.

```dart
var str1 = 'Hello';
var str2 = 'World';

// This lints, but I wouldn't expect it to.
var str3 = str1 + str2;
```

**Comment by alexeieleusis** [comment]
I agree with your point, but your example seems a bit artificial (given that you could have had just one constant from the beginning). In the instances where I have seen this, either string interpolation or using  a stringbuffer result in more readable (or efficient) code. Does this example reflect the issue you had in your code? Can you provide a closer one if not?

**Comment by jacehensley-wf** [comment]
This is pretty close to what we have in our code base:

```dart
var listOfStrings = [];
  
var baseString = 'base';
  
var values = [
  'value1',
  'value2',
  'value3',
  'value4',
  'value5',
  'value6',
];
  
for (var value in values) {
  listOfStrings.add(baseString + value);
}
```

**Comment by pq** [comment]
Thanks for the example @jacehensley-wf!
