### ISSUE TITLE
Add explanation or reasoning for each lint

### ISSUE THREAD

**Issue by jacehensley-wf** [dart-lang/linter#736]
It would be nice if each lint had a description around why it was implemented and the benefit it provides. It would make turning on some lints easier to justify if the thought behind it was know.

**Comment by alexeieleusis** [comment]
I am assuming this is in addition to http://dart-lang.github.io/linter/lints/ 
Or expanding those is enough? I think some of them are too brief.

**Comment by jacehensley-wf** [comment]
I think adding to those would be enough. Like why should we use StringBuffer? It's not super obvious that it's for perf gains.

**Comment by pq** [comment]
This is ongoing work.  Let's keep tracking in more targeted follow-ups (like #1025).
