### ISSUE TITLE
`directives_ordering` doesn't report directives that are out of order lexically

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#738]
From a (perhaps incorrect) test, it doesn't look like `directives_ordering` complains when directives are incorrectly ordered lexically within the same group (package:bbb, package:aaa).

**Comment by pq** [comment]
Confirmed.  The rub is that we are creating these errors (and there are tests to verify) but the way we are doing it does not play nice w/ the new analysis driver.  We'll need to fix that (https://github.com/dart-lang/linter/issues/743) and debug from there.

**Comment by pq** [comment]
Hoping this is fixed w/ #754.  Will verify once this change has made it's way into the SDK. 👍

**Comment by pq** [comment]
Should be fixed in the latest dev SDK.
