### ISSUE TITLE
Inline regexps defined in analyzer `util.dart`.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#769]
ATM we depend on regexps that are defined in the `analyzer` package for some of our lints.  This makes changing them hard (e.g., #684) and doesn't add any real benefit (IMO); also note that the tests live in the linter while the definitions are in the analyzer --- another odd coupling!

**Comment by bwilkerson** [comment]
> ... and doesn't add any real benefit ...

The (possibly only theoretical) benefit is that these utility methods are available for all clients of the analyzer code base, not just the lint rules. Given the number of clients, it seems quite likely that these would be of use to more than the lint rules.

If you do pull them back out of the analyzer, note that this is a (potentially) breaking change and that you ought to put some effort into making sure that there are no other users.

> ... the tests live in the linter while the definitions are in the analyzer ...

Well, that's just wrong! The tests of the utility methods need to be moved into analyzer (assuming that the utility methods aren't removed from analyzer, of course).

**Comment by pq** [comment]
As per our discussion, deprecating (but not removing) analyzer utility methods:

https://codereview.chromium.org/2989363002/
