### ISSUE TITLE
"Specify type annotations" identifies AngularDart pattern as breaking rule

### ISSUE THREAD

**Issue by Stargator** [dart-lang/linter#776]
```dart
    directives: const [COMMON_DIRECTIVES],
```

In AngularDart, you can identify directives (custom or built-in) by declaring a list which is a mix of List<List<Type>> or whatever component the application has custom-created.

The top example is taken from https://github.com/angular-examples/toh-1

I bring this up either to understand if there **is** a way to specify type within this context, if the linter can be updated to take into account this example, or if I'll just have to ignore it.

**Comment by alexeieleusis** [comment]
Can you provide more specific links to what is linted?

**Comment by Stargator** [comment]
@alexeieleusis Sure, give me a moment

**Comment by Stargator** [comment]
[Here is a branch with linting of always_specify_types enabled](https://github.com/Stargator/dart_toh/tree/sample).

Via the analyzer you should see it highlighting common syntax within AngularDart as issues. But the types could not be easily set some of these cases

**Comment by zoechi** [comment]
One of these should do what you need
```
directives: const <dynamic>[COMMON_DIRECTIVES],
```
```
directives: const <Object>[COMMON_DIRECTIVES],
```

**Comment by Stargator** [comment]
@zoechi Thanks. That helps. It wasn't clear to me. And based on your feedback I figured out the one at the top of app_test.dart.
