### ISSUE TITLE
comment_references: Parameters of new typedef

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/linter#779]
Lints:

```dart
/// Defines a function that connects to a web socket [url].
typedef WebSocketFactory = Future<WebSocketClient> Function(String url, {
  Map<String, String> headers,
});
```

...

but the old-style typedef works just fine.

**Comment by pq** [comment]
@bwilkerson @scheglov: I can confirm this.  I'm guessing it's a limitation of the analyzer parser?

**Comment by bwilkerson** [comment]
That sounds reasonable, but I don't know for sure. If it, it's probably because the parameters are not getting included when building the name scope for the typedef. (Probably in NamespaceBuilder.)

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/16620

**Comment by scheglov** [comment]
https://dart-review.googlesource.com/c/sdk/+/16620

**Comment by pq** [comment]
Wow.  Awesome.  Thank you @scheglov !
