### ISSUE TITLE
Consider removing lint kinds (Kind.{DO,DONT,PREFER...})

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#78]
In the spirit of [Tricorder](http://research.google.com/pubs/pub43322.html)'s approach, I think we should consider removing severities.  I think severities are contentious at best and ultimately subject to override anyway.

EDIT: severities == kinds.

**Comment by lukechurch** [comment]
TLDR: sgtm.

The sliding scale caused meshing problems with different teams, that impeded work. I think we're probably better having 2 priorities, on and off, that be configured per team.

This avoids adding any more complexity to story we have around Errors/Warnings/Hints/Lints.

We can always add more flexibility later, taking it away isn't so easy.
 
So yeah - removing for now sounds good.

**Comment by pq** [comment]
Thanks for chiming in Luke.  That's exactly my thinking.

Cheers!
