### ISSUE TITLE
avoid_returning_this complaints should highlight the return not the function

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#780]
Just a nit

![image](https://user-images.githubusercontent.com/405837/30472394-7130a12e-99fc-11e7-884e-698321dd9de3.png)

(generated code from built_value)

I found this confusing because the getter name contains `this` as well.
If it's a longer body with multiple returns, it can be cumbersome to locate the issue.

**Comment by alexeieleusis** [comment]
We thought about that possibility back when it was implemented, but then what happens if there are more than one return statement with this? Might be a bit noisy, I am fine with both approaches.

On the other hand, having a way to exclude generated code would help too.

**Comment by zoechi** [comment]
In built_value David added `// ignore_for_file: ...` for rules that cause issues
But being able to add glob + ignore in analysis_options.yaml would be better, because it would work for all generators.

I think with multiple such returns it would still be better to highlight each one. 
If this rule should be suppressed it can be for the whole file.
I guess if it's used on time, multiple are intentional as well.
