### ISSUE TITLE
Conflict between always_specify_types and avoid_annotating_with_dynamic?

### ISSUE THREAD

**Issue by yyoon** [dart-lang/linter#789]
```dart
void foo(dynamic value) {
  value.doSomething();
}
```

This lints with `avoid_annotating_with_dynamic`, but when I remove the type it lints with `always_specify_types`. Are they not supposed to be used together?

**Comment by matanlurey** [comment]
Just use `Object`?

**Comment by yyoon** [comment]
Well in the example above, it would be an error because `Object` doesn't have `doSomething()` method.
It's more of a contrived example though, and we would normally use more specific type that implements `doSomething()`.

To add a bit more context, we use a dynamic parameter mostly when dealing with json objects. So an example code would look like:

```dart
factory Foo.fromJson(dynamic json) {
  return Foo(
    id: json['id'],
    name: json['name'],
    // ...
  );
}
```

In this case we can't simply change this to `Object` because we can't use the `[]` operator on `Object`.

**Comment by matanlurey** [comment]
This could potentially perform badly in AoT if not inferred, so wouldn't `Map` make sense:

```dart
factory Foo.fromJson(Map<String, Object> json) { ... }
```

In general Dart 2.x greatly discourages duck-typing a `dynamic`.

**Comment by yyoon** [comment]
I guess we could do that. Is dynamic a bad thing to use in general, or are there other specific cases where dynamic would be still useful? If it's bad, then we might consider not using dynamic at all.

**Comment by matanlurey** [comment]
This is a sometimes controversial topic, but _I'd_ never use `dynamic` if possible.

**Comment by yyoon** [comment]
Okay. Good to know. I can change our code to use more specific types (`Map<String, Object>` for example). Please feel free to close this.
