### ISSUE TITLE
Conditions must have a static type of 'bool'. (non_bool_condition at ...)

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#797]
```
Conditions must have a static type of 'bool'. (non_bool_condition at ...)
```
```
primary ?? -1 > Colors.primaries.length
```
with
```
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
```
![image](https://user-images.githubusercontent.com/405837/31350400-4c07248e-ad27-11e7-974c-d4347e2816a1.png)

**Comment by zoechi** [comment]
When I set the rule to be ignored I get

```
info: Always false because length is always greater or equal 0. (prefer_is_empty at ...)
```
![image](https://user-images.githubusercontent.com/405837/31350604-11df5118-ad28-11e7-97f5-2fc1f4139c77.png)

**Comment by bwilkerson** [comment]
What is the type of `primary`?

**Comment by zoechi** [comment]
`int`
```
final primary = prefs.getInt(ThemeState.kPrimaryColorKey);
```

**Comment by bwilkerson** [comment]
Given that the type of `primary` is `int` and the type of `-1 > Colors.primaries.length` is `bool`, then the type of `primary ?? -1 > Colors.primaries.length` is `Object` (the least upper bound of `int` and `bool`).

Did you intend to write `(primary ?? -1) > Colors.primaries.length`?

**Comment by zoechi** [comment]
ouch, thanks
was a tough day ;-)
