### ISSUE TITLE
non_constant_identifier_names: Lints new Function syntax

### ISSUE THREAD

**Issue by matanlurey** [dart-lang/linter#805]
```dart
// ignore: non_constant_identifier_names
T scope<T>(T Function() run) { /* ... */ }
```

`Function` is not the name of the parameter, so this should be fine.

**Comment by aemino** [comment]
I'm using SDK version `1.25.0-dev.14.0` and I don't have this issue. Also, couldn't you declare that parameter as `(T run())`?

**Comment by matanlurey** [comment]
This is on a later version of the SDK.

I could but that syntax is soft deprecated

**Comment by aemino** [comment]
Ah, thanks for letting me know!

**Comment by pq** [comment]
cc @bwilkerson

**Comment by pq** [comment]
I can no longer reproduce this on bleeding edge so I'm inclined to think that the underlying issue in analyzer has been fixed.  Let's leave this open for a bit and see what shakes out.

Thanks for the report @matanlurey !

**Comment by pq** [comment]
Closing in favor of a test that will fail if a dev build gets pushed that breaks in a similar way: https://github.com/dart-lang/linter/commit/e7fd27d23b50792df113ad59633c74ad58a44e83.
