### ISSUE TITLE
prefer_interpolation_to_compose_strings should not lint += assignements

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#813]
I find it makes code harder to read and more error prone:

```dart
log += ' paint';
// vs.
log = '$log paint';
```

With the `+=` version it is clear that we append something to `log`. With the interpolated version the variable name is duplicated and it's easier to make typo like `_log = '$log paint'`.

**Comment by pq** [comment]
I tend to agree.

cc @bwilkerson @alexeieleusis

**Comment by bwilkerson** [comment]
@munificent The style guide only discusses the use of `+`. Should this also apply to `+=`?

**Comment by munificent** [comment]
I think "+=" is perfectly fine to use on strings.
