### ISSUE TITLE
Do analysis and linting in one go

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#82]
From what I learned is the linter something like a plugin to the analyzer.
At least when I run the linter I get the same errors like when I run the analyzer (http://dartbug.com/23046)

I have an issue with the analyzer (see http://dartbug.com/23049) which seems to be solved in the linter already.

Currently when I run the linter, analyzer hints/warnings are not shown, only linter hints/warnings.

Do you think it makes sense to integrate both so that I just run the linter and get *analyzer and linter* hints/warnings?
It would probably be a lot more efficient when I want to run both which I usually do (at least from command line).
Or is it supposed to work like this anyway but just doesn't yet?

**Comment by bwilkerson** [comment]
I think it makes sense to have one command-line tool for analyzing Dart code. The linter is still in early stages, and having it as a separate tool makes it faster to develop, but it probably won't stay a separate tool forever.

**Comment by zoechi** [comment]
Good to know. 
Davon already pointed out a simple workaround which works fine https://github.com/google/grinder.dart/issues/155#issuecomment-88117161

**Comment by pq** [comment]
What Brian said.  The current thinking is to make the `linter` a plugin for the `analyzer` and provide something like an `--enable-lints` flag for the analyzer CLI that will enable it.

**Comment by zoechi** [comment]
Lints are integrated into the analyzer. This fixes it for me.
