### ISSUE TITLE
prefer_function_declarations_over_variables should only lint final elements

### ISSUE THREAD

**Issue by a14n** [dart-lang/linter#823]
otherwise you can not change the value of the variable

```dart
var f = () => true; // LINT
f = () => false;
```

 and the change leads to error:

```dart
f() => true; // OK
f = () => false; // ERROR
```

**Comment by bwilkerson** [comment]
Either that, or the lint should check to see whether the variable is re-assigned somewhere and not produce a lint if it is. That way the lint could still catch cases where `final` isn't used but a function declaration would work fine.

**Comment by a14n** [comment]
Agree for local variables. I mentioned `final` especially for class fields and top level variables.

**Comment by a14n** [comment]
We could also limit the lint to `final` local variable. The combination with `prefer_final_locals` could be enough.

**Comment by bwilkerson** [comment]
That assumes that users always use both, which might not always be the case :-) I think each lint should be useful on its own.
