### ISSUE TITLE
Suspicious output from `flutter analyze` after upgrade to linter 0.1.37

### ISSUE THREAD

**Issue by yjbanov** [dart-lang/linter#824]
We see a lot of output like the following after upgrading to linter `0.1.37`:

```
analyzer stderr: Exception while using a _Visitor to visit a CompilationUnitImpl
```

The process does not crash, but the risk is that it might be linting incorrectly. So this is a high priority issue.

Full output: https://flutter-dashboard.appspot.com/api/get-log?ownerKey=ahNzfmZsdXR0ZXItZGFzaGJvYXJkclgLEglDaGVja2xpc3QiOGZsdXR0ZXIvZmx1dHRlci81YjM1NzUwMDZlNTJjZTNmMmRmMmVlMzE5YmRhYWIwYjU3NTBkZWEyDAsSBFRhc2sYgICAgIDkyQkM

**Comment by yjbanov** [comment]
We decided that we will roll back, but that makes it a P0 for me, as I'm unable to continue any i18n work until this is fixed.

**Comment by bwilkerson** [comment]
@devoncarew Is this related to the issue you were going to look at?

**Comment by devoncarew** [comment]
Yes, I think this is https://github.com/dart-lang/linter/issues/822.

**Comment by yjbanov** [comment]
I'm in a less panicky mood this morning. I might get unblocked by tweaking our upgrade script to keep the `linter` dependency artificially pinned to 0.1.35 (fingers crossed!). I will lower the priority once I confirm that 0.1.35 functions properly with all the other package upgrades.

**Comment by yjbanov** [comment]
I'm unblocked (phew!), dropping priority to medium. However, Flutter won't be able to upgrade `linter` while this bug is still there, and eventually that will start causing our versions to lag.

**Comment by devoncarew** [comment]
There's a new version of the linter out with the fix - `0.1.38` (thanks @pq). It's worth patching in to see if it does address the issue.

**Comment by yjbanov** [comment]
Looks promising! https://github.com/flutter/flutter/pull/12737

**Comment by pq** [comment]
Sweet!  This will be in the SDK as of https://github.com/dart-lang/sdk/commit/87820ba6866aa2c6d5d5eabcaceaa7ee5420adcd, though I note it just missed today's dev build. 😢

**Comment by yjbanov** [comment]
Our build is green on `0.1.38`. Closing. Thanks!
