### ISSUE TITLE
Lint for hashCode implementation referencing mutable fields

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#83]
http://blog.mgm-tp.com/2012/03/hashset-java-puzzler/

**Comment by krisgiesing** [comment]
This would have saved myself and a teammate about 12-16 hours of combined debugging time over the past week, FWIW.

**Comment by krisgiesing** [comment]
The original link above appears to be dead, but more context on this issue can be found at https://dart.dev/guides/language/effective-dart/design#avoid-defining-custom-equality-for-mutable-classes

**Comment by Hixie** [comment]
Also `operator ==` should not be allowed on mutable objects.

**Comment by krisgiesing** [comment]
Should I interpret your statement as saying we should warn if people define `operator ==` on classes not marked as `@immutable`? This is a slightly different (and more strict) lint than I was imagining here.

**Comment by Hixie** [comment]
That would probably be ideal but I'm not too worried about how we do that.

**Comment by krisgiesing** [comment]
OK. I'm working on a PR right now.
