### ISSUE TITLE
Linter website

### ISSUE THREAD

**Issue by aemino** [dart-lang/linter#835]
I was looking around and I realized that the website hasn't been updated in a few months.  I don't have too much time on my hands, but I thought it might be a fun project to attempt redesigning the site, unless there are already plans to do so.  Also, I was wondering about what frameworks/technologies would be preferable.

**Comment by pq** [comment]
This would be awesome!  There aren't any specific plans to do anything but I'd be all for helping.  (FWIW, in particular, the CSS for the rule pages was *very* hastily thrown together and intended to only be provisional; I just never found anyone keen enough to take it on!)

Anyway, how about we start by enumerating some of the improvements you envision?  I'd love to hear more about what you have in mind.

**Comment by aemino** [comment]
I was thinking of doing something somewhat similar to `eslint`'s website, where they have a basic setup; search bar for searching for rules, as well as some dropdowns for the users (how to set up the linter) and for potential contributors (how to create rules and such.)

**Comment by pq** [comment]
It looks like they use [algolia](https://www.algolia.com/) for search.  Not sure if they have open-source licensing?

Anyway, I agree it's slick.  For reference, here it is in action:

![image](https://user-images.githubusercontent.com/67586/32389805-228c28dc-c089-11e7-8e99-8ab203369d61.png)

https://eslint.org/docs/rules/

Something like this would be fantastic for sure! 👍

**Comment by aemino** [comment]
I'm more wondering if you have a preference for front-end technologies.  I have my framework preferences, but it seems that Dart's "family" websites (pub, linter, dartlang.org) use mostly HTML templating engines, so I'm not sure whether or not I should deviate from this trend.

**Comment by pq** [comment]
Great question!  I don't personally have a strong feeling about this.  Curious if @filiph or @kevmoo do though.

**Comment by kevmoo** [comment]
AngularDart is **awesome** (for single-page apps).

If you care about SEO – which I think you do – it may not be the best option.

**Comment by aemino** [comment]
In what way does AngularDart hinder SEO? I'm considering using it (though I'm most familiar with React as a frontend framework.)

**Comment by kevmoo** [comment]
> In what way does AngularDart hinder SEO? I'm considering using it (though I'm most familiar with React as a frontend framework.)

Content within components is dynamic – it's generated at runtime.

Most search engines don't run script on the page. So if you're content is generated by script, it may not be indexed.

**Comment by aemino** [comment]
Unless I'm mistaken, I think that Google and some other search engines *do* run scripts for a few seconds.  More and more websites are adopting virtual DOMs, and I don't see any visible SEO issues with these sites.  Of course, I might be wrong here, so let me know if that's the case! 🙂

**Comment by kevmoo** [comment]
@aemino – I'm glad! My data may be a bit old, too.

**Comment by filiph** [comment]
I don't recommend using SPA for docs for the following reasons:

* SEO. Yes, even in this day and age: https://goralewicz.com/blog/javascript-seo-experiment/
* Load speed, especially on mobile. If we can get a static page, that's going to load in under a second, which is what you want for documentation. This really matters.
* User experience. It's relatively easy to build a SPA, but it's quite hard to make it perform the same as people expect. I'm talking about all the edge cases in back button, deep linking, opening in new tab, etc.
* As an SPA, docs are much less likely to be crawled by tools like Dash.

Of course, there's a balance between the points above and the cost of development. If building a SPA is 2x cheaper/faster and we're optimizing for delivering the page fast, we'll want to take that into consideration.

**Comment by aemino** [comment]
Perhaps isomorphic rendering is a possibility. Not sure how I would go about implementing that with Dart, but it seems from what you're saying that SPA probably isn't the best option. 🙂

**Comment by kevmoo** [comment]
>  it seems from what you're saying that SPA probably isn't the best option.

Weird place for this discussion, but it's important.

If you `curl` nytimes, you'll see the content in line. Definitely not an SPA, although they light up a light with JS

gmail, google map, etc are the opposite – SPA all the way.

Depends where your site is on the spectrum.

**Comment by pq** [comment]
Awesome conversation.  I don't have a ton to add on implementation but would love to see something along any of these lines happen! 👍

**Comment by pq** [comment]
@aemino : if you're interested in pitching in here, please re-open.  Closing as stale in the meantime.

Thanks!
