### ISSUE TITLE
Dependency on args package should be bumped to allow args 1.0

### ISSUE THREAD

**Issue by leafpetersen** [dart-lang/linter#853]
The pubspec.yaml for linter specifies args at < 0.14 . There is now a 1.0 version of args.

This is blocking rolling flutter to the 2.0 SDK, see flutter/flutter#13223 .

cc @kevmoo @mit-mit

**Comment by pq** [comment]
I'm looking now at broadening this constraint.  @kevmoo : any idea why the SDK is still on [0.13.7](https://github.com/dart-lang/sdk/blob/master/DEPS#L47)?

**Comment by kevmoo** [comment]
I think it's just behind...no reason AFAIK

**Comment by leafpetersen** [comment]
Awesome, thanks!
