### ISSUE TITLE
Add "always call super.attached()" and "always call super.detached()" rules

### ISSUE THREAD

**Issue by kelegorm** [dart-lang/linter#873]
In web development it's usual mistake to forgot call super methods for `attached` and `detached`. sometimes it's cause errors, sometimes - doesn't. While Element doesn't have @mustCallSuper annotation let's have such lint rule.

**Comment by zoechi** [comment]
Wouldn't it be easier to add `@mustcallsuper`?

**Comment by kelegorm** [comment]
Somebody can do it I guess. Can you?

**Comment by srawlins** [comment]
Closing in favor of adding `mustCallSuper` to Element; we cannot support special case rules in this package.
