### ISSUE TITLE
`prefer_const_constructors` doesn't take into account implicit creation

### ISSUE THREAD

**Issue by devoncarew** [dart-lang/linter#910]
From https://github.com/flutter/flutter/issues/15023, It's likely that `prefer_const_constructors` doesn't take into account implicit `const` creation.

**Comment by pq** [comment]
Thanks for the report!

I've got this reproduced in the latest Flutter SDK (using linter 0.1.43).  Looking now to see if it's been fixed by @a14n's recent work in the area...

**Comment by pq** [comment]
Confirmed 👍 .

Using linter 0.1.43:

![image](https://user-images.githubusercontent.com/67586/36872977-f34b0b76-1d5b-11e8-9e7f-ab2d1fbc5e66.png)

Using head:

![image](https://user-images.githubusercontent.com/67586/36872996-09aa9972-1d5c-11e8-97ca-5e5cbce37894.png)

I'll look at publishing a new linter in the next few days to get this fix out for integration into the Flutter SDK.

**Comment by devoncarew** [comment]
Awesome! Thanks for digging into it.

**Comment by pq** [comment]
Fixed by @a14n  in 0.1.44 🎉
