### ISSUE TITLE
False positive in `invariant_booleans`.

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#914]
![image](https://user-images.githubusercontent.com/405837/37205901-d8f56fa0-2396-11e8-93e6-ae1bac413364.png)

It doesn't seem to recognize that there is still the uncovered case where both are equal

**Comment by bwilkerson** [comment]
@alexeieleusis

**Comment by srawlins** [comment]
We've deprecated `invariant_booleans` and will not be fixing correctness bugs going forward.
