### ISSUE TITLE
Publish 0.1.44

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#915]
I'd like to do this in the next few days...

@a14n: are you OK doing this before #904 lands?  

Any other changes folks want to see make it or are we at a good steady state?  

(FWIW I'm happy to make a quick follow-up pull in the next if, for example, we want to get any fixes out quickly.)

/cc @alexeieleusis @bwilkerson @a14n

**Comment by a14n** [comment]
I was on vacations. Not sure I can move #904 forward quickly. Feel free to publish without this new lint.

**Comment by pq** [comment]
Sounds good.

@bwilkerson : I'll roll in #918; otherwise: anything to wait for?

**Comment by bwilkerson** [comment]
Not that I know of.

**Comment by pq** [comment]
Published and tagged: https://github.com/dart-lang/linter/releases/tag/0.1.44

On it's way into SDK DEPS: https://dart-review.googlesource.com/c/sdk/+/46305

🎉
