### ISSUE TITLE
Publish 0.1.45.

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#932]
Ramping up pushes to weekly+ as we head to Flutter beta.

@a14n : my sense is to do a quick push before #927 lands, unless you feel strongly?  I can do another soon after or next week at the latest.

**Comment by a14n** [comment]
Feel free to land without #927 . No need to hurry up.

**Comment by pq** [comment]
Good deal.  As always, thanks so much for the contributions!

**Comment by pq** [comment]
Landed in: https://github.com/dart-lang/sdk/commit/1c5d2e9016c6d30cea7762259e4b337b26966d54
