### ISSUE TITLE
Add a crazy exception for interaction between no_adjacent_strings_in_list and prefer_adjacent_string_concatenation

### ISSUE THREAD

**Issue by kevmoo** [dart-lang/linter#965]
Enable both lints

Have something like this

```dart
[
      'webdev could not run for this project.',
      'The pubspec.yaml file has changed since the pubspec.lock file ' +
          'was generated, please run "pub get" again.'
    ]
```

Error with the plus. Error without.

The exception is pretty crazy: `prefer_adjacent_string_concatenation` ... unless they are strings in a list and `no_adjacent_strings_in_list` is enabled

**Comment by bwilkerson** [comment]
Yeah, that's not good. Thinking aloud about some possible solutions...

A lint rule can't currently determine whether another rule is enabled, and I think it would be a bad idea to allow this kind of interaction between rules. (At worst case it leads to a combinatorial explosion of tests that have to be coordinated across multiple lints.)

We could make `prefer_adjacent_string_concatenation` always ignore strings in a list.

We could document the two rules to highlight the incompatibility.

We could require users to add an ignore comment.

I'm not loving any of those. Do you have any additional suggestions, or a preference?

**Comment by kevmoo** [comment]
> I'm not loving any of those. Do you have any additional suggestions, or a preference?

"We could make prefer_adjacent_string_concatenation always ignore strings in a list." is the best and I'm ambivalent about it...

**Comment by pq** [comment]
@bwilkerson: thoughts on this?  I don't love any of the options and wonder whether they're any better than leaving things well enough alone.

**Comment by bwilkerson** [comment]
Well, that's effectively what we've been doing. :-)

Bottom line: the two rules are contradictory, and there's not much we can do about it. Rather than change `prefer_adjacent_string_concatenation` so that it's behavior is surprising when _not_ combined with `no_adjacent_strings_in_list`, users are probably better off documenting the exception to the rule.

**Comment by pq** [comment]
> Well, that's effectively what we've been doing. :-)

And this bug is a reminder!

Thanks for the quick follow-up.
