### ISSUE TITLE
false positive `await` on last statement

### ISSUE THREAD

**Issue by zoechi** [dart-lang/linter#968]
![image](https://user-images.githubusercontent.com/405837/38607785-e3df6cb6-3d79-11e8-88de-904d0904dfc4.png)

**Comment by a14n** [comment]
Regarding https://github.com/flutter/plugins/blob/3a5cb26d68f02f34d348401e448ac692a7fe4b79/packages/shared_preferences/lib/shared_preferences.dart#L102 , it looks like the lint is correct as `setString` returns a `Future`.

Is it that `setString` method you are using ?

**Comment by zoechi** [comment]
Ouch!
You're right.
Sorry for that :-/
