### ISSUE TITLE
Add @camsteffen to AUTHORS

### ISSUE THREAD

**Issue by pq** [dart-lang/linter#972]
@camsteffen: what's a good email for attribution?  I'd like to update https://github.com/dart-lang/linter/blob/master/AUTHORS.

**Comment by camsteffen** [comment]
cam.steffen94@gmail.com - thanks!

**Comment by pq** [comment]
Fixed w/ https://github.com/dart-lang/linter/commit/b18fc05483e3a4adac0482c00f89a0084ffae46c
