### ISSUE TITLE
Exit code on lint failures

### ISSUE THREAD

**Issue by danschultz** [dart-lang/linter#98]
Should the linter return a non-zero exit code if a source file fails a lint? The linter is always returning 0, which makes it difficult for a script to know if linting fails without having to parse the result.

**Comment by pq** [comment]
:+1: 

Ideally the linter CLI should be consistent with the `analyzer_cli` which bases it's exit code on the ordinal value of the severity of the analysis error.  In the case of lints, which are treated as `INFO`s, that would be `1`.  `NONE` is, as you'd expect, `0`.

I'll take a look at this.  Thanks for the report!
